- README.md
- docs/docs/dev-setup.md
- docs/docs/intro.md
Make the setup docs actually useful!
> Improved dev setup docs.

- .github/workflows/build.yml
- app/west.yml
* Don't waste space/time updating unused modules for architectures
we aren't targetting (yet).
> Exclude some unused Zephyr west submodules.

- docs/docusaurus.config.js
This PR disables sidebar collapse (globally) because we currently have few documents.  This revision can be reverted when the need arises in the future.
> docs: Add "sidebarCollapsible: false"

- docs/docs/dev-setup.md
For just building, we don't need the full Python dependencies listed in `requirements.txt`, as discovered in #12 and I've verified locally here as well. Switch the docs here slightly with a one liner.
> Only install `requirements-base.txt`

- .github/workflows/build.yml
- app/boards/shields/kyria/Kconfig.defconfig
- app/boards/shields/kyria/Kconfig.shield
- app/boards/shields/kyria/keymap/keymap.overlay
- app/boards/shields/kyria/kyria.dtsi
- app/boards/shields/kyria/kyria_left.overlay
- app/boards/shields/kyria/kyria_right.overlay
- app/dts/bindings/zmk,matrix-transform.yaml
- app/include/zmk/matrix.h
- app/src/keymap.c
- app/src/matrix_transform.c
* Refactor Kyria into separate left/right "revisions"
of the Kyria shield, and include central
kyria.dtsi file with common definition.
* Fixes for keymaps to work fully with matrix
transforms that override effective rows/columns.
* Add ability for matrix transform to do row/col
offsets, which is needed for split keyboards.
> Kyria left/right overlays, matrix transform fixes

- docs/docs/dev-boards-shields-keymaps.md
- docs/sidebars.js
Adds expanded documentation on boards/shields/keymaps in the development section.
This is a start, and I intend to add more detailed "Guides" for creating these things that will be referenced from this new doc eventually.
> Expanded dev docs on boards/shields/keymaps.

- docs/docs/dev-setup.md
> Multiple OS tabs for dev setup instructions

- app/boards/shields/lily58/keymap/keymap.overlay
- app/include/dt-bindings/zmk/keys.h
This keymap follows the one given in the [Lily58 repository as default](https://github.com/kata0510/Lily58/blob/master/Pro/Doc/buildguide_en.md#default-keymap)
Only key that outputs incorrectly is _ (underscore) in the LOWER layer because it doesn't have its own HID code.
> Add better default keymap for Lily58

- app/Kconfig
- app/src/ble.c
- app/src/split/bluetooth/central.c
- Update central split half to only accept 7.5ms
- Update latency from 5 to 30 (maximum officially supported by Apple, good benchmark)
- Add 2M PHY to connection between split halves
- Adds callback function to stop split connection params from resetting to default
> Split connection parameter adjustments and 2M PHY added

- app/boards/shields/kyria/boards/nice_nano.overlay
- app/boards/shields/kyria/kyria.conf
- docs/docs/behavior/lighting.md
- docs/docs/feature/underglow.md
- docs/sidebars.js
- docs/src/css/custom.css
This adds initial documentation for lighting behaviors as well ad RGB underglow. Step on adding RGB underglow could probably be improved. Suggestions welcome.
> Add RGB documentation

- docs/static/setup.sh
macOS is pinned to bash 3.2, which does not include support for `read -i`, as reported on Discord. Revert the couple lines that switched to using that so we *should* work on macOS, hopefully.
> macOS compatability fixes for setup.sh

- app/boards/shields/corne/corne.conf
- app/boards/shields/kyria/kyria.conf
- docs/docs/feature/underglow.md
This adds all the missing mentions where the shield needs to define the type of LED strip it uses.
This still doesn't address config values not being inherited from `<shield>.conf` by `<shield>_left.conf` and  `<shield>_right.conf`.
> Add missing configuration values for RGB underglow

- app/Kconfig
- app/src/ble.c
This fixes the odd issue where a few seconds into the connection the central would get a request to reset back to default connection parameters.
The last fix intercepted all requests and denied them unless they were 7.5ms. That was more of a band-aid fix for something that we didn't know why it was happening. 
This is tested working on my Lily58. I don't see any issues with disabling `BT_GAP_AUTO_UPDATE_CONN_PARAMS`.
> Create proper fix for split default connection bug

- app/CMakeLists.txt
- app/boards/arm/nrfmicro/pinmux.c
The macro defined for board has CONFIG_ prefix which is missing in code and hence skips some initialization code for nrfmicro 1.3
Found this issue while verifying the software charger.
Verified the fix by testing the battery voltage
> nRFMicro: Charger issue. Use correct macro for board

- .github/workflows/build.yml
This will cancel runs that get stuck on the cache west modules step. The issue here is that GitHub Actions doesn't support auto re-runs yet... https://github.community/t/how-to-retry-a-build-that-failed/16297
> fix(actions): timeout stuck cache west modules

- app/src/behaviors/behavior_mod_tap.c
found a bug when refactoring the modtap code, where the wrong loop variable was used.
> fix bug in modtap behavior which cleared the wrong keycode events

- app/CMakeLists.txt
This stops the GCC compiler on the first encountered error, so users don't have to wade through pages of macro failures to find their typo.
> stop on fatal errors

- app/boards/shields/sofle/sofle.dtsi
- docs/docs/feature/keymaps.md
- docs/docs/intro.md
Got this error: https://github.com/CrossR/zmk_config/runs/1068763312 when enabling encoders in my config, and my assumption is that its because they default to `"okay"` and I set them to that in the l/r overlay, it was causing a conflict.
~~Whilst I was fixing this, updated the intro page to move bits around and add macros since I've seen a few people question if ZMK had them yet.~~ Backed out in favour of #159.
> Fix Sofle build.

- docs/static/setup.sh
You will definitely want to clone this repo : https://github.com/bmcgavin/zmk-config-template and then remove the .git folder and push up to the zmkfirmware account - when this is done I can change this PR to point to the 'official' template repo.
> Add RoMac / non-split template support

- .gitignore
- app/boards/shields/qaz/Kconfig.defconfig
- app/boards/shields/qaz/Kconfig.shield
- app/boards/shields/qaz/qaz.keymap
- app/boards/shields/qaz/qaz.overlay
Wanted to update the default keymap to something more filled out with the available features in the main branch now - homerow modtaps and layer taps for examples.
> QAZ shield keymap update

- app/run-test.sh
The issue was the script would return an exit code of 0 because the echo succeeds. Just added an exit statement and all's well.
> Integration Tests Should Fail on Build Errors

- app/boards/shields/romac_plus/romac_plus.overlay
I'm not sure but I found the bt_unpair_combo in the overlay file. This PR seeks to clean this up.
> Remove bt_unpair_combo from romac_plus.overlay

- docs/static/setup.ps1
- docs/static/setup.sh
I've tidied up the existing `setup.sh` script as well as implementing a few of the TODOs.
I also added an equivalent script for PowerShell, since (IMO) asking for WSL just to run a single script seems overkill.
Assuming it looks good, I can add it to the docs as well, should just be a case of running
```
iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/CrossR/zmk/CrossR/ShellScriptTidyUp/docs/static/setup.ps1'))
```
The main question I had, which I expect someone has already thought about, is how to deal with the growing list of boards/shields and multiple sources of truth? Its already a pain when there is the source code and the bash script, and now there is a third source. Having a single location and deriving these two scripts from it seems best, …
> Shell script tidy up.

- app/Kconfig
* Proper max values for both split central, and
non-split keyboards.
> Fix max paired/connected settings for all configs.

- app/boards/arm/planck/Kconfig.defconfig
- app/boards/arm/planck/board.cmake
- app/boards/shields/clueboard_california/Kconfig.defconfig
- app/drivers/zephyr/Kconfig
- app/drivers/zephyr/kscan_gpio_direct.c
- app/drivers/zephyr/kscan_gpio_matrix.c
This branch is intended to address #202. I added code to do timer-based polling of the matrix instead of the original interrupt-only model.  This will hopefully pave the way for a functional Planck or Preonic board.
Summary of changes:
- A new Kconfig flag was added to enable matrix scanning (ZMK_KSCAN_MATRIX_POLLING). This is defaulted to n overall, but should be set to y for boards like Planck. 
- The polling flag used by the direct wire driver was renamed to better match the new one (ZMK_KSCAN_DIRECT_POLLING).
- Code changes were made to the matrix driver (kscan_gpio_matrix.c) to add the appropriate matrix poll logic when the flag is enabled. 
All changes were modeled after the code written in kscan_gpio_direct.c, which does something similar.
> Add polling (instead of interrupt) based matrix kscan detection, to avoid interrupt limits on stm32

- app/drivers/zephyr/ec11.c
Fixes "device.h:101:11: error: redefinition of '__device_ec11'" in firmware that has more than one encoder.
> fix(ec11): allow more than one encoder

- docs/docs/dev-setup.md
Addresses issues #191 and #189. Fixed Windows west install instructions to be consistent with Zephyr docs. Removed Windows instructions for running zephyr-env.cmd and reformatted to emphasize only GNU Arm Embedded environment variables have to be set for Windows.
> docs: Fixed Windows setup instructions

- app/drivers/zephyr/kscan_gpio_direct.c
- app/src/kscan_composite.c
The changes to kscan_composite.c are just a code improvement I noticed while debugging this code. I can split that out into a separate PR if you'd like.
> Fix direct GPIO when using interrupts

- app/include/drivers/behavior.h
- app/include/zmk/behavior.h
- app/include/zmk/events/keycode-state-changed.h
- app/include/zmk/events/position-state-changed.h
- app/include/zmk/keymap.h
- app/src/behaviors/behavior_bt.c
- app/src/behaviors/behavior_hold_tap.c
- app/src/behaviors/behavior_key_press.c
- app/src/behaviors/behavior_momentary_layer.c
- app/src/behaviors/behavior_none.c
- app/src/behaviors/behavior_reset.c
- app/src/behaviors/behavior_rgb_underglow.c
- app/src/behaviors/behavior_sensor_rotate_key_press.c
- app/src/behaviors/behavior_toggle_layer.c
- app/src/behaviors/behavior_transparent.c
- app/src/keymap.c
- app/src/kscan.c
- app/src/split/bluetooth/central.c
- app/tests/hold-tap/balanced/many-nested/events.patterns
- app/tests/hold-tap/balanced/many-nested/keycode_events.snapshot
- app/tests/hold-tap/balanced/many-nested/native_posix.keymap
When events are queued and later replayed, timing information is currently not preserved. This makes timings of things like nested hold-taps difficult. This PR adds timestamp information to position and behavior events, so timings of nested hold-taps can be handled properly. 
previously, this would return hold for the first HT and tap for the other three. Now, all three hold-taps are enabled quickly after one another.
This makes homerow mods much easier to work with. Without this implementation, if you press ctrl+alt+shift TH mods at the same time, you have to wait for 3x the tapping term for all three mods to register. With this PR, you only wait for the tapping_term once!
> Add timestamps to position and behavior events

- docs/static/setup.ps1
- docs/static/setup.sh
Added a check in `setup.sh` that will print a message and exit if the user does not have write permissions in the current directory. Should close #178.
I haven't ever used powershell, but I would be happy to try something similar if a similar issue exists in Windows.
> Exit setup if no write permissions in directory

- .gitattributes
Always check out Bashs scripts with Unix-style line endings so they work if you run them inside Docker on Windows.
> fix: check out Bash scripts with LF

- app/src/hog.c
bt_conn_lookup_addr_le() gives us a new reference that must be released with bt_conn_unref()
> fix: don't leak bt_conn refs

- docs/docs/dev-setup.md
Added install instructions for 'dfu-util' to the brew command, and to a separate code block for installing with chocolatey on Windows.
> Issue: #197 Added Setup Instructions for `dfu-util` 

- .devcontainer/.bashrc
- .devcontainer/devcontainer.json
Properly detect if we're running inside a codespace, and set up correct defaults so it works.
The reason for this change is that [`${containerWorkspaceFolder}` variable is not supported by Codespaces](https://code.visualstudio.com/docs/remote/devcontainerjson-reference#_variables-in-devcontainerjson).
This will probably almost certainly break if someone forks into a repository that is _not_ called `zmk`, but I think this is an acceptable tradeoff for right now. Hopefully we can find a more robust solution in the future.
cf. #209 for the original work on this.
> Tweak devcontainer setups for GitHub Codespaces

- docs/docs/behavior/power.md
- docs/sidebars.js
This PR updates docs for the external power control behavior added in https://github.com/zmkfirmware/zmk/pull/258
> Added docs for external power output

- app/Kconfig
* Use openmoko product ID from:
https://github.com/openmoko/openmoko-usb-oui/pull/15
> Use official USB product ID

- docs/docs/user-setup.md
- docs/static/setup.sh
I have added the ability to use either `wget` or `curl` to `setup.sh`. If the user only has one installed, then the script will use that one. I give the user the choice between the two if both are present, but realized that many users may not care which one gets used. I can remove that option and default to `curl` if both are present if that would make things simpler for the user.
Should close #200.
> Add support for wget to setup.sh

- .gitignore
VS Code can't share two folders with a Docker container at the same time, so to build with `-DZMK_CONFIG` the zmk-config repo needs to be a subfolder of the zmk repo. Added zmk-config to .gitignore to allow this.
> fix: allow nested zmk-config for dev container

- app/src/kscan_mock.c
This is necessary for testing a large number of events (e.g. every key code) within a single build/pass.
The `u8_t` limitation became apparent during end-to-end testing of #21.
Tested on the Nordic nRF52840 Dongle.
> feat(kscan_mock): Increase max number of events

- docs/README.md
- docs/docusaurus.config.js
Adding an explicit license to our documentation content, using the Creative Commons CC-BY-NC-SA license.
> Explicitly license documentation as CC-BY-NC-SA.

- .github/workflows/build.yml
- .vscode/settings.json
- app/boards/shields/nibble/Kconfig.defconfig
- app/boards/shields/nibble/Kconfig.shield
- app/boards/shields/nibble/nibble.keymap
- app/boards/shields/nibble/nibble.overlay
- app/drivers/zephyr/CMakeLists.txt
- app/drivers/zephyr/dts/bindings/zmk,kscan-gpio-demux.yaml
- app/drivers/zephyr/kscan_gpio_demux.c
- docs/static/setup.ps1
- docs/static/setup.sh
Added NIBBLE keyboard folder and keymap. The biggest change is the addition of a new kscan driver, zmk_kscan_gpio_demux, along with some driver cleanup while porting from the standard matrix driver. I also added some comments to the driver.
The demux chip is active-low ~~and the driver allows for both row2col and col2row configurations. Currently, polling is the only method that has been tested as working, but hooks for interrupt-based scanning were left in as well for the future.~~
Tested locally on a NIBBLE keyboard with nice!nano MCU.
> Add zmk_kscan_gpio_demux kscan driver & NIBBLE keyboard

- .github/workflows/build.yml
- app/boards/shields/boardsource3x4/Kconfig.defconfig
- app/boards/shields/boardsource3x4/Kconfig.shield
- app/boards/shields/boardsource3x4/boardsource3x4.keymap
- app/boards/shields/boardsource3x4/boardsource3x4.overlay
The included keymap contains 4 layers - a nav laver, a num(pad) layer, a bluetooth layer, and an extended F-layer (F13-F23)
This shield has been tested with a nice!nano board. Thanks to the awesome documentation, this implementation was relatively painless!
> Add Boardsource 3x4 shield

- app/include/zmk/hid.h
- app/src/hid.c
- Replace keypad report's NKRO bit-array with a configurable integer (DV) array.
- Refactor consumer report to a configurable size.
- Add missing constant into keypad report so that it's boot friendly.
- Integration tests run on each commit.
- End-to-end tests after rebasing #236.
- Not yet tested in use (@petejohanson offered to do so).
- Not yet tested varying the configurable sizes.  But my best guess is ...
- The keypad report should be fine until `ZMK_HID_KEYPAD_NKRO_SIZE` = 13
- The consumer report should be fine until `ZMK_HID_CONSUMER_NKRO_SIZE` = 7
> refactor(hid): configurable NKRO integer arrays & boot friendly

- docs/docs/user-setup.md
Per @petejohanson 's request, after finding this to be my blocker to a successful push to my github repo. I'm on MacOS, and was getting the error:
` ! [remote rejected] main -> main (refusing to allow an OAuth App to create or update workflow '.github/workflows/build.yml' without 'workflow' scope)`
I already had a personal access token saved in the MacOS Keychain, but since the "workflow" scope hadn't been selected, I needed to delete that one and create a new one with that option. Worked like a charm after that.
> Add Github.com personal token to prerequisites.

- docs/docs/dev-guide-new-shield.md
- docs/docs/dev-guide-usb-logging.md
- docs/docs/user-setup.md
Update the doc to add some pointers for users to create their own shield in a user repository. Mostly based on my own experience (with a lot of help from ZMK developers in the discord server).
One extra suggestion: Maybe we could have links to two official example repos:
1. One that only contains config files for customizing keymaps based on built-in shields.
2. One that defines new shield in user repo.
Although one could probably find a lot of examples just by github search, it is not clear which one is most up-to-date or working properly as references. So it might be good to have official examples as references.
> update doc for new shield in user repo

- docs/docs/behavior/outputs.md
The output selection behaviors page still referenced defines that were removed while reviewing the PR. Updated the docs to match the code.
Fixes #328
> fix(docs): remove incorrect defines for outputs

- app/include/dt-bindings/zmk/keys.h
This was a misrepresentation in the standardized keys (#236) that originated in earlier code.
- As per #236.
- [e2e-2020-11-04T19-00-32-ble.log](https://github.com/zmkfirmware/zmk/files/5489999/e2e-2020-11-04T19-00-32-ble.log)
- [e2e-2020-11-04T19-00-32-usb.log](https://github.com/zmkfirmware/zmk/files/5490000/e2e-2020-11-04T19-00-32-usb.log)
> fix(keys): Replace GUI with Application / Context Menu

- docs/docs/behavior/key-press.md
This should've been changed in: b8f6d52ae521993c736bdbeaa9cbf63a4de37a5e
> docs(key press): Replace deprecated `NUM_1` with `N1`

- app/dts/behaviors/key_press.dtsi
- app/dts/behaviors/sensor_rotate_key_press.dtsi
- app/src/hid.c
This should've been done in eff1b8223b5010d526914530c5d1d469eff356df.
> refactor(app): Remove obsolete include's of `hid_usage_pages.h`

- app/boards/shields/corne/boards/nice_nano.overlay
- app/boards/shields/kyria/boards/nice_nano.overlay
- app/boards/shields/kyria/boards/nrfmicro_11.overlay
- app/boards/shields/kyria/boards/nrfmicro_11_flipped.overlay
- app/boards/shields/kyria/boards/nrfmicro_13.overlay
- app/boards/shields/microdox/boards/nice_nano.overlay
- app/boards/shields/reviung41/boards/nice_nano.overlay
- app/boards/shields/romac_plus/boards/nice_nano.overlay
- docs/docs/feature/underglow.md
This replaces the legacy Nordic SPI master implementation in favor of SPIM. It has been confirmed to fix #305 for those who have tested it. It also reduces power consumption of the underglow part of the firmware from 55µA to 30µA. #312 should note this.
The reason for this fix working is speculated to be because SPIM does not require the CPU to transfer data packets to and from RAM. Because of this it's speculated that the CPU was busy for a few µs, which caused the strip update to get reset in the middle of transfer.
> fix(underglow): Switch from legacy SPI to SPIM

- app/boards/arm/bluemicro840/bluemicro840_v1.dts
- app/boards/arm/nice_nano/nice_nano.dts
- app/boards/arm/nrf52840_m2/nrf52840_m2.dts
- app/boards/arm/nrfmicro/nrfmicro_11.dts
- app/boards/arm/nrfmicro/nrfmicro_11_flipped.dts
- app/boards/arm/nrfmicro/nrfmicro_13.dts
This cleans up some extra commented-out items, standardizes the UART to unexposed pins, closes #294, and closes #295.
> boards: Cleanup and standardize features

- app/src/split/bluetooth/central.c
I believe the check should be `if (bt_uuid_cmp(...))` since `bt_uuid_cmp()` returns "true" when the UUID is different. Allocating `struct bt_uuid_128` ensures that memory is correctly allocated for the custom UUID.
> Fix connection to incorrect peripheral

- docs/docs/customization.md
- docs/docs/dev-boards-shields-keymaps.md
- docs/docs/dev-build-flash.md
- docs/docs/dev-clean-room.md
- docs/docs/dev-guide-usb-logging.md
- docs/docs/dev-posix-board.md
- docs/docs/dev-setup.md
- docs/docs/dev-tests.md
- docs/docs/faq.md
- docs/docs/feature/keymaps.md
- docs/docs/hardware.md
- docs/docs/intro.md
- docs/docs/troubleshooting.md
- docs/docs/user-setup.md
Aligns older documents with newer file-based ids.  Lays the groundwork for upcoming organizational refactors.
@petejohanson, the newer documents haven't been setting explicit ids and have instead relied on implicit ids from the filenames and directory layouts.  We should probably align everything to one convention.  Please reject the PR if you feel explicit ids are the better path.
> refactor(docs): Remove explicit document ids

- docs/docs/dev-guide-new-shield.md
This was missed in: 4d42e792c5fe71156ca5618513645a0e825e2fc2
I even searched all files for `id: ` before submitting yesterday.
Must be Gremlins.
> refactor(docs): Remove explicit document ids (part 2)

- docs/docs/behaviors/key-press.md
`usages` is a more accurate term in this context.
> docs(key-press): Change `codes` to `usages`

- docs/docs/troubleshooting.md
This was obsoleted by 36d3d01a22a46cdc4f1ebcabe27666dec4afface ... I believe?  @petejohanson?
@Nicell, I think this is what you were referring to on Discord.
> fix(docs): Remove obsolete VID/PID CMake error

- docs/docs/dev-guide-new-shield.md
- docs/docs/features/keymaps.md
- docs/docs/keymap-example-file.md
- docs/docs/keymap-example.md
Eases maintenance and promotes reuse.
> refactor(docs): Extract keymap examples into their own files

- .devcontainer/devcontainer.json
- docs/docs/dev-build-flash.md
The `zmk-config` mounting mechanism implemented in #307 has bad default behavior that makes docker unhappy when the user did not specify an environment variable for custom `zmk-config`.
This implementation uses docker volume. When user did not create a custom zmk-config volume, docker will create a default one and mount correctly. The customization setup is more complicated (involves deleting the default volume), but the default behavior is much well defined.
I tested it locally on MacOS.
> zmk-config mounting based on docker volume

- docs/docs/behaviors/key-press.md
- docs/docs/faq.md
- docs/docs/user-setup.md
When I documented the PowerShell Install script (#210), I must have made a typo that added an extra quotation mark at the end, but I fixed it and now copying script straight from the docs works. I also added a FAQ for wired split seeing as it comes up in the discord quite often. Lastly I removed a note in `behavior/keypress` because the open issue it referred to is now closed and in main.
> docs: Fixed PS Script, Added Wired Split FAQ, and Removed an Outdated Note

- app/cmake/zmk_config.cmake
3.15 is the minimum version required to facilitate `list(PREPEND)` used within `zmk_config.cmake`.
https://cmake.org/cmake/help/v3.15/command/list.html
Fixes #402
> build: set zmk_config.cmake cmake_minimum_required to VERSION 3.15

- .github/workflows/test.yml
- .gitignore
- app/scripts/west-commands.yml
- app/scripts/west_commands/test.py
- app/west.yml
- docs/docs/development/tests.md
This PR adds  West command 'test' that runs our testsuite.
For now it adds little value, but this opens the way to run the testsuite from python instead of a bash script. This may enable us to run the tests on Windows and add nice things like pretty printing.
The command is invoked as `west test` and runs the current test runner.
> west test command to run testsuite

- docs/docs/behaviors/key-press.md
This was obsoleted by eff1b8223b5010d526914530c5d1d469eff356df
> docs(key-press): remove references to `key press`

- app/include/zmk/hid.h
- app/include/zmk/hog.h
- app/src/endpoints.c
- app/src/hid.c
- app/src/hid_listener.c
- app/src/hog.c
The application usage used by report 1 is `HID_USAGE_GD_KEYBOARD`.  Moreover, the `keys` usage page (0x07) that primarily feeds into this report is predominantly keyboard codes.  The rest of the system should align with this naming convention.
Note: an alternative is to use `key` or `keys`, instead of `keyboard` / `keypad`.  I'm still not sure on that.  This PR is a step in the right direction however.
end-2-end test logs:
- [e2e-2020-11-13T14-04-25-ble.log](https://github.com/zmkfirmware/zmk/files/5537275/e2e-2020-11-13T14-04-25-ble.log)
- [e2e-2020-11-13T14-04-25-usb.log](https://github.com/zmkfirmware/zmk/files/5537276/e2e-2020-11-13T14-04-25-usb.log)
> refactor: change `keypad` to `keyboard`

- app/src/hid.c
Aligns with other existing conventions.
Ref https://github.com/zmkfirmware/zmk/pull/381#discussion_r528212807, I looked around and noticed there was already precedent for `keyboard_report` rather than `kb_report`.  It also aligns with how `consumer_report` is treated and how the reports types are named.
> refactor(hid): replace `kp_report` with `keyboard_report`

- app/Kconfig
- app/src/behaviors/behavior_rgb_underglow.c
- app/src/rgb_underglow.c
- docs/docs/features/underglow.md
This adds the ability for RGB underglow toggling to control ext_power to save immensely on battery when RGB is off. It also can be turned off if people want to have more fine tuned control if they have more than RGB on their board for example.
This PR also fixes the error being thrown on release of any underglow behavior and the quick blip of red LED on start when using settings.
> feat(underglow): RGB toggle controls ext_power

- app/run-test.sh
fixes bug that was introduced in the latest improvement of the testrunner. "west test" was not running all tests, neither was "west test all" or "./run-test.sh all".
> fix(tests): fix testrunner for 'all'

- .devcontainer/Dockerfile
This updates the dev container to address the following bugs
- Add nano so git has a default editor to use in case the user runs git and it needs a default editor
- Setup locales, including a generic default, so make menuconfig can be run
> Update Dev Container Fixing Small Bugs

- .github/workflows/build.yml
- .github/workflows/test.yml
Removes obsolete cache invalidation hack.
Ref: 064323b667e33b3f68e56165e9add66b7482ed68
> refactor(workflows): remove `2-` prefix from cache keys

- app/west.yml
This reduces zephyr's footprint to 33% and dramatically reduces the cloning times (`west update`).
What do you think @petejohanson?  Please check it locally just in case there's any environmental factors.
If this PR is merged, then I'll reset the CI build cache with a follow-up PR.  I suspect we'll see improvements.
> build(west): add clone-depth = 1 to zephyr and uf2

- .github/workflows/build.yml
- .github/workflows/clang-format-lint.yml
- .github/workflows/doc-checks.yml
- .github/workflows/test.yml
Cosmetic pass at aligning the conventions used in ZMK's workflows with GitHub's examples.  Based on examples found at:
https://github.com/actions/starter-workflows
I'm not personally a fan of GitHub's conventions, but aligning to them helps improve consistency.
> refactor(workflows): align GitHub workflow conventions

- app/drivers/zephyr/battery_voltage_divider.c
Updated function calls with missing reference. GPIO missing.
To my understanding:
DT_INST_GPIO_PIN() should be called instead of DT_INST_PIN()
DT_INST_GPIO_FLAGS() should be called instead of DT_INST_FLAGS()
Current implementation does not compile when using control pin.
> Updated function calls with missing reference. GPIO missing.

- .github/workflows/build.yml
- .github/workflows/test.yml
A hack to invalidate GitHub actions/cache in CI builds/tests.
Activates benefits of 90123caa4ca413f9c9e96d37e9b627ebf0407b66.
Should be reverted after 2 weeks.
> refactor(workflows): add `3-` prefix to cache keys

- app/src/ble.c
Silences the following build warning ...
```
../src/ble.c:407:13: warning: 'auth_passkey_display' defined but not used [-Wunused-function]
407 | static void auth_passkey_display(struct bt_conn *conn, unsigned int passkey) {
```
@petejohanson, is this obsolete code?
Zephyr v2.4.0 (#223) seems to have stricter build rules by default, so this will soon cause an error.
> refactor(ble): silence warning `auth_passkey_display` not used

- .github/workflows/build.yml
A multi-line list can be more merge friendly than a single-line array.
> ci(build): replace board matrix array with list

- docs/docs/development/setup.md
This is a re-implementation of GitHub PR 403 that bumps the minimum cmake version note in the docs
> Update cmake note in docs to be 3.15 which is the current minimum version

- app/boards/shields/cradio/Kconfig.defconfig
- app/drivers/zephyr/kscan_gpio_direct.c
* Switch interrupt configuration so nRF52 uses
PORT events for lower power use, and wake
from deep sleep.
* Closes #272
> Convert direct KSCAN driver to PORT events for power management improvements.

- .github/workflows/build.yml
Guards conditions aren't strictly required because the build only logs a warning if the file doesn't exist.  It still completes successfully.
> ci(build): remove proton_c guard from uf2 archive step

- app/CMakeLists.txt
This doesn't seem to be required for the current system?
> build: Remove unnecessary SYSCALL_INCLUDE_DIRS for drivers

- app/west.yml
Replaces `petejohanson` with `zmkfirmware` for ZMK's fork of Zephyr (branch `zmk-v2.3.0-with-fixes`).
> build(west): migrate to zmkfirmware/zephyr fork

- .github/workflows/build.yml
Lays the groundwork for CI building boards that don't require shields.
Tested using `dz60rgb_rev1` board.  See https://github.com/innovaker/zmk/actions/runs/397136358 for results.
> ci(build): add support for board-only builds

- .github/workflows/build.yml
These should've been added in previous PRs.
> ci(build): add missing pro-micro compatible shields

- docs/docs/development/setup.md
Add a note about cmake 3.19 with the current zmk version having a bug : https://github.com/zephyrproject-rtos/zephyr/issues/22060
Addresses issue #487
> Add note about cmake 3.19 not working with zephr ; addresses issue #487

- .devcontainer/devcontainer.json
Required for testing the documentation with the host's browser.
> feat(devcontainer): add forwardPorts 3000

- .github/workflows/build.yml
This facilitates users who can't utilize the uf2 artifact.
> ci(build): add zmk.hex to archive

- docs/docs/behaviors/bluetooth.md
- docs/docs/user-setup.md
Updated doc about bluetooth connection, and also added some explanation about BLE profiles and why one need to clear bonds from both the keyboard and the computer. Those are based on my (newly acquired) understanding of BLE, so please let me know if anything sounds incorrect.
> update doc about bluetooth

- app/scripts/west_commands/test.py
the os.system command does not return status codes but something else. The more modern `subprocess.run` has a friendlier interface.
> fix(west) test command should not swallow errors.

- .github/workflows/build.yml
The archive now contains hex and uf2 files so the uf2 suffix is no longer accurate.  It probably should've been removed as part of the earlier hex commit.
See: 97d045e7ef887f8b532838676347e8def0291215
> ci(build): remove artifact uf2 suffix

- app/CMakeLists.txt
- app/src/ble.c
- app/src/endpoints.c
- app/src/ext_power_generic.c
- app/src/rgb_underglow.c
- app/src/settings.c
This closes #379 as well as removes the unnecessary `settings.c` file by using `settings_load_subtree` in all areas that use settings.
> refactor(settings): Debounce settings with high churn and other small fixes

- .github/workflows/build.yml
- .github/workflows/test.yml
CI builds successfully without this step.
> ci(workflows): remove zephyr.base-prefer configfile

- .github/workflows/doc-checks.yml
Aligns with other jobs/workflows.  It isn't necessary.
> ci(docs-checks): remove prettier name

- .github/workflows/build.yml
- app/boards/shields/tidbit/Kconfig.defconfig
- app/boards/shields/tidbit/Kconfig.shield
- app/boards/shields/tidbit/README.md
- app/boards/shields/tidbit/boards/nice_nano.conf
- app/boards/shields/tidbit/boards/nice_nano.overlay
- app/boards/shields/tidbit/boards/proton_c.conf
- app/boards/shields/tidbit/tidbit.conf
- app/boards/shields/tidbit/tidbit.dtsi
- app/boards/shields/tidbit/tidbit.keymap
- app/boards/shields/tidbit/tidbit.overlay
- app/boards/shields/tidbit/tidbit_19key.conf
- app/boards/shields/tidbit/tidbit_19key.keymap
- app/boards/shields/tidbit/tidbit_19key.overlay
- docs/docs/hardware.md
- docs/static/setup.ps1
- docs/static/setup.sh
Bring up for the nullbits.co tidbit. This bring up includes 2 keymaps that match the assembly documentation
- standard "number pad" build
- "19 keys" build that is more dense
> Initial nullbitsco tidbit bring up

- app/include/zmk/endpoints.h
Aligns `zmk_endpoints_send_report` function declaration with its definition:
https://github.com/zmkfirmware/zmk/blob/e89aa1cde82e93bcdac7324751af2cbab4d1d44f/app/src/endpoints.c#L133
> refactor(endpoints): rename usage_report parameter to usage_page

- .devcontainer/devcontainer.json
When combined with the root user volume, this commit instructs bash to save each command to the bash history after execution, thereby sharing the bash history between any containers that use the volume.
Based on the advice of KemoNine.
> feat(devcontainer): persist bash history

- .devcontainer/devcontainer.json
This effectively caches Zephyr and its dependencies.  It also shares them between containers.
> feat(devcontainer): add volume mounts for zephyr, modules and tools

- docs/docs/development/setup.md
Latest stable version.  Also used in zmk-docker images.
> docs(setup): bump Zephyr SDK version to 0.11.4

- .github/workflows/build.yml
Ignore failed "archive artifacts" steps which are making lots of builds fail. This is needed because currently many "archive artifact" steps failing with an "ECONNRESET" error.
> ci(build): ignore failing upload-artifacts step

- app/include/zmk/keys.h
zmk_action isn't referenced anywhere.
> refactor(app): remove zmk_action

- .github/workflows/build.yml
Recent failures w/ the Zephyr 2.4 stuff pointed out a deficiency in our current automated build, which is we only build board w/ their default configs.
This includes an additional two entries in our build matrix w/ the display stuff enabled, but doesn't archive them (yet), just builds to be sure we didn't break display code.
> feature(ci): Build split w/ display enabled for testing.

- app/Kconfig
- app/src/ext_power_generic.c
- app/src/power.c
This adds support for cutting ext-power when the power management policy is set to low power using the [central Zephyr device power management system](https://docs.zephyrproject.org/2.3.0/reference/power_management/index.html#central-method).
> feat(ext-power): Cut power when PM is sleeping

- app/boards/shields/lily58/boards/nice_nano.overlay
Small update to facilitate using ws2812 strips with the lily58 pro and nice!nano
> (feat/enhance) Add ws2812 to lilly58 + nice!nano

- app/include/zmk/behavior.h
- app/include/zmk/event_manager.h
- app/src/behaviors/behavior_bt.c
- app/src/behaviors/behavior_ext_power.c
- app/src/behaviors/behavior_hold_tap.c
- app/src/behaviors/behavior_none.c
- app/src/behaviors/behavior_reset.c
- app/src/behaviors/behavior_rgb_underglow.c
- app/src/behaviors/behavior_sticky_key.c
- app/src/behaviors/behavior_toggle_layer.c
- app/src/behaviors/behavior_transparent.c
- app/src/display/widgets/battery_status.c
- app/src/display/widgets/output_status.c
- app/src/split_listener.c
This PR defines constants for  EV_EV_EVENT_BUBBLE, ZMK_BEHAVIOR_OPAQUE and ZMK_BEHAVIOR_TRANSPARENT so we don't have to use magic numbers in the `behavior_driver_api` return values.
> Use constants for EV_EV_EVENT_BUBBLE, ZMK_BEHAVIOR_OPAQUE and ZMK_BEHAVIOR_TRANSPARENT

- app/src/behaviors/behavior_to_layer.c
oops, missed this one when I rebased the constants PR.
> chore(behavior): use ZMK_BEHAVIOR_OPAQUE in to-layer behavior

- docs/docs/development/new-shield.md
Removes CONFIG_ZMK_SPLIT_BLE_ROLE_PERIPHERAL from the new shield docs
> docs(shield): Remove SPLIT_BLE_ROLE_PERIPHERAL

- app/boards/shields/bfo9000/Kconfig.defconfig
- docs/docs/development/new-shield.md
This updates the docs for split boards to show how split configurations should be done based on the changes in #510.
> docs(shield): Add docs based on #510 changes

- docs/docs/troubleshooting.md
I couldn't find the "clear" (now called reset) uf2 file. This updates the docs.
> docs(troubleshooting): fix instructions on how to download the reset uf2

- docs/static/setup.sh
This was missing from its original commit.
Refs: f3153b17d293466160c03f7cb618a2be939c55f7
> fix(setup.sh): add NIBBLE to options

- app/Kconfig
- docs/docs/development/usb-logging.md
This adds a singular Kconfig option that will enable all the USB logging related config options. It also bumps the buffer size a bit to reduce the dropped message count.
> feat(core): Add USB logging Kconfig option

- app/dts/behaviors/rgb_underglow.dtsi
- app/dts/bindings/behaviors/zmk,behavior-rgb-underglow.yaml
- app/include/dt-bindings/zmk/rgb.h
- app/include/zmk/rgb_underglow.h
- app/src/behaviors/behavior_rgb_underglow.c
- app/src/rgb_underglow.c
- docs/docs/behaviors/lighting.md
This PR implements a behavior to allow setting the HSV of the underglow via a keymap binding.
> (feat) Allow setting underglow color by key press

- app/Kconfig
- app/boards/shields/bfo9000/Kconfig.defconfig
- app/boards/shields/corne/Kconfig.defconfig
- app/boards/shields/cradio/Kconfig.defconfig
- app/boards/shields/helix/Kconfig.defconfig
- app/boards/shields/iris/Kconfig.defconfig
- app/boards/shields/jian/Kconfig.defconfig
- app/boards/shields/jorne/Kconfig.defconfig
- app/boards/shields/kyria/Kconfig.defconfig
- app/boards/shields/lily58/Kconfig.defconfig
- app/boards/shields/microdox/Kconfig.defconfig
- app/boards/shields/quefrency/Kconfig.defconfig
- app/boards/shields/sofle/Kconfig.defconfig
- app/boards/shields/splitreus62/Kconfig.defconfig
- docs/docs/development/new-shield.md
Removes the USB default under every split right half in favor of a default based on hardware capabilities in the main app Kconfig.
> refactor(Kconfig): Set USB default based on hardware capabilities

- CODEOWNERS
I've created two new GH teams for this, instead of listing individuals in `CODEOWNERS`. Once this is in, we can tweak the @zmkfirmware/boards-shields-team  and @zmkfirmware/docs-team teams as needed, etc.
> Initial simple CODEOWNERS file

- app/include/zmk/endpoints.h
- app/include/zmk/events/keycode_state_changed.h
- app/src/endpoints.c
- app/src/hid_listener.c
Aligns with the HID specification.
Usage page values were sometimes declared as `uint8_t` and sometimes `uint16_t`.  This commit aligns all instances with the HID specification for consistency.
> refactor(core): define usage page as uint16_t

- app/Kconfig
- app/src/ble.c
- app/src/hid.c
- app/src/hog.c
- app/src/split/bluetooth/central.c
- app/src/split/bluetooth/service.c
Resurrecting this change, since we're still having occasional failures w/ crashes on splits, which I believe could be related (but not fully fixed) to this.
Previously on #466 it was noted that this caused failures to sleep, but I cannot reproduce that here. Setting a low sleep timeout, and my Kyria properly sleeps and awakes from deep sleep.
This now has fixes for splits, and for non-splits, that have encountered spam/crash issues.
> Handle events from peripherals on the main work thread, avoid concurrent GATT notifications to avoid locking up central side..

- app/boards/shields/nibble/nibble.keymap
- app/boards/shields/nibble/nibble.overlay
The NIBBLE code was written before the unified ANSI + ISO board was released, which added an additional key to support ISO left shift. After the key was added (row 0, column 0), the matrix transformation was missing RC(0,0), which caused some strange behavior in the kscan driver: pressing the 7 key sent an esc/alt.
Adding RC(0,0) and updating the default keymap to match this resolves the issue. &trans is used in the new slot in the keymap and can be replaced with the pipe/backslash key if a user is building with an ISO layout.
Tested locally on my dev NIBBLE and also by @mcrosson.
> Fix offset in NIBBLE transformation and keymap

- app/run-test.sh
This allows tests to be run on platforms where '-l'
isn't implemented, such as MacOS.
> run-test.sh: use the POSIX '-L 1' for xargs

- docs/docs/features/combos.md
- docs/docs/intro.md
- docs/sidebars.js
* Since combos aren't a behavior, but a new high level keymap
feature, move under Features section.
> refactor(docs): Move combos under Features.

- docs/docs/development/documentation.md
- docs/sidebars.js
Title kind of says it all. This PR adds a new link under the Development section on how to update the zmk documentation.
This addresses ticket #426
> Add information on how to update the documentation to the docs

- docs/docs/troubleshooting.md
The old link would show pull requests from users who didn't change their branch name from main. This makes it so only pushes to this repository show up in the workflow list.
> fix(docs): Only show push workflow builds in link

- docs/docusaurus.config.js
> docs: remove redundant slash from "docs/"

- app/src/ble.c
Quiets a log error when debug logging in `ble.c` is enabled.
> Add a missing log_strdup()

- app/include/zmk/keymap.h
- app/src/behaviors/behavior_hold_tap.c
- app/src/behaviors/behavior_sticky_key.c
- app/src/keymap.c
This was suggested in the PR for https://github.com/zmkfirmware/zmk/pull/284 and tracked in https://github.com/zmkfirmware/zmk/issues/447
There are multiple places in the codebase using some variant on `_TRANSFORM_ENTRY`. This PR unifies all of those uses and renames `_TRANSFORM_ENTRY` to the more descriptive `KEY_BINDING_TO_STRUCT`
```
#define _TRANSFORM_ENTRY(idx, drv_inst)                                                       \
{                                                                                              \
.behavior_dev = DT_LABEL(DT_PHANDLE_BY_IDX(drv_inst, bindings, idx)),                      \
.param1 = COND_CODE_0(DT_PHA_HAS_CELL_AT_IDX(drv_inst, bindings, idx, param1), (0),        \
(DT_PHA_BY_IDX(drv_inst, bindings, idx, param1))),                   \
.param2 = …
```
> Refactor _TRANSFORM_ENTRY

- app/boards/shields/splitreus62/Kconfig.defconfig
- app/src/ble.c
Closes #613. I found the max length by incrementally adding a character until it broke. 16 seems to be the maximum. While researching I found that the max should be 29 for BLE (31 bytes - 2 bytes for header), so I'm not sure where the limitation is.
Preprocessor `#if` and `#error` cannot be used because you can't compare a `sizeof` output.
> fix(core): Assert BLE device name is correct length

- docs/docs/development/build-flash.md
- docs/docs/development/new-shield.md
Clarifying the need for `west flash` in a dockerized environment and providing a high-level overview of testing a board with UF2 support.  As a first-time developer in this environment, it wasn't entirely clear to me that `west flash` shouldn't work from within a Docker container and it seemed like a good opportunity to clarify the documentation.
> Update new keyboard shield testing documentation.

- app/Kconfig
- app/drivers/kscan/Kconfig
- app/drivers/kscan/kscan_gpio_matrix.c
This refactor is needed for my upcoming Ferris board work. In particular, the Ferris:
* Uses the composite kscan driver, to compose the left and right half matrixes.
* Uses matrix polling, which seems to have been broken by the interrupt work, done for sleep recently.
While there, I took the opportunity to add some more useful macros to make the conditional code a little bit easier to read.
There's also a small commit in here as well that removes some `default n` settings from some Kconfig settings to allow them to be defaulted yes elsewhere as needed.
> GPIO driver refactor - polling, multiple instance fixes, remove default Kconfigs

- app/dts/bindings/behaviors/zmk,behavior-hold-tap.yaml
- app/src/behaviors/behavior_hold_tap.c
- app/tests/hold-tap/balanced/5-quick-tap/events.patterns
- app/tests/hold-tap/balanced/5-quick-tap/keycode_events.snapshot
- app/tests/hold-tap/balanced/5-quick-tap/native_posix.keymap
- app/tests/hold-tap/balanced/behavior_keymap.dtsi
- app/tests/hold-tap/hold-preferred/5-quick-tap/events.patterns
- app/tests/hold-tap/hold-preferred/5-quick-tap/keycode_events.snapshot
- app/tests/hold-tap/hold-preferred/5-quick-tap/native_posix.keymap
- app/tests/hold-tap/hold-preferred/behavior_keymap.dtsi
- app/tests/hold-tap/tap-preferred/5-quick-tap/events.patterns
- app/tests/hold-tap/tap-preferred/5-quick-tap/keycode_events.snapshot
- app/tests/hold-tap/tap-preferred/5-quick-tap/native_posix.keymap
- app/tests/hold-tap/tap-preferred/behavior_keymap.dtsi
- docs/docs/behaviors/hold-tap.md
Tap-and-hold a hold-tap to hold the tap behavior so it can repeat.
After a tap, if the same key is pressed within `quick_tap_ms`, the
tap behavior is always picked.
This is useful for things like `&ht LSHFT BACKSPACE` where holding
the backspace is required.
Implements #288
> behaviors(hold-tap): Implement quick_tap_ms (TAPPING_FORCE_HOLD)

- docs/static/setup.sh
This should fix Issue [#659](https://github.com/zmkfirmware/zmk/issues/659).
> Change the board selection part of setup.sh, so that the 4th option ("makerdiary nRF52840 M.2") can be selected

- app/boards/shields/crbn/crbn.conf
- app/boards/shields/crbn/crbn.keymap
- app/boards/shields/crbn/crbn.overlay
Converted spaces to tabs based on kyria shield examples.
Encoder is disabled by default. Built locally with `west build -p -b nice_nano -- -DSHIELD=crbn` and uf2 flashed successfully.
> Crbn encoder

- .pre-commit-config.yaml
- CONTRIBUTING.md
clang-format and prettier need to be run on all files committed to ZMK.  Pre-commit hooks makes it easier to not forget to run these tools.
Installation is easy;
```
pip install pre-commit
pre-commit install
```
> Add pre-commit hooks for clang-format and prettier

- app/drivers/sensor/battery_voltage_divider/battery_voltage_divider.c
It is good practice in  hardware to connect a capacitor to any analog input. If anyone is using the `power_gpios`, with the idea of saving power by "enabling" the battery voltage divider with an NMOS, it takes a while for that capacitor to charge. 
This change adds just that, a 10ms delay after turning on the `power_gpios.pin`.
> Add support for capacitors on ADC for BVD

- docs/docs/development/ide-integration.md
- docs/sidebars.js
Added a docs page with tips for setting up VS Code's code completion to work in ZMK's source files. Info for other IDEs can be added here later as needed.
> docs: Add docs for setting up vscode

- app/include/drivers/behavior.h
- app/include/dt-bindings/zmk/rgb.h
- app/include/zmk/rgb_underglow.h
- app/src/behaviors/behavior_ext_power.c
- app/src/behaviors/behavior_rgb_underglow.c
- app/src/keymap.c
- app/src/rgb_underglow.c
Based on [discussions](https://discord.com/channels/719497620560543766/719565084208398406/801454819340189726) in Discord, this adds a new (optional) behavior driver callback, that allows behaviors to convert a relative binding invocation (e.g. "Toggle Power" or "Next Profile", into an *absolute* one.
This is *mostly* important for behaviors that, after #547, won't only be executed locally, but maybe "globally" on central and peripheral, we can ensure all devices converge to the same final state, not be out of sync.
I've only implemented this so far for ext power and RGB, since the "profile select" *only* matters for central side anyways.
> Add optional `binding_convert_central_state_dependent_params` callback to the behavior driver API.

- app/boards/shields/qaz/qaz.keymap
- app/boards/shields/tg4x/tg4x.keymap
- app/dts/behaviors/layer_tap.dtsi
- app/dts/behaviors/mod_tap.dtsi
- app/dts/bindings/behaviors/zmk,behavior-hold-tap.yaml
- app/src/behaviors/behavior_hold_tap.c
- app/tests/hold-tap/balanced/behavior_keymap.dtsi
- app/tests/hold-tap/balanced/many-nested/native_posix.keymap
- app/tests/hold-tap/hold-preferred/behavior_keymap.dtsi
- app/tests/hold-tap/tap-preferred/behavior_keymap.dtsi
- docs/docs/behaviors/hold-tap.md
- docs/docs/behaviors/mod-tap.md
tapping_term_ms -> tapping-term-ms
quick_tap_ms -> quick-tap-ms
Unfortunately I have not found a way to make this backwards compatible, so I don't know if you want to make this change. Thoughts?
> style(hold-tap)!: write hold-tap params with dashes

- .pre-commit-config.yaml
This uses the recommended repository for the prettier pre-commit hook and pins the versions of both hooks to avoid surprises in the future.
> fix(pre-commit): use prettier mirror and pin version

- app/dts/bindings/zmk,ext-power-generic.yaml
- app/src/ext_power_generic.c
This adjusts the initialization of the `ext_power` driver to be right after the flash systems have been initialized (All flash systems initialize by `POST_KERNEL` priority `80`). This way we know `ext_power` is properly initialized for the rest of the devices that need external power on start.
Currently, this fixes displays not turning on after deep sleep, but this should prevent similar issues in the future.
This is a step towards recovering devices when `ext_power` is in use. The next step is tying more devices to the PM policy so they can re-initialize without the entire system needing to be reset when `ext_power` is used while we keep context (idle, behaviors, etc).
I'm wondering if this init priority should be a Kconfig value.
Some boards' power switch takes some substantial time to …
> fix(ext-power): Initialize as soon as settings are available

- app/src/behaviors/behavior_hold_tap.c
A hold-tap trigger was missing in the scenario where a hold-tap behavior
was queued for a while and it's timer should've run out.
> fix(behaviors): Add missing hold-tap trigger

- app/include/zmk/battery.h
- app/include/zmk/events/battery_state_changed.h
- app/src/battery.c
Currently the battery polling sends a zmk_battery_state_changed every minute whether or not the charge level changes.  This change will only send zmk_battery_state_changed if the battery level changes.
> only send zmk_battery_state_changed on change

- app/drivers/sensor/battery_voltage_divider/battery_voltage_divider.c
- app/src/kscan.c
Newlines are automatically added to logs. These newlines are very distracting while reading through big logfiles.
> fix(logging): remove unnecessary newline

- docs/docusaurus.config.js
- docs/src/components/custom-board-form.js
- docs/src/components/power-estimate.js
- docs/src/css/power-estimate.css
- docs/src/css/power-profiler.css
- docs/src/data/power.js
- docs/src/pages/power-profiler.js
- docs/src/utils/hooks.js
This adds a battery life estimator to the docs website. This is currently working quite well I'd say, but I'd like to get some feedback before I go into the details of cleaning up the code. Try it here: https://deploy-preview-312--zmk.netlify.app/power-profiler
Todo:
> feat(docs): Add power profiler

- docs/docs/features/combos.md
A user on Discord was having trouble compiling their firmware with the combos example, this was due to the `<-1>` being invalid devicetree syntax for an array.
As @okke-formsma pointed out in #755 this is because array values are 32-bit unsigned.
I have removed the `layers = <-1>;` line in the combos example and clarified that it will default to the global scope when it is omitted.
I chose to remove the property because the example makes sense in a global scope and the property is optional, if the preference is to include it as example with valid layers let me know and I'll do that instead (e.g. `layers = <0 1>;`)
> fix(docs) omit layers -1 example, clarify it defaults when omitted

- docs/docusaurus.config.js
Now, instead of always defaulting to light theme, documentation, docs
will default to the color scheme based by the user preference (reported
by web browser as a `prefers-color-scheme` media query).
It is still possible for user to change the theme by using the switch
next to the search box. His preference will be remembered.
I've tested all existing documentation pages for compatibility with the dark
color theme and I've found no major ones.
> Added support for prefers-color-scheme in docs

- docs/src/css/codes.css
Previously the colors of operating systems were the same both for dark
and light color scheme. That's not a major issue, but adjusting the
colors for the dark theme to better match the theme looks like an
improvement.
Colors were just darkened by reversing the lightness of each color taken
from the dark theme.
> Readjusted colors for dark theme for OSes in docs

- app/run-test.sh
For comparison, default run locally:
```
PASS: tests/transparent/layered
PASS: tests/transparent/normal
PASS: tests/wpm/1-single_keypress
PASS: tests/wpm/2-multiple_keypress
west test  1238.57s user 269.31s system 654% cpu 3:50.43 total
```
WIth `J=8` on my laptop:
```
PASS: tests/wpm/1-single_keypress
PASS: tests/wpm/2-multiple_keypress
J=8 west test  468.36s user 117.44s system 595% cpu 1:38.44 total
```
It might be nice to pick a saner default based on the number of processors? Something like https://stackoverflow.com/a/23569003 ?
> feat(tests): Override test parallelism w/ `J=8` environment.

- docs/docs/behaviors/hold-tap.md
- docs/docs/behaviors/mod-morph.md
- docs/docs/behaviors/mod-tap.md
- docs/docs/behaviors/sticky-key.md
- docs/docs/behaviors/sticky-layer.md
I was running into errors when copying example code from the documentation to my personal zmk-config. This was due to missing semicolons in at least two cases, so I want to fix those errors in the doc to maybe save others some time.
Not too experienced with contributing to open source projects. I ran through the Development Guidelines in the doc and executed the checks / linting / build, hope this is all that is required :)
> Add missing semicolon to examples in doc

- app/boards/arm/bluemicro840/bluemicro840_v1.dts
This commit fixes the pin definition for BlueMicro840's blue led. Based on the
schematics, the blue led is at pin 1.10.
Signed-off-by: Anthony Amanse <ghieamanse@gmail.com>
> Fix Blue LED pin definition in BlueMicro840

- app/boards/arm/bluemicro840/bluemicro840_v1.dts
This commits adds a delay of 100ms on initializing the external
power control driver. Previously, OLED's i2c driver is failing to
initialize the display. This commit fixes that issue.
Signed-off-by: Anthony Amanse <ghieamanse@gmail.com>
> Add delay on initializing external power control for BlueMicro840

- app/boards/arm/nice60/board.cmake
Currently doing a fresh build fails due to the nRF subfamily not being set on the nice!60. It's usually inferred based on the board name (seems like a silly optimization in my opinion, but maybe I'm missing something). This allows for clean builds to function once more.
> fix(boards): Set nice!60 nRF subfamily for openocd

- app/src/ble.c
Don't allow selecting a BLE profile that is out of range to avoid reading/writing past the end of the profiles array.
> fix(ble): Ignore out of range profiles

- docs/docs/development/setup.md
Brew has a cask for GCC embedded, so we can make this guide more user friendly by providing it.
> Update macos GCC embedded section with brew cmd

- app/drivers/kscan/kscan_gpio_demux.c
I was getting erroneous presses when pressing the encoder. This PR fixes that.
+ Add a 1us sleep to let the column selection settle in order to avoid spurious keypresses when row capacitance is high (like on the encoder row)
> Fix nibble demux scan errors on encoder row

- app/boards/shields/jian/jian.keymap
The quick tap feature was implemented after the Jian was merged, but it's an integral part of using the keymap. I've been using it for a couple months now, and it works great.
I've got a similar PR in the works for the Jorne, but that has some config issues regarding RGB.
> Keymap adjustment: fixed right alt and added layer quick tap to the Jian

- app/src/behaviors/behavior_hold_tap.c
- app/tests/hold-tap/tap-preferred/6-nested-timeouts/events.patterns
- app/tests/hold-tap/tap-preferred/6-nested-timeouts/keycode_events.snapshot
- app/tests/hold-tap/tap-preferred/6-nested-timeouts/native_posix.keymap
A hold-tap timer event would be triggered too soon if the hold-tap
was delayed for longer than its tapping-term. This may cause
accidental hold behavior when the correct behavior would be tap.
By queuing the timer event instead of executing it immediately,
other delayed events get a chance to be processed properly.
This fixes an edge case introduced by https://github.com/zmkfirmware/zmk/pull/694.
> fix(behaviors): Fix timing of delayed hold-tap trigger

- docs/docs/development/setup.md
This should've been done alongside 5f9244fc21f063d68cc600667d56fda87357e424.
> docs(setup): replace `zephyr-west-action` with `zmk-docker`

- app/drivers/sensor/CMakeLists.txt
- app/drivers/sensor/Kconfig
- app/drivers/sensor/battery/CMakeLists.txt
- app/drivers/sensor/battery/Kconfig
- app/drivers/sensor/battery/battery_common.c
- app/drivers/sensor/battery/battery_common.h
- app/drivers/sensor/battery/battery_nrf_vddh.c
- app/drivers/sensor/battery/battery_voltage_divider.c
- app/drivers/sensor/battery_voltage_divider/CMakeLists.txt
- app/drivers/sensor/battery_voltage_divider/Kconfig
- app/drivers/zephyr/dts/bindings/sensor/zmk,battery-nrf-vddh.yaml
Added a driver which uses the nRF52's ADC channel on the VDDH pin to read the battery voltage when using high voltage mode. 
The voltage divider driver technically could be configured to work for this, but the way you'd configure it would be really weird and arbitrary, so I figured a separate driver would be easier to use:
```
vbatt {
// Channel must be SAADC_CH_PSELN_PSELN_VDDHDIV5 - SAADC_CH_PSELP_PSELP_AnalogInput0
io-channels = <&adc (0x0D - 1)>;
// Multiply ADC result by 5
full-ohms = <5>;
output-ohms = <1>;
};
```
> feat: Add nrf VDDH battery driver

- docs/docs/keymap-example-file.md
- docs/docs/keymap-example.md
Default keymap used an invalid character, this sets it valid.
> Update docs to use “SQT” instead of “QUOTE” 

- app/boards/shields/corne/corne.keymap
Updated default corne layout.
Reference: https://github.com/qmk/qmk_firmware/blob/master/keyboards/crkbd/keymaps/default/keymap.c
> Update to Corne default keymap

- app/Kconfig
- app/src/activity.c
- app/src/ext_power_generic.c
Fixes #882 
`PM_STATE_SOFT_OFF` doesn't tell devices to go into low power mode, so for now, I've added a line before going into sleep to force the standby state, which does tell devices to go into low power mode.
Related Zephyr fix: https://github.com/zephyrproject-rtos/zephyr/pull/37256
I've tested this with a nice!nano v2, and now VCC properly powers off during sleep.
> Fix power management to trigger low power devices

- app/boards/arm/planck/planck_rev6.dts
My Planck rev 6.1 would not register any keys without "col2row".
I also had to apply a matrix_transform in order to move them to the
correct position. Peeking into #228 helped for finding this.
> fix: Planck rev 6.1

- docs/static/setup.sh
This results in these two boards getting recognized as split, since that is the default. Credit goes to @dxmh for noticing it on Discord :)
> fix: Add missing semicolons for tidbit and eek in setup script

- app/drivers/kscan/kscan_gpio_matrix.c
- app/drivers/zephyr/dts/bindings/kscan/zmk,kscan-gpio-matrix.yaml
Refactored the GPIO matrix kscan driver so that only the data and config structures are defined in the foreach macro. Functionality is unchanged except for the addition of DT properties to adjust polling speed.
This matches how most other drivers in Zephyr are written, and it should make it easier to add other enhancements later, like improved and customizable debounce behavior.
> refactor(kscan): Demacroify GPIO matrix driver

- app/boards/shields/cradio/README.md
The Cradio shield is also used by Sweep and Hypergolic keyboards. Some revisions of these PCBs have slightly different pin arrangements compared to what's defined in the Cradio shield. 
This PR adds a section to the Cradio shield's README, explaining how users can reorder the `input-gpio` definition in their keymap file if they need to swap a few keys around for their particular PCB.
(I have run this update by @davidphilipbarr, author of Cradio.)
> fix(shield): Add note about Cradio pin arrangement

- docs/docs/development/new-shield.md
Fixes #786, until the time the behavior might be changed.
> feat(docs): Add note to clarify shared .conf files do not apply outside zmk-config

- docs/src/templates/setup.ps1.mustache
Use correct quotation marks in order for the script to properly function on this line.
> fix: Use correct quotation marks on line 65

- docs/docs/behaviors/bluetooth.md
As discussed here;
https://ptb.discord.com/channels/719497620560543766/719909884769992755/876550012153233420
It seems like the bluetooth pairing mechanism ZMK uses isn't always intuitive to new users who may expect a bluetooth device to replace the current bond when it is advertising. However since ZMK does not do this there are frequent questions on the discord and other things may be assumed at fault.
I've tried clarifying this behaviour and also moved the note about number of profiles down to reduce the amount of text in the note
There's some repetition with the `Bluetooth Pairing and Profiles` section but I think this is a tldr that will grab users attention a bit more
I've also fixed a small typo that existed here 1c05f37
See the preview here; …
> feat(docs) Clarify Bluetooth profile pairing

- docs/docs/intro.md
This change updates the [feature comparison table](https://zmk.dev/docs) to show "Mouse Keys" as "Under Development" (instead of "Planned").
Mouse Keys development is happening in PR #778.
> fix(docs): Set "Mouse Keys" as "Under Development"

- docs/docs/development/new-shield.md
Tiny change to remove the `build.yml` step from the high-level overview of creating a new shield, since that step was removed in 7bf68f2a0024accaeed3ba1abdbe075b2d29ccb2.
> fix(docs): Remove build.yml from new shield steps

- docs/src/templates/setup.sh.mustache
Fixes #949. Note that I couldn't test this end-to-end locally; it seems like a safe change but I will try it if netlify preview creates a custom link for setup.sh.
For reference, here are the display names currently in the repo:
```
$ rg -IN 'name:' **.zmk.yml
name: BDN9 Rev2
name: BlueMicro840 v1
name: Ferris 0.2
name: nice!60
name: nice!nano v1
name: nice!nano v2
name: nRF52840 M.2 Module
name: nRFMicro 1.1/1.2
name: nRFMicro 1.1 (flipped)
name: nRFMicro 1.3/1.4
name: Planck Rev6
name: QMK Proton-C
name: MakerDiary nRF52840 M.2
name: Pro Micro
name: A. Dux
name: BFO-9000
name: Boardsource 3x4 Macropad
name: Corne
name: Cradio/Sweep
name: CRBN Featherlight
name: eek!
name: Helix
name: Iris
name: Jian
name: Jorne
name: Kyria
name: MakerDiary m60
name: Microdox
name: Nibble
name: QAZ
name: …
```
> fix(setup): Fix sed delimiters for Cradio

- app/include/zmk/display.h
- app/src/display/Kconfig
- app/src/display/main.c
- app/src/display/widgets/battery_status.c
- app/src/display/widgets/layer_status.c
- app/src/display/widgets/output_status.c
- app/src/display/widgets/wpm_status.c
For displays that take a lot longer to push updates out, e.g. EPD devices, during the blocking calls to push those updates, the system work queue is currently blocked from processing other key inputs, sending HID updates, etc.
This PR adds a new Kconfig setting to allow instead using a dedicated work queue for all UI updates.
Doing so requires that all UI updates be done through `k_work` submitted to the UI work q, instead of assuming we can do that directly from the main event callbacks.
Tested on a waveshare EPD module, will test on standard OLEDs soon.
> Add optional dedicated work queue for display updates

- app/src/display/Kconfig
- app/src/display/status_screen.c
- app/src/display/widgets/Kconfig
- app/src/display/widgets/battery_status.c
- app/src/display/widgets/layer_status.c
- app/src/display/widgets/output_status.c
- app/src/display/widgets/wpm_status.c
* Only select fonts for the default built in status screen
* Leverage theme default fonts, instead of hardcoding theme
details in each component.
> refactor(display): Saner font selection/defaults.

- app/src/behaviors/behavior_hold_tap.c
Not sure why this bug didn't affect anything in the past, perhaps the ordering of the cases is special and lucky?
> Bugfix: decide_hold_tap switch statement needs breaks after cases

- app/include/zmk/hid.h
* Logical max values are signed, so for the report descriptor, use a two
byte logical max descriptor item to impart proper 0xFF max logical
value.
> fix(hid): Basic consumer code fixes for signed logical max.

- app/cmake/zmk_config.cmake
Previously shared `<board>.conf` files in the ZMK config folder were not considered in the build for split boards (no shields), but only `<board>_left.conf`,  `<board>_right.conf`. It would make sense for them to be since `<board>.keymap` can now be used as a keymap and split shields also consider `<shield>.conf`. The shared `.conf` will also override any existing left- or right-specific `.conf` similar to how it works for split shields.
Since `.conf` and `.overlay` discovery logic seem to be very similar, I also added the same change for `<board>.overlay`.
Tested with the `corne-ish_zen` left and right boards in https://github.com/LOWPROKB/zmk/tree/Board-Corne-ish-Zen-dedicated-work-queue,
> fix(keymaps): Locate shared conf and overlay for split boards.

- docs/docs/codes/modifiers.mdx
* Ensure the list of available modifier functions is clearly shown
as macros, not as basic defines.
> fix(docs): Make the modifier function examples clearer.

- app/src/hid.c
- app/src/hid_listener.c
* Properly send the KEY usage page report for modifier changes
when there are state changes to other usages pages that
include implicit modifiers.
> fix(hid): Implicit mods on non-key page events

- app/boards/shields/murphpad/Kconfig.defconfig
* Fix Murphpad conditional to ensure SSD1306 driver isn't
enabled whenever `ZMK_DISPLAY` is enabled.
@Nicell Heads up, this was a bug with a couple shields that I *fixed* a while ago, but may be sneaking into shield PRs that were from a while ago. This causes issues for anyone using ZMK_DISPLAY with other drivers like Zaphod or Corne-ish Zen, because it enables the SSD1306 driver which then fails to build.
> fix(shields): Don't enable SSD1306 automatically.

- app/dts/bindings/zmk,matrix-transform.yaml
Closes #721.
Adds `row-offset` property to `matrix-transform`.
First fixed in #735 by @devriesp, but the PR went stale and is not atomic, so submitting a separate fix just for #721.
> fix(keymaps): add row-offset property to matrix-transform

- docs/docs/behaviors/outputs.md
- docs/docs/troubleshooting.md
Adds remarks in "Output Selection" behavior and "Troubleshooting" pagesto note that the output behavior should be used to direct keystrokes to bluetooth if USB is connected. This is a frequent issue users run into, where they might be powering the keyboard with a charger device that doesn't accept USB input so they expect ZMK to automatically output over bluetooth.
I also removed the extraneous "Summary" header in Troubleshooting page, which is consistent with other "Getting Started" subpages. I think it'd be good to remove it from other pages like behaviors as well but at least they are consistent between each other right now.
> feat(docs): Add remarks on bluetooth output with USB power

- docs/src/templates/setup.sh.mustache
Looks like the flags for `curl` download were modified in #975 but not for the special case where `curl` exists but `wget` doesn't. From my testing using the modified flags prevents error messages from being written to the target file and makes it properly return a non-zero exit code.
I also checked that #1055 only happens with `curl -O` and not `wget` or `Invoke-RestMethod`, so this PR is supposed to fix #1055.
> fix(setup): Use right flags for curl when wget doesn't exist.

- docs/src/data/hid.js
C_BRI_UP
C_BRI_DN
C_BRI_MIN
C_BRI_MAX
C_BRI_AUTO
C_BKLT_TOG
C_ASPECT
C_PIP
Manual use with my Helix split keyboard using the associated ZMK shield on the desktop and in video windows.
Nothing but `C_BRI_UP` worked whatsoever to change the brightness or perspective settings of my display.
> docs(codes): Windows Support: Display Adjustment Commands

- docs/src/data/hid.js
KP_EQUAL
KP_COMMA
KP_LPAR
KP_RPAR
KP_EQUAL_AS400
NON_US_HASH
TILDE2
Manual use with my Helix split keyboard using the associated ZMK shield within an open document file alongside keyboardchecker.com.
`NON_US_HASH` produced a forward slash. `TILDE2` produced a pipe. I believe the specific results may be dependent on the region of the IME being used. As they did in fact produce characters (which likely differ based on IME), I've decided to mark them as 'true', but if reviewers disagree with this approach, I think it is also acceptable to consider them 'false' and otherwise nonfunctional.
> docs(codes): Windows Support: Symbols, Operations, and Punctuation

- docs/src/data/hid.js
C_AC_CUT
C_AC_COPY
C_AC_PASTE
K_CUT
K_COPY
K_PASTE
C_AC_UNDO
C_AC_REDO
K_UNDO
K_REDO
RET2
LCAPS
LSLCK
Manual use with my Helix split keyboard using the associated ZMK shield in an open document file alongside keyboardchecker.com within Firefox.
`LSLCK` worked for me in several windows such as document files, browser tabs, and more. Nothing else appeared to function whatsoever.
> docs(codes): Windows Support: Workflow Commands and Locks

- docs/src/data/hid.js
C_VOL_UP
C_VOL_DN
C_MUTE
C_BASS_BOOST
K_VOL_UP
K_VOL_UP2
K_VOL_DN
K_VOL_DN2
K_MUTE
K_MUTE2
Manual use with my Helix split keyboard using the associated ZMK shield. Tested within Foobar2k, MPC-HC, and YouTube.
Consumer commands (prefix `C_`) were the only kind that functioned. Keyboard commands (prefix `K_`) did not work whatsoever.
> docs(codes): Windows Support: Audio Controls

- docs/src/data/hid.js
LANG1
LANG2
LANG3
LANG4
LANG5
INT1
INT2
INT3
INT4
INT5
INT6
Manual use with my Helix split keyboard using the associated ZMK shield, within both standard QWERTY input and Japanese Microsoft IME.
I was able to get `LANG1` and `LANG2` to both work without issue on Windows. They function to switch between English and Japanese input. However, the latter three codes (`LANG3-5`) and all `INT_` codes did not produce any results for me. Either they are incompatible, or are used exclusively in other languages, and do not serve dual purposes in this case.
> docs(codes): Windows Support: Language/International Inputs

- docs/docs/development/build-flash.md
- docs/docs/development/hardware-metadata-files.md
- docs/docs/development/new-shield.md
- docs/docs/faq.md
- docs/docs/features/keymaps.md
Saw some typos when reading one of the doc pages, and ran a spellcheck against the rest. This is an American English dictionary, so it flagged `licence` and `behaviour`.
The former is valid in British English, though still was used incorrectly in that doc; `license` is the verb and `licence` the noun, so `licencing` is less valid.
`behaviour` is the British spelling as well, but since there aren't any others in all the docs, I assumed it should be called out.
If you'd rather these stay as-is, I'll pare this down to just the typos.
> Fix typos and inconsistent spellings

- docs/src/data/hid.js
C_REC
C_PLAY
C_PP
C_PAUSE
C_STOP
C_NEXT
C_PREV
C_FF
C_RW
C_SLOW
C_SLOW2
C_REPEAT
C_SHUFFLE
C_CAPTIONS
C_SNAPSHOT
K_PP
K_STOP2
K_STOP3
K_NEXT
K_PREV
K_APP
Manual use with my Helix split keyboard using the associated ZMK shield. Tested within Foobar2k, MPC-HC, Audacity, and YouTube.
Nearly every Keyboard command (prefix `K_`) did not work whatsoever. `C_PP` and `C_PAUSE` are seemingly synonymous in effect, acting as dual start/stop functions. Interestingly, `C_PLAY` restarts tracks from the beginning. In my testing, `K_APP` has an effect of opening context menus within videos/streamed content in Windows. I believe it may have alternative uses in other specific applications. `C_NEXT` works to play the next track in a playlist within Foobar2k, but I could not get …
> docs(codes): Windows Support: Media Controls

- app/boards/arm/nice_nano/nice_nano_v2.dts
Bump init delay to 50ms for nico-nano to prevent issues with OLED not being found. i.e.:
```
[00:00:00.303,375] <err> zmk: Failed to find display device
```
> Bump init delay to 50ms for nico-nano

- .vscode/settings.json
- app/run-test.sh
- app/scripts/west_commands/metadata.py
- app/scripts/west_commands/test.py
* Rewrote some python code to be more pythonic, and applied 'black' formatter
* Tests now output "FAILED" instead of "FAIL" and "PENDING" instead of "PEND" so it's easier to scan the output when the messages are not all 4 characters long
* Tests now output the results while they're running so screwups can be identified faster locally
> Some light refactoring of the test code 

- app/boards/arm/mikoto/mikoto_520.dts
Fix the devicetree for the mikoto board definition. If my understanding of `GPIO_ACTIVE_HIGH` is correct (ie. it follows the name), then to enable external power, the pin should be driven high. This follows the schematic here:
The current active-low definition was probably an oversight from the initial commit. Anyway, I also added the `init-delay-ms` line from #1082, since whatever applies to the n!n probably applies here as well.
Disclaimer: I don't use zmk, and I don't have any spare boards to test with right now. However, this *is* my board, so I feel a little responsibility to fix it.
> Fix ext-power in Mikoto board definition

- app/boards/arm/dz60rgb/board.cmake
An incredibly minor first patch.
> The DZ60 uses dfu-util, but board.cmake included openocd.board.cmake

- app/boards/shields/contra/Kconfig.defconfig
- app/boards/shields/contra/Kconfig.shield
- app/boards/shields/contra/contra.keymap
- app/boards/shields/contra/contra.overlay
- app/boards/shields/contra/contra.zmk.yml
* Adds shield configuration for the [Contra PCB](https://github.com/ai03-2725/Contra)
* Tested on nice!nano
> Add Contra shield

- app/include/zmk/ble.h
- app/src/ble.c
* Handle capturing numeric inputs while pairing and sending
final passkey once six digits entered.
This restores the basic functioning of the BLE Secure Connect numeric comparison by allowing the user to type the digits displayed on the host into their keyboard during pairing. This secures against active MITM attacks during pairing.
To test, enable the `CONFIG_ZMK_BLE_PASSKEY_ENTRY=y` config and rebuild.
So far, I've tested w/ Fedora, Android 12, and macOS Catalina.
> fix(ble): Restore BLE SC passkey entry for pairing.

- .github/workflows/build.yml
- app/core-coverage.yml
Refactors the build workflow to use hardware metadata to accomplish the following:
- Nightly, build every single onboard MCU board and board+shield combo possible
- Whenever app/** is changed (minus app/boards), run a short, premade core builds list
- Whenever app/boards is changed, build every board+shield combo that's affected by the changes
Here's a nightly build: https://github.com/Nicell/zmk/actions/runs/1519228121
Here's a boards change run: https://github.com/Nicell/zmk/actions/runs/1517831312
Here's a core run: https://github.com/Nicell/zmk/actions/runs/1517789825
Todo:
> feat(ci): Use metadata for builds

- docs/docs/behaviors/hold-tap.md
This PR replaces the deprecated `SCLN` keycode in the positional hold-tap example, which fixes #646 (I found no other deprecated keycodes in the docs).
Also I tweaked the label of the behavior in the example. We see folks copying this behavior node and duplicating it for the right hand, then forgetting to modify the "label" value and getting confusing runtime ehavior. If we modify the label to be left-specific like this it might be a better hint to change it when duplicating it.
Two unrelated changes in one PR isn't ideal but they were small enough that I thought I shouldn't split them up; ideally we would not squash this if we merge the PR.
> fix(docs): Fix issues with positional hold-tap example

- docs/sidebars.js
Currently, the documentation for `&key_repeat` [exists](https://zmk.dev/docs/behaviors/key-repeat/) but is not accessible via the sidebar. 
This small PR adds the page to the sidebar:
https://deploy-preview-1129--zmk.netlify.app/docs/behaviors/key-repeat
> fix(docs): Add `behaviors/key-repeat` to sidebar

- docs/docs/development/new-shield.md
This fixes the [prettier warning which causes the checks to fail](https://github.com/zmkfirmware/zmk/runs/5215608764?check_suite_focus=true#step:4:13) for 43ffa6c76077a446ee0ebc8ebc39ebc09eae4b57.
Currently:
```console
> prettier --check .
Checking formatting...
[warn] docs/development/new-shield.md
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
Error: Process completed with exit code 1.
```
With this PR, on my local machine, prettier is happy again:
```console
$ prettier --check .
Checking formatting...
All matched files use Prettier code style!
```
> fix(docs): Remove trailing whitespace (to appease prettier)

- app/boards/shields/bat43/Kconfig.defconfig
- app/boards/shields/bat43/Kconfig.shield
- app/boards/shields/bat43/bat43.keymap
- app/boards/shields/bat43/bat43.overlay
- app/boards/shields/bat43/bat43.zmk.yml
See https://kbd.dailycraft.jp/bat43/ for details.
The shield uses the default keymap of the bat43, with the tiny tactile
pushbuttons used for output selection and bluetooth functions.
> feat(shield): Add Bat43 shield

- app/boards/shields/two_percent_milk/Kconfig.defconfig
- app/boards/shields/two_percent_milk/Kconfig.shield
- app/boards/shields/two_percent_milk/two_percent_milk.conf
- app/boards/shields/two_percent_milk/two_percent_milk.keymap
- app/boards/shields/two_percent_milk/two_percent_milk.overlay
- app/boards/shields/two_percent_milk/two_percent_milk.zmk.yml
2022 renewal of PR #684 with updated metadata file.
> Added support for 2% Milk (Updated with metadata)

- docs/docs/intro.md
Update `intro.md` in docs to allow for easier accessibility for tap-dance documentation
> Tap-Dance Documentation Fix - Update intro.md

- docs/docs/troubleshooting.md
Add a short note to troubleshooting dtlib.DTError section, on locating the `.dts.pre.tmp` file in the next GH action step.
> feat(docs) Add note on locating tmp file in GH action

- docs/docs/behaviors/macros.md
Windows unicode input using alt + number sequence requires using the keypad keycodes, as noted in [the linked doc](https://support.microsoft.com/en-us/office/insert-ascii-or-unicode-latin-based-symbols-and-characters-d13f58d3-7bcb-44a7-a4d5-972ee12e50e0):
>  You must use the numeric keypad to type the numbers, and not the keyboard. Make sure that the NUM LOCK key is on if your keyboard requires it to type numbers on the numeric keypad.
This PR fixes the example sequences and improves the description slightly. Tested before and after the fix and confirmed the keypad keycodes are required.
> fix(docs): Fix Windows unicode macro example

- docs/src/components/hardware-list.tsx
renamed Boards to Keyboards to not confuse with zmk board lingo (a pcb with a processor)
renamed Keyboard to Interconnect to more accurately state what is presented in the composite board sections.
provided description of what interconnect refers to.
> Cleared up ambiguity on supported hardware page

- docs/docs/troubleshooting.md
There are feedback on Discord about difficulty locating settings_reset firmware from core-coverage workflow job. This change adds an additional procedure for users to build their own `settings_reset` UF2 with their `zmk-config` repository workflow.
> feat(docs): Add settings_reset build instructions

- docs/netlify.toml
Enabled CORS so external tools can fetch the metadata file.
> fix(docs): Allow CORS for hardware-metadata.json

- docs/docs/user-setup.md
This change tweaks the `powershell` setup script invocation in the docs so that if it exits with a failure it will not close the current terminal window. We saw quite a few folks in Discord confused because of this behavior.
From what I have tried this helps the current shell stay alive for error cases and doesn't persist a nested shell even after the command runs successfully. I tried with Windows 11 and Powershell version 5.1, but continues working if I try different versions down to `3` with `powershell -Version 3`.
That being said I am not very knowledgeable in Powershell and I don't know how backwards-compatible the `-Command` switch is. I would appreciate any advice or testing from folks with different Windows versions.
Fixes #1206.
> fix(docs): Improve powershell command for setup script for failure cases

- .github/workflows/test.yml
- app/run-test.sh
* To parallelize our tests, generate a dynamic matrix
of tests to run.
@Nicell Thoughts on this to cut down on our test time? See https://github.com/petejohanson/zmk/actions/runs/2084238754 for an example.
If we do this, we might be to the point we want to get a Teams subscription to GH, since that would bump our concurrent builds up from 20 to 60: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
> refactor(tests): Use GH Actions matrix for tests.

- app/src/behaviors/behavior_hold_tap.c
Related to discussion during development of tap-dance behavior:
https://github.com/zmkfirmware/zmk/pull/1139#discussion_r810564682
This PR suggests to remove the `struct behavior_hold_tap_data` because it is not used to store data for each hold tap.
> fix(behaviors): Remove `behavior_hold_tap_data`

- app/src/ext_power_generic.c
- app/src/rgb_underglow.c
Needed because k_work_reschedule can return positive success codes.
This fixes an issue where bindings such as `RGB_TOG` or `EP_OFF` would also press the key underneath them in the keymap, and never release it.
> Stop persisted binding keypress fallthrough

- docs/docs/behaviors/layers.md
Addresses at least part of #1043.  That issue also mentions linking to the conditional layers page on the Keymaps page, but I don't see a natural place to do that, as that page doesn't link to any of the other layers behaviors.
> feat(docs): Reference conditional layers from the layers behavior page

- app/boards/shields/hummingbird/Kconfig.defconfig
- app/boards/shields/hummingbird/Kconfig.shield
- app/boards/shields/hummingbird/hummingbird.keymap
- app/boards/shields/hummingbird/hummingbird.overlay
- app/boards/shields/hummingbird/hummingbird.zmk.yml
* Reference shield for the Seeed(uino) XIAO interconnect.
> feat(shields): Add Hummingbird shield

- docs/docs/development/setup.md
`cmake` now requires version `>3.20.0`, so update Debian/Ubuntu instructions. Note that 22.04 LTS will officially be released on April 21st but it will have [version 3.22.1](https://packages.ubuntu.com/jammy/cmake). Also added PyPI as an easy to install method recommendation, which is also [what ZMK Docker image uses](https://github.com/zmkfirmware/zmk-docker/blob/d69745c8be52487bb47dede1a93456076a778b78/Dockerfile#L28).
> fix(docs): Fix cmake version requirements

- app/boards/arm/bdn9/Kconfig.defconfig
- app/boards/arm/bdn9/bdn9_rev2.conf
- app/boards/arm/bdn9/bdn9_rev2.dts
Tested on my BDN9. Skipping the two actual underglow LEDs in the chain for now, so we use underglow just for the per-key LEDs.
> feat(boards): Add BDN9 rev2 RGB support

- app/include/zmk/hid.h
* Switch to a logical max for the consumer page
that avoid signed issue, and still allows
full range of documented consumer page
values.
> fix(hid): Use a full valid range for consumer page

- app/west.yml
Accidentally left ZMK referencing my fork of Zephyr! Fixing it.
> fix: Properly use zmkfirmware Zephyr version.

- docs/docs/behaviors/sticky-key.md
Documentation for [sticky key behavior](https://zmk.dev/docs/behaviors/sticky-key) does not mention `quick-release` like the [sticky layer behavior](https://zmk.dev/docs/behaviors/sticky-layer) page. #903 shows that there is a use case for this setting for sticky keys. This PR adds these findings to the documentation page so people with this problem don't end up having to search through Github issues.
Edit: Included documentation for #1226
> Update sticky key documentation with new settings

- app/boards/arm/bluemicro840/bluemicro840_v1.dts
- app/boards/arm/bt60/bt60.dtsi
- app/boards/arm/mikoto/mikoto_520.dts
- app/boards/arm/nice60/nice60.dts
- app/boards/arm/nice_nano/nice_nano.dts
- app/boards/arm/nice_nano/nice_nano_v2.dts
- app/boards/arm/nrfmicro/nrfmicro_13.dts
- app/boards/arm/s40nc/s40nc.dts
- app/boards/seeeduino_xiao_ble.overlay
- app/src/battery.c
- docs/docs/features/battery.md
- docs/sidebars.js
battery.c now uses the `zmk,battery` chosen node to select a battery sensor. Using the node labeled `"BATTERY"` is maintained as a fallback, but is now deprecated. Custom boards/shields should switch to using the chosen node.
Also changed to fetch all channels to support fuel gauge sensors that don't support fetching individual channels like max17055.
> feat!: Add chosen node for battery

- .github/workflows/build-user-config.yml
Closes https://github.com/zmkfirmware/zmk/issues/1178
> ci: add reusable user-config workflow

- docs/docs/features/displays.md
- docs/docs/intro.md
After #1248 was merged, I noticed that the destination of the relative link can sometimes be incorrect depending on the trailing slash of the current URL:
* Access the Displays page _via the sidebar_ then the current URL is `https://zmk.dev/docs/features/displays` and the relative link works: `https://zmk.dev/docs/behaviors/power` ✅
* Access the Displays page _directly_ (or refresh the above) then the current URL becomes `https://zmk.dev/docs/features/displays/` (a trailing slash is added), so of course the relative link results in a 404: `https://zmk.dev/docs/features/behaviors/power` ❌
The fix is to link to the document _file path_ rather than the document _URL_; this ensures that the link resolves regardless of trailing slash config – Docusaurus just takes care of it. More information …
> fix(docs): Ensure relative links always resolve

- app/west.yml
Zephyr upstream seemed to have force-pushed to their `sof` module, causing the sha1 referenced from the Zephyr `west.yml` to be missing. Exclude for now, we don't use it.
> fix: Exclude `sof` module to avoid build breakage.

- app/Kconfig
* Larger stack for split peripheral notifications
to avois stack overflow with logging on.
> fix(split): Raise split notification stack size.

- app/Kconfig
- app/src/ble.c
- app/src/split/bluetooth/central.c
Adds support for configuring the BLE connection interval to allow users to force a faster connection and lower the latency of BLE. The original idea came from @Nicell youtube video where he tested the latency of different things and showed that BLE with a forced connection interval of 7.5ms is as fast as wired when not using ZMKs 1ms polling.
The new configuration variables are
Setting the connection interval, setting both these to the same value forces a set polling rate so both 6 will give you 7.5 ms
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6 
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
Setting for latency and timeout
CONFIG_BT_PERIPHERAL_PREF_SLAVE_LATENCY=30
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
> Add support for BLE connection interval

- docs/docs/features/combos.md
The PR rephrases the description of the `timeout-ms` configuration for Combos.
This is based on the message from `joshua.r.smith#6858` [on Discord](https://discord.com/channels/719497620560543766/719909884769992755/946023231431802910):
> I have a question about the combos feature. **There is a `timeout-ms` parameter for which the docs indicate the value is the number of ms the combo must be pressed for the combo effect to trigger. However, it seems like that value is the length of the window in which all of the keys in the combo must be pressed in order to successfully trigger the combo.** Regardless of the value of timeout-ms, as soon as all they keys are pressed in time, the combo is triggered. I would like to trigger the combo after holding the combo for a particular duration; …
> fix(docs): Clarify `timeout-ms` for Combos

- docs/docs/customization.md
Discussed here: https://discord.com/channels/719497620560543766/883452966114324550/970385441134104747
Code snippets in titles are not formatted properly in page titles
> fix(docs): Remove code-snippet backticks from customization.md title

- app/src/activity.c
- app/src/ext_power_generic.c
When using `pm_power_state_set`, we skip over all of the device-related power management seen here: https://docs.zephyrproject.org/latest/services/pm/system.html#system-power-management
Although I wasn't able to 100% confirm this from reading Zephyr code, `pm_power_state_force` seems to force the next state to what you want, and then all of the rest of the diagram follows as expected setting device power states. In our case, `STATE_OFF` sets devices to standby, which is why those actions got updated.
We should probably be aware of the fact that this currently just sets CPU 0 to off. This may be an issue with dual/multi-core chips like the nrf5340. I'm not sure about that though.
> fix(sleep): use pm_power_state_force for proper device power management

- app/drivers/kscan/kscan_gpio_direct.c
- app/drivers/kscan/kscan_gpio_matrix.c
- app/drivers/zephyr/dts/bindings/kscan/zmk,kscan-gpio-direct.yaml
Rewrote the direct GPIO kscan driver to match the improvements made to the matrix driver in 82cb76269811105bbe89569367d888d7a3fdd083 and f946dc68931a712bae1c2be0ed1581815ccc8767. It now uses the same debouncing system as the matrix driver.
> refactor(kscan): Match direct GPIO driver to matrix driver

- app/Kconfig
- app/src/battery.c
Makes the interval between BAS GATT reports for battery level configurable using a new `CONFIG_ZMK_BATTERY_REPORT_INTERVAL` setting. Related: https://github.com/zmkfirmware/zmk/issues/1273#issuecomment-1127103347
There are a few decisions I made that I am not 100% sure of, comments welcome:
- Location of Kconfig: right now this is under the battery driver, but it could be under `app/Kconfig` (in a new submenu under "Basic keyboard setup"?) or is there a better spot?
- Name of setting: I didn't mention BAS GATT since it is not very familiar to users. Should it have "level" in the name?
- Should the delay until first report also be configurable, or equal to the interval? I thought there isn't much use in making this configurable and 1 minute seems like a good value.
- Unit of interval: …
> feat(battery): Add Kconfig setting for battery level report interval

- .github/workflows/build-user-config.yml
- Add `artifact_name` as a workflow dispatch option. Users can specify a different output artifact name alongside custom build and config path.
- Use `set -x` for verbose output of shell commands. This will display content of all environment variables and aid troubleshooting.
- Simplify `grep` one-liner command for displaying Kconfig file.
- Steps naming consistency.
- Shell `if` `then` statement consistency.
> Edits and improvements to the reusable build workflow

- docs/docs/development/new-behavior.md
- docs/sidebars.js
Co-Authored-By: Henré Botha <henrebotha@gmail.com>
Co-Authored-By: Cem Aksoylar <caksoylar@users.noreply.github.com>
Co-Authored-By: Dom H <dom@hxy.io>
This PR adds a guide for developers wishing to create new behaviors for ZMK. The behavior guide is largely inspired by the new shield guide, and shows users how to:
> feat(docs): Add New Behavior Guide

- docs/docusaurus.config.js
This PR aims to make trailing slashes in URLs more consistent on https://zmk.dev.
Wherever we link to a page (in the sidebar and in other menus), the links do not include a trailing slash – e.g. `href="zmk.dev/blog"`, `href="zmk.dev/docs/displays"`, etc. This is fine. 
However, accessing a page directly via it's URL (or refreshing a page that you're already on) will cause a trailing slash to be added to the URL – e.g. `zmk.dev/blog/`, `zmk.dev/docs/displays/`, etc.
Easiest to demonstrate in a quick video clip:
https://user-images.githubusercontent.com/60922914/163870576-43fc4d16-e900-414b-9da4-9a6af7c60e11.mov
With the Docusaurus configuration option [`trailingSlash`](https://docusaurus.io/docs/api/docusaurus-config#trailing-slash) set to `false`, all URLs are without a trailing slash …
> fix(docs): Standardize URLs with no trailing slash

- app/boards/shields/leeloo/README.md
- app/boards/shields/leeloo/leeloo.dtsi
A quick update to the leeloo.dtsi file to ensure OLEDs are properly supported with the 'chosen' node reference; and, a correction to the README.md file to adjust the direction of the folder separators.
> Add 'chosen' node reference for OLEDs to leeloo.dtsi, and a correction to README.md.

- docs/docs/development/build-flash.md
This PR addresses issue #1285.
Adds a tip block with the solution from the referenced issue.
It is currently under the "Building For Split Keyboards" header but could be elsewhere?
Tested and formatted appropriately.
> Documentation update - tip for improving build times

- app/drivers/gpio/CMakeLists.txt
- app/drivers/gpio/Kconfig
- app/drivers/gpio/Kconfig.595
- app/drivers/gpio/gpio_595.c
- app/drivers/zephyr/dts/bindings/gpio/zmk,gpio-595.yaml
* Use SPI for sending serial data.
* Supports 1-4 shift registers chained together by
setting `ngios` property appropriately.
> feat(gpio): Add 595 shift register driver.

- app/dts/behaviors/caps_word.dtsi
- app/src/behaviors/behavior_caps_word.c
- app/tests/caps-word/continue-with-modifiers/events.patterns
- app/tests/caps-word/continue-with-modifiers/keycode_events.snapshot
- app/tests/caps-word/continue-with-modifiers/native_posix_64.keymap
- docs/docs/behaviors/caps-word.md
* Continue caps word when mods are changed, and
match the continue list on combination of
explicit and implicit modifiers.
> feat(behaviors): Continue on mods in caps word.

- app/drivers/CMakeLists.txt
- app/drivers/gpio/Kconfig
- app/drivers/gpio/Kconfig.595
- app/drivers/gpio/Kconfig.mcp23017
* Avoid defining the ZMK GPIO drivers lib if none of the drivers  are
selected.
> fix(drivers): Avoid build failures for GPIO driver

- app/src/conditional_layer.c
- app/tests/conditional-layer/same-layer-reached-both-ways/events.patterns
- app/tests/conditional-layer/same-layer-reached-both-ways/keycode_events.snapshot
- app/tests/conditional-layer/same-layer-reached-both-ways/native_posix_64.keymap
- app/tests/conditional-layer/same-layer-reached-differently/events.patterns
- app/tests/conditional-layer/same-layer-reached-differently/keycode_events.snapshot
- app/tests/conditional-layer/same-layer-reached-differently/native_posix_64.keymap
- app/tests/conditional-layer/tri-layer-lt/events.patterns
- app/tests/conditional-layer/tri-layer-lt/keycode_events.snapshot
- app/tests/conditional-layer/tri-layer-lt/native_posix_64.keymap
* Proporly handle multiple  conditonal layers w/ the same target
`then-layer` values.
* Move handling to work callback, to avoid re-entrance for cascading
layers enabling other layers.
> fix(keymaps): Handle matching `then-layer`s.

- app/boards/shields/two_percent_milk/two_percent_milk.keymap
A very minor nitpick to improve the indentation styling for the 2% Milk keymap. Removes the leading space for each affected line.
> fix(shields): Fix indentation in two_percent_milk.keymap

- app/src/usb.c
* Fix detection of USB power vs. configuration, to ensure endpoint
selection works properly with power-only USB attached.
> fix(usb): Correctly detect USB connection status. 

- app/src/backlight.c
This is just a minor tweak to address #1361 so that the RGB an backlighting behave the same
> fix(backlight): Improve initial power on behaviour

- app/boards/shields/corne/Kconfig.defconfig
- app/boards/shields/elephant42/Kconfig.defconfig
- app/boards/shields/jorne/Kconfig.defconfig
- app/boards/shields/knob_goblin/Kconfig.defconfig
- app/boards/shields/kyria/Kconfig.defconfig
- app/boards/shields/leeloo/Kconfig.defconfig
- app/boards/shields/lily58/Kconfig.defconfig
- app/boards/shields/lotus58/Kconfig.defconfig
- app/boards/shields/microdox/Kconfig.defconfig
- app/boards/shields/murphpad/Kconfig.defconfig
- app/boards/shields/nibble/Kconfig.defconfig
- app/boards/shields/sofle/Kconfig.defconfig
- app/boards/shields/tidbit/Kconfig.defconfig
- app/boards/shields/zodiark/Kconfig.defconfig
* Horizontal/Vertical resolution max is now defaulted
from the DTS chosen display automatically, so
remove the duplication in our shield Kconfig.
Found this while helping on Discord, sinze Zephyr 3.0, the Kconfig settings for this is now defaulted from the DTS, so no need to set in the shield Kconfig code.
> refactor(shields): Remove res max Kconfigs

- app/boards/shields/two_percent_milk/boards/nice_nano.overlay
- app/boards/shields/two_percent_milk/boards/nice_nano_v2.overlay
- app/boards/shields/two_percent_milk/boards/nrfmicro_11.overlay
- app/boards/shields/two_percent_milk/boards/nrfmicro_11_flipped.overlay
- app/boards/shields/two_percent_milk/boards/nrfmicro_13.overlay
- app/boards/shields/two_percent_milk/two_percent_milk.conf
Adds RGB support to the 2% Milk. Tested by @treezoob using the nice!nano V2, working as expected so far.
> feat(shields): Add RGB support to 2% Milk

- docs/docs/behaviors/underglow.md
These defines were not documented, but they are now.
> fix(docs): Add missing underglow on/off defines

- app/boards/shields/a_dux/a_dux.dtsi
- app/boards/shields/cradio/README.md
Cleaning up a couple missed instances of old `&pro_micro_d/&pro_micro_a` naming in shields.
> fix(shields): Remove uses of deprecated pro_micro_a/d nodes

- docs/docs/behaviors/caps-word.md
- docs/docs/config/backlight.md
- docs/docs/config/battery.md
- docs/docs/config/behaviors.md
- docs/docs/config/combos.md
- docs/docs/config/displays.md
- docs/docs/config/encoders.md
- docs/docs/config/index.md
- docs/docs/config/keymap.md
- docs/docs/config/kscan.md
- docs/docs/config/power.md
- docs/docs/config/system.md
- docs/docs/config/underglow.md
- docs/docs/customization.md
- docs/docs/features/battery.md
- docs/docs/features/combos.md
- docs/docs/features/debouncing.md
- docs/docs/features/underglow.md
- docs/sidebars.js
This adds a new "config" section to the sidebar with documentation on (most of) the Kconfig and Devicetree options we support.
I documented everything manually, because I didn't want to try to figure out how to write a Kconfig parser in JavaScript, get it reading files from outside the docs directory, and organize it in a reasonable way. As a future improvement, we could try to generate some of this dynamically so it can't get out of sync with the code.
This also adds a section describing how to actually edit configuration, and I replaced some redundant information in the rest of the documentation with links to the new pages.
> docs: Add documentation for config options

- app/drivers/kscan/Kconfig
- app/drivers/kscan/kscan_gpio_matrix.c
Add optional Kconfig setting to delay scanning after each
output column is set, and inputs are read, to allow inputs
to "settle" after the last column is set back to inactive.
This was found during work on the RP2040 hardware, but this was also encountered by jmnw on Discord for an stm32 build recently.
Without a delay, on some platforms we need to have a small delay after disabling the previous output column to prevent it from causing a "false positive" detected on an input for the next column.
> feat(kscan): Kconfig for optional scan delay.

- docs/docs/behaviors/macros.md
- docs/docs/config/behaviors.md
Added information about the `CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE` config option to the macros page in the docs.
> feat(docs): Added behavior queue limit section to macros page

- app/drivers/display/il0323.c
- app/src/display/Kconfig
- app/src/display/main.c
A hopeful fix for slow initialization of devices with displays with slow response times, by moving the init to the display queue, which may be a secondary display queue, to free up system queue for handling inputs right away.
> fix(display): Initialize display on queue as well.

- docs/docs/behaviors/underglow.md
Some minor spelling/grammar issues were bugging me but when I fixed them the sentence still felt awkward so I went for something more concise since it's already pointing the reader towards the syntax example.
I also removed the second "See below for an example" since the examples are in the very next section with a big heading to advertise them.
> Change wording in RGB_COLOR_HSB description

- app/src/behaviors/behavior_hold_tap.c
- app/src/combo.c
- app/src/event_manager.c
- app/tests/combo/combos-and-holdtaps-3/events.patterns
- app/tests/combo/combos-and-holdtaps-3/keycode_events.snapshot
- app/tests/combo/combos-and-holdtaps-3/native_posix_64.keymap
- app/tests/combo/combos-and-holdtaps-4/events.patterns
- app/tests/combo/combos-and-holdtaps-4/keycode_events.snapshot
- app/tests/combo/combos-and-holdtaps-4/native_posix_64.keymap
Continuing on the work in #1405 this adds another fix in the hold tap event handler clean up code.
Hopefully fixes #986 as part of this.
> Combo + hold tap fixes (take 3)

- app/boards/shields/eternal_keypad/Kconfig.defconfig
- app/boards/shields/eternal_keypad/Kconfig.shield
- app/boards/shields/eternal_keypad/README.md
- app/boards/shields/eternal_keypad/boards/nice_nano_v2.overlay
- app/boards/shields/eternal_keypad/eternal_keypad.conf
- app/boards/shields/eternal_keypad/eternal_keypad.dtsi
- app/boards/shields/eternal_keypad/eternal_keypad.keymap
- app/boards/shields/eternal_keypad/eternal_keypad.overlay
- app/boards/shields/eternal_keypad/eternal_keypad.zmk.yml
- app/boards/shields/eternal_keypad/eternal_keypad_lefty.keymap
- app/boards/shields/eternal_keypad/eternal_keypad_lefty.overlay
- app/boards/shields/eternal_keypad/eternal_keypad_lefty.zmk.yml
Add Eternal Keypad gaming keypad.
> feat(shields): Add Eternal Keypad

- app/src/usb.c
All credit for this one goes to @xudongzheng (thanks for helping debug this!). Should fix the issue where keyboards go unresponsive after their host machine wakes from sleep due to the USB driver entering an error state. I was able to both reliably reproduce the issue before the patch goes in and confirmed it no longer occurs post patch.
The `USB_DC_RESUME` state indicates the host event has resumed the connection. Adding it to the list of valid connection states to prevent the error when waking from sleep.
Zephyr API Link:
https://docs.zephyrproject.org/apidoc/latest/group____usb__device__controller__api.html#gac09e3e0af1a2b41a5bfbad91f900baf7
fixes #1372
See below for logs both before and after the patch. After the fix goes in the `FAILED TO SEND OVER USB: -11` error being generated by …
> fix(usb): add USB_DC_RESUME to supported states

- docs/docs/behaviors/hold-tap.md
Having misinterpreted the tap-preferred documentation myself and seeing other people on discord doing the same mistake, I suggest rewording it slightly. The current wording ("It triggers the tap behavior when another key is pressed") may falsely be interpreted as "tap-preferred" being the mirror of "hold-preferred": i.e., that it resolves all interrupts within the tapping-term as tap.
(As an aside, if one wants to implement the mirror of "hold-preferred", one can do so using positional hold taps with `hold-trigger-key-positions` set to a dummy key (setting it all empty is interpreted as all keys)).
> feat(docs): Fix ambigous tap-preferred documentation

- docs/docs/behaviors/hold-tap.md
The bindings for the toggle-layer-on-tap/momentary-layer-on-hold example code were backwards, resulting in toggle-on-hold. This also made momentary unachievable.
> fix(docs): corrected mo_tog example on hold-tap page

- app/boards/arm/planck/planck_rev6.keymap
- app/boards/shields/crbn/README.md
- app/boards/shields/crbn/crbn.keymap
This is a port of the QMK planck keymap. Given the one for the CRBN is identical I fixed it at the same time. I think I followed the indentation guidelines this time
> Planck keymap

- .github/workflows/build.yml
- .github/workflows/test.yml
> ci: remove `4-` prefix from zephyr-modules cache keys

- app/drivers/kscan/Kconfig
- app/drivers/kscan/kscan_gpio_matrix.c
- docs/docs/config/kscan.md
* Add a new Kconfig option, `ZMK_KSCAN_MATRIX_WAIT_BEFORE_INPUTS` to delay reading inputs after setting an output active.
> feature(drivers): Option for read wait on matrix.

- docs/src/data/hid.js
F13-F19 are confirmed to work on Windows 11 in VSCode 1.71.2.
Refs: #1476
> docs(codes): Windows Support: F13-F19

- app/Kconfig
Default values for DIS GATT characteristics for:
* Vendor ID
* Product ID
* Manufacturer
* Model
This should help our ZMK keebs show properly in more places on various hosts, and hopefully help with identification for programs like Karabiner Elements on macOS.
> feat(ble): Default a few configs for DIS GATT svc.

- docs/src/data/power.js
- docs/src/pages/power-profiler.js
Adds the nice!view based on my profiling using a Nordic PPK2. Idle is lower than 1uA, but I wrote this originally to use uA as the base unit, so 1 will do.
> docs(power profiling): add nice!view

- app/include/dt-bindings/zmk/keys.h
- docs/src/data/hid.js
This PR adds additional aliases to NON_US_BACKSLASH (NUBS) and NON_US_HASH (NUHS), as the full length keycode name causes keymaps to look confusing for ISO boards. 
The aliases are still unique and easy to understand in a keymap, while being short enough to be the same length as most regular keycodes.
> Add NUHS/NUBS alias for Non-US-Backslash/Non-US-Hash

- app/src/display/status_screen.c
- app/src/display/widgets/battery_status.c
- app/src/display/widgets/layer_status.c
- app/src/display/widgets/output_status.c
- app/src/display/widgets/wpm_status.c
This fixes and improves a few things. I think a couple of these are subjective.
- Fix right aligned widgets (battery and WPM) by realigning every time the text is updated (maybe `lv_realign` could be used? Didn't work when I tried)
- Add spacing between text elements to make things less cramped
- Add one to the profile index, which is better understood in the non-programming world
> fix(displays): Adjust alignment and spacing

- .github/workflows/build-user-config.yml
The use of `set-output` will be [deprecated by GitHub](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). This change replaces it with [environment variables](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files) to share data between jobs and steps.
> chore(build): replace workflow set-output with environment variables

- app/boards/shields/snap/Kconfig.defconfig
- app/boards/shields/snap/Kconfig.shield
- app/boards/shields/snap/boards/nice_nano.overlay
- app/boards/shields/snap/boards/nice_nano_v2.overlay
- app/boards/shields/snap/snap.conf
- app/boards/shields/snap/snap.dtsi
- app/boards/shields/snap/snap.keymap
- app/boards/shields/snap/snap.zmk.yml
- app/boards/shields/snap/snap_left.overlay
- app/boards/shields/snap/snap_right.overlay
PR to add the [nullbits SNAP](https://nullbits.co/snap/) split keyboard. 
Thoroughly tested on real hardware with nice!nano V1s.
> feat(boards): Add nullbits SNAP shield

- docs/docs/troubleshooting.md
Copying a UF2 into microcontrollers with macOS 13's Finder will trigger an "error code 100093". This change add a workaround for that error.
> feat(docs): Add suggestion to workaround macOS 13 Finder bug

- app/boards/shields/nice_view/Kconfig.defconfig
- app/boards/shields/nice_view/Kconfig.shield
The default bit/pixel is 32, as is the default color depth. This results in LVGL sending all zeros to the nice view, which makes for not happy dev times. 😢
Default it to 1x1 in the nice_view shield so no one else has to go though this. 🎉
> Set bits per pixel and color depth on n!v

- app/boards/shields/splitkb_aurora_sweep/Kconfig.defconfig
- app/boards/shields/splitkb_aurora_sweep/Kconfig.shield
- app/boards/shields/splitkb_aurora_sweep/boards/nice_nano.overlay
- app/boards/shields/splitkb_aurora_sweep/boards/nice_nano_v2.overlay
- app/boards/shields/splitkb_aurora_sweep/splitkb_aurora_sweep.conf
- app/boards/shields/splitkb_aurora_sweep/splitkb_aurora_sweep.dtsi
- app/boards/shields/splitkb_aurora_sweep/splitkb_aurora_sweep.keymap
- app/boards/shields/splitkb_aurora_sweep/splitkb_aurora_sweep.zmk.yml
- app/boards/shields/splitkb_aurora_sweep/splitkb_aurora_sweep_left.overlay
- app/boards/shields/splitkb_aurora_sweep/splitkb_aurora_sweep_right.overlay
> feat(shields): Add splitkb.com Aurora Sweep.

- docs/docs/troubleshooting.md
> Error not exclusive to Apple silicon

- app/boards/shields/splitkb_aurora_corne/Kconfig.defconfig
- app/boards/shields/splitkb_aurora_corne/Kconfig.shield
- app/boards/shields/splitkb_aurora_corne/boards/nice_nano.overlay
- app/boards/shields/splitkb_aurora_corne/boards/nice_nano_v2.overlay
- app/boards/shields/splitkb_aurora_corne/splitkb_aurora_corne.conf
- app/boards/shields/splitkb_aurora_corne/splitkb_aurora_corne.dtsi
- app/boards/shields/splitkb_aurora_corne/splitkb_aurora_corne.keymap
- app/boards/shields/splitkb_aurora_corne/splitkb_aurora_corne.zmk.yml
- app/boards/shields/splitkb_aurora_corne/splitkb_aurora_corne_left.overlay
- app/boards/shields/splitkb_aurora_corne/splitkb_aurora_corne_right.overlay
> feat(shields): Add splitkb.com Aurora Corne.

- app/include/zmk/hid.h
This PR fix isse #1236.
Here qmk/qmk_firmware#312 is discussion about the same issue in QMK.
> HKRO HID_LOGICAL_MAX should be 16bit

- docs/docs/config/backlight.md
The documentation has a broken link. This change updates the link to a relevant page.
> Update link to Zephyr led docs

- app/boards/seeeduino_xiao_ble.overlay
* Use proper resistor value for the `output-ohms` property.
Found this bug in my own testing, and the fix came from `sctanf` [on Discord](https://discord.com/channels/719497620560543766/719909884769992755/1042977575418474586). Reviewing the schematic confirms that's the proper fix.
> fix(boards): Fix XIAO BLE voltage divider config.

- app/src/usb.c
See https://manpages.debian.org/testing/linux-manual-4.9/usb_clear_halt.9 for information on halted USB endpoints.
USB_DC_CLEAR_HALT tends to appear occasionally (maybe every day or so) when connected via my USB hub.
Before fix:
```
[24:50:12.712,371] <dbg> zmk: zmk_usb_get_conn_state: state: 9
[24:50:12.712,371] <dbg> zmk: get_selected_endpoint: Only BLE is ready.
```
> fix(usb): add USB_DC_CLEAR_HALT to supported states

- docs/docs/behaviors/caps-word.md
Update the example for the `mods` property for `&caps_word` per the devicetree spec
> values may be represented as arithmetic, bitwise, or logical expressions within parenthesis.
This is also in line with the usage in the mod-morph documentation as well.
> fix(docs): Correct syntax in capsword mods

- app/src/display/widgets/Kconfig
- app/src/display/widgets/battery_status.c
- docs/docs/config/displays.md
Add a new Kconfig `CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE` for battery status widget. When set, show battery level in percentage text instead of using battery icons.
Unfortunately it looks to me there can be issues with widgets overlapping while charging with nice!view resolution and font sizes. This is an emulation, haven't tested on the actual shield yet:
> feat(display): Add config to show battery level in percentage

- app/boards/arm/bdn9/bdn9_rev2.conf
This took me some time to figure out. if this was in the conf file, it would be much easier to figure out.
proof of working, https://github.com/pvinis/zmk-config-bdn9, and I am using it.
> add encoder comments for bdn9_rev2

- docs/docs/behaviors/bluetooth.md
This is a very simple PR correcting a minor grammatical point in the documentation.
> change to correct number (singular) of the verb 'negotiate'

- app/boards/arm/corneish_zen/corneish_zen.conf
- docs/src/templates/setup.ps1.mustache
- docs/src/templates/setup.sh.mustache
- Add the `.conf` file from the [official config repo](https://github.com/LOWPROKB/zmk-config-zen-2/blob/main/config/corneish_zen.conf) so that the ZMK setup script can copy it to the user config folder and the produced repo can match the official config repo
- Make setup scripts also look for `keyboard_dir.{keymap,conf}` files, so that for revisioned board/shields like `corneish_zen_v2` we can retrieve `corneish_zen.keymap` and `corneish_zen.conf` files if the versioned filenames don't exist
> fix(setup): Fix issues for using Corne-ish Zen with the setup scripts

- docs/src/templates/setup.ps1.mustache
This is a hotfix for a typo in b8fb218a where I forgot to change a variable name.
> fix(setup): Fix conf download path in PS script

- app/src/display/Kconfig
Default to blanking displays on idle like before https://github.com/zmkfirmware/zmk/commit/4a3e783f3212e584e86494db2af8e30f362ecace#diff-1b9b4413fe6b7fbc88f0437fdd6b38c3717f2dede8faa249a16bbd1ae04cb4cb for OLED displays. See [user question on Discord](https://discord.com/channels/719497620560543766/1053852659842547762) where this came up.
Also there is a tiny tab-to-spaces consistency fix in the same file.
Let me know if there is a better way to do this. One other way would be to add it to all the shield Kconfigs that use OLEDs (but not sure if that would interfere with `nice_view` being able to disable it). Another way might be to default to `y` as before but disable it in `corneish_zen_*_defconfig` (rather than `Kconfig.defconfig` -- I don't know why that wasn't initially preferred and …
> fix(display): Re-default to blank on idle for OLEDs

- docs/docs/development/new-shield.md
**Documentation update**: added property to disable status of encoder in dtsi for a new shield. Per my experience of creating a new shield, encoders wouldn't work unless disabled in dtsi and then enabled through config.
> fix(docs): added property to disable status of encoder in dtsi for a new shield.

- app/Kconfig
- app/dts/bindings/behaviors/zmk,behavior-macro.yaml
- app/src/behaviors/behavior_macro.c
- app/tests/macros/timing-override/keycode_events.snapshot
- docs/docs/config/behaviors.md
Added `CONFIG_ZMK_MACRO_DEFAULT_WAIT_MS` and `CONFIG_ZMK_MACRO_DEFAULT_TAP_MS` to set global defaults for the wait-ms and tap-ms properties of macros.
Also reduced the default timings for macros, since it's been reported many times that 100 ms is too slow.
> feat: Add global macro timing configs

- app/dts/bindings/behaviors/zmk,behavior-sticky-key.yaml
While experimenting with custom behaviors based on `zmk,behavior-sticky-key` I noticed that `release-after-ms` is required, and its absence will cause the build to fail.
> fix(behaviors): Mark sticky key release-after-ms required

- docs/docs/user-setup.md
I added a few improvements to the end of user setup cautioning against common issues that people run into when they are first testing their keyboard. These are related to: (a) encouraging testing over USB before BT, (b) explaining peripherals shouldn't be tested before central for split keyboards, (c) linking to troubleshooting for pairing two halves in case of issues, (d) emphasizing BT profiles' importance a little more.
> feat(docs): Add testing related remarks to user setup page

- app/boards/shields/splitkb_aurora_lily58/Kconfig.defconfig
- app/boards/shields/splitkb_aurora_lily58/Kconfig.shield
- app/boards/shields/splitkb_aurora_lily58/boards/nice_nano.overlay
- app/boards/shields/splitkb_aurora_lily58/boards/nice_nano_v2.overlay
- app/boards/shields/splitkb_aurora_lily58/splitkb_aurora_lily58.conf
- app/boards/shields/splitkb_aurora_lily58/splitkb_aurora_lily58.dtsi
- app/boards/shields/splitkb_aurora_lily58/splitkb_aurora_lily58.keymap
- app/boards/shields/splitkb_aurora_lily58/splitkb_aurora_lily58.zmk.yml
- app/boards/shields/splitkb_aurora_lily58/splitkb_aurora_lily58_left.overlay
- app/boards/shields/splitkb_aurora_lily58/splitkb_aurora_lily58_right.overlay
> feat(shields): Add splitkb.com Aurora Lily58.

- app/drivers/gpio/gpio_max7318.c
Fix the potentially buggy implementation in I2C read/write routines in the MAX7318 driver. It used the same style of read/write as #1301, which was identified as buggy.
While nobody has yet raised an issue about it, this PR changes the register read/write functions to use the same (correct) style as the fix in #1301.
> fix(driver): Fix potentially buggy read/write routines for max7318 driver

- app/west.yml
West has supported a 'name-blocklist' replacement for 'name-blacklist' since v0.9.
> chore(build): update west.yml syntax

- docs/docs/troubleshooting.md
Add a note to indicate that the Ventura uf2 bug is fixed in version 13.1
> feat(docs): additional note on bug fixed in macOS v13.1

- app/boards/shields/reviung41/reviung41.keymap
- Asterisk in layer 1 was mapped to 8
- Underscore in layer 1 was mapped to minus
- Right GUI in layer 0 was mapped to right Alt
- Space in layer 1 was mapped to Return
- Plus was mapped with KP_PLUS
> fix(shields): Fix keycodes that deffer from the default keymap

- app/boards/shields/eek/eek.keymap
Noticed the third row of the symbol layer is missing an empty binding, leading to the last layer having 35 total rather than 36.
> fix(keymap): Fix missing binding in eek keymap

- app/src/rgb_underglow.c
Most SoC such as nRF52 do not support double-precision natively. Calculations are faster with single-precision, particularly with FPU.
> feat(underglow): use float for HSB to RGB calculation

- app/dts/bindings/behaviors/zmk,behavior-hold-tap.yaml
- app/src/behaviors/behavior_hold_tap.c
- app/tests/hold-tap/balanced/7-positional/on-release-no-trigger/events.patterns
- app/tests/hold-tap/balanced/7-positional/on-release-no-trigger/keycode_events.snapshot
- app/tests/hold-tap/balanced/7-positional/on-release-no-trigger/native_posix_64.keymap
- app/tests/hold-tap/balanced/7-positional/on-release-trigger/events.patterns
- app/tests/hold-tap/balanced/7-positional/on-release-trigger/keycode_events.snapshot
- app/tests/hold-tap/balanced/7-positional/on-release-trigger/native_posix_64.keymap
- app/tests/hold-tap/hold-preferred/7-positional/on-release-no-trigger/events.patterns
- app/tests/hold-tap/hold-preferred/7-positional/on-release-no-trigger/keycode_events.snapshot
- app/tests/hold-tap/hold-preferred/7-positional/on-release-no-trigger/native_posix_64.keymap
- app/tests/hold-tap/hold-preferred/7-positional/on-release-trigger/events.patterns
- app/tests/hold-tap/hold-preferred/7-positional/on-release-trigger/keycode_events.snapshot
- app/tests/hold-tap/hold-preferred/7-positional/on-release-trigger/native_posix_64.keymap
- app/tests/hold-tap/tap-preferred/7-positional/on-release-no-trigger/events.patterns
- app/tests/hold-tap/tap-preferred/7-positional/on-release-no-trigger/keycode_events.snapshot
- app/tests/hold-tap/tap-preferred/7-positional/on-release-no-trigger/native_posix_64.keymap
- app/tests/hold-tap/tap-preferred/7-positional/on-release-trigger/events.patterns
- app/tests/hold-tap/tap-preferred/7-positional/on-release-trigger/keycode_events.snapshot
- app/tests/hold-tap/tap-preferred/7-positional/on-release-trigger/native_posix_64.keymap
- docs/docs/behaviors/hold-tap.md
This fixes https://github.com/zmkfirmware/zmk/issues/1363 by adding a `hold-trigger-on-release` option to positional hold-taps. 
When `hold-trigger-on-release` is set to `true`, it delays the evaluation of `hold-trigger-key-position` until the next key's *release*. This is in contrast to the current behavior, which evaluates `hold-trigger-key-positions` upon the next key *press*. The current behavior is not always ideal, for example for homerow mods, because it prevents combining multiple modifiers on the same hand. 
The new `hold-trigger-on-release` configuration allows combining multiple modifiers when held, while still forcing a tap-decision when the next key is tapped.
Note: Due to the delay of the position-check until key *release*, the property has no effect when using the …
> On-release option for positional-hold-taps

- app/run-test.sh
Running tests from within Docker on Windows results in failed tests due to mismatched line endings:
```lang=bash
Running tests/backlight/basic:
--- tests/backlight/basic/keycode_events.snapshot       2023-03-07 13:24:03.103769000 +0000
+++ build/tests/backlight/basic/keycode_events.log      2023-03-07 13:45:21.258707000 +0000
@@ -1,9 +1,9 @@
-Update backlight brightness: 40%
-Update backlight brightness: 60%
-Update backlight brightness: 80%
-Update backlight brightness: 60%
-Update backlight brightness: 40%
-Update backlight brightness: 0%
-Update backlight brightness: 0%
-Update backlight brightness: 40%
-Update backlight brightness: 40%
+Update backlight brightness: 40%
+Update backlight brightness: 60%
+Update backlight brightness: 80%
+Update backlight brightness: 60%
+Update …
```
> fix(tests): Fix line endings causing tests to fail in Docker on Windows

- app/boards/arm/ferris/ferris_rev02.dts
* Ferris board's CDC ACM node was accidentally nested under the wrong node, causing USB logging builds to fail with cryptic error.
> fix(boards): Move the CDC ACM node under the USBD.

- app/boards/shields/nice_view_adapter/boards/bluemicro840_v1.overlay
- app/boards/shields/nice_view_adapter/boards/mikoto_520.overlay
- app/boards/shields/nice_view_adapter/boards/nice_nano.overlay
- app/boards/shields/nice_view_adapter/boards/nrfmicro_11.overlay
- app/boards/shields/nice_view_adapter/boards/nrfmicro_11_flipped.overlay
- app/boards/shields/nice_view_adapter/boards/nrfmicro_13.overlay
- app/boards/shields/nice_view_adapter/boards/puchi_ble_v1.overlay
`pinctrl-0` setting missing `<>`.
Happened to copy paste from one of these when setting up my test branch. 💥  Fluke discovery.
> Fixup nice!view adapters

- app/boards/shields/nice_view_adapter/boards/bluemicro840_v1.overlay
- app/boards/shields/nice_view_adapter/boards/mikoto_520.overlay
- app/boards/shields/nice_view_adapter/boards/nice_nano.overlay
- app/boards/shields/nice_view_adapter/boards/nice_nano_v2.overlay
- app/boards/shields/nice_view_adapter/boards/nrfmicro_11.overlay
- app/boards/shields/nice_view_adapter/boards/nrfmicro_11_flipped.overlay
- app/boards/shields/nice_view_adapter/boards/nrfmicro_13.overlay
- app/boards/shields/nice_view_adapter/boards/puchi_ble_v1.overlay
Currently building with `nice_view_adapter` shields isn't working if deep sleep is enabled, e.g. the following fails to build: 
```sh
west build -p -d build/corne_left_nv -b nice_nano -- -DSHIELD="corne_left nice_view_adapter nice_view" -DCONFIG_ZMK_SLEEP=y
```
This seems to be because `spi0_sleep` pinctrl nodes aren't defined and adding those seems to fix the issue. Corne-ish Zen definitions [defines and uses them ](https://github.com/zmkfirmware/zmk/blob/main/app/boards/arm/corneish_zen/corneish_zen_v2_left.dts#L65)in a similar way.
> fix(shields): Fix nice!view for deep sleep

- app/boards/shields/zmk_uno/zmk_uno.overlay
Fixes some warning messages when building
> fix: Remove deprecated labels from zmk_uno

- app/src/display/status_screen.c
This commit fixes the normal font styling in stock status screen so that the selected font size is used. It has resolved the widget sizing issues in my testing with [the native posix setup](https://github.com/caksoylar/zmk-posix-testbed/tree/nice-view).
> fix(display): Do not override font size in status screen

- app/include/zmk/matrix_transform.h
- app/src/kscan.c
- app/src/matrix_transform.c
Before this change, if a matrix position was not present in the transform, various incorrect behaviors would happen:
1) In some cases out-of-bounds accesses:
Note that the size of the`transform[]` array does not necessarily match the size of the matrix. So for example if key position (ZMK_MATRIX_COLS-1, ZMK_MATRIX_ROWS-1) is not present in the transform, but ends up being pressed, then the array will be accessed beyond its size, and any data could be returned.
2) In other cases the 0th position in the keymap will be used because the `transform[]` array is initialized to all zeros.
> fix keypresses that are not in the transform

- app/boards/arm/corneish_zen/custom_status_screen.c
The Corne-ish Zen logo on the peripheral was slightly misaligned, which I am guessing causes the black bar at the bottom to appear. Moving it slightly so it doesn't go off-screen fixes this issue, see pictures below:
Before:
After:
> fix(boards): Fix Corne-ish Zen logo alignment

- docs/docs/behaviors/sticky-key.md
Clarify the potential need of adding the `ignore-modifiers;` setting for new sticky key behaviors when combining multiple modifiers into a single key.
> fix(docs): ignore-modifiers clarification

- docs/docs/development/boards-shields-keymaps.md
Current: A `keymap/keymap.overlay` file that includes the default keymap for that keyboard. Users will be able to override this keymap in their user configs. 
Fix:
A `${board_name}.keymap` file that includes the default keymap for that keyboard. Users will be able to override this keymap in their user configs.
> fix doc typo for development/boards-shields-keymaps

- app/boards/arm/nice60/nice60-pinctrl.dtsi
- app/boards/arm/nice60/nice60.dts
* Move to SPI3 for underglow peripheral, needed after the
move to pinctrl.
> fix(boards): Move nice!60 to SPI3 for underglow

- docs/docs/behaviors/hold-tap.md
* `TAPPING_FORCE_HOLD` was replaced with an equivalent QUICK_TAP_TERM.
* `IGNORE_MOD_TAP_INTERRUPT` will be a default setting.
> fix(docs): Update references to QMK settings

- app/Kconfig
* Reports of constant/frequent disconnects, with HCI err 0x28, "instant passed", seem linked to newer LLCP that became default in Zephyr 3.2, so revert to the Legacy LLCP for now until a proper fix for new LLCP can be found.
This needs a decent amount of testing, since it switches a core BT building block that hasn't been as well tested on the Zephyr 3.2 work.
> fix(bluetooth): Revert to Legacy LLCP

- docs/src/components/interconnect-tabs.tsx
Added a `key` property to interconnect tabs list items to fix a React warning.
> fix(docs): Add key to interconnect tabs

- app/boards/arm/bluemicro840/bluemicro840_v1.dts
- app/boards/arm/nrfmicro/nrfmicro_11.dts
- app/boards/arm/nrfmicro/nrfmicro_11_flipped.dts
- app/boards/arm/nrfmicro/nrfmicro_13.dts
- app/boards/arm/nrfmicro/nrfmicro_13_52833.dts
https://github.com/petejohanson/zmk/commit/b74830bec6dab11c4cbf59b16eecb9a62b5ff429 (the commit moving boards to pinctrl) used the `nrf-twim` driver for all `nrfmicro` revisions and the `bluemicro840`.
That driver does not seem to work with ZMK OLED screens for some reason. Both the issue and the fix were observed and tested with `nrfmicro_13_52833` and `nrfmicro_13` with various shields.
Note: the Corne-ish Zen V1 uses the same `nrf-twim` driver for its fuel gauge, that seems to work fine (tested on my Zen). The issue only occurs with the screens.
> fix(boards): unify board I2C configuration, use TWI driver

- docs/docs/features/debouncing.md
Edits:
* `asym_eager_defer_pk` is already implemented
* Update link to QMK's documentation
> fix(docs): Update QMK debounce references

- .vscode/extensions.json
- .vscode/settings.json
Added settings to format various file types on save in VS Code.
Added some recommended VS Code extensions:
- Prettier for formatting various file types
- Python for formatting Python files
- C/C++ for formatting C files
- Devicetree for syntax highlighting
- CMake for syntax highlighting
> refactor: Add format on save for VS Code

- app/src/display/Kconfig
- app/src/display/main.c
- docs/docs/config/displays.md
This PR sets `CONFIG_LV_USE_THEME_MONO` by default when `ZMK_DISPLAY` is enabled, so that small font selection used in the built-in status screen widgets is no longer ineffective.
It also adds a new Kconfig `ZMK_DISPLAY_INVERT` to invert the colors used in the display from black-on-white to white-on-black, by setting the appropriate value in mono theme initialization.
LVGL mono theme was getting selected by `ZMK_DISPLAY` but not actually used outside of the `corneish_zen` configuration. This change sets it by default if OLEDs or ls0xx memory displays like nice!view are used. This change could use some testing to make sure it doesn't break on OLEDs, nice!views, Adafruit memory displays etc. (Unfortunately I don't have any at the moment, tested on native_posix+SDL setup.)
Given that the …
> feat(display): Set mono theme and add invert config

- app/src/ble.c
* Check the actual connection status before considering a discovered connection as connected.
> fix(bluetooth): Improved checking for conn status.

- app/drivers/kscan/CMakeLists.txt
- app/drivers/kscan/kscan_gpio.c
- app/drivers/kscan/kscan_gpio.h
- app/drivers/kscan/kscan_gpio_direct.c
- app/drivers/kscan/kscan_gpio_matrix.c
This is an alternative solution to #1567 which does not require any dynamic memory.
Changed the GPIO matrix and direct GPIO key scan drivers to do a single read per port instead of one read per pin. This is much more efficient for some types of GPIO drivers, such as I2C GPIO expanders.
To accomplish this with minimal overhead, we now sort input pins by port at driver init. if we iterate through the pins in the sorted order, all pins on the same port are consecutive, so we only need to read each port once the first time we see it.
> refactor(kscan): batch GPIO reads by port

- docs/docs/behaviors/macros.md
Add a shost note for a common use case that is easier solved by modifier functions than macros. Unfortunately the modifier functions section isn't very discoverable since it only shows up when you click on [the modifiers section](https://zmk.dev/docs/codes/modifiers) and not on the full codes page.
> feat(docs): Add note on modifier functions to macros

- docs/docs/behaviors/hold-tap.md
Add a subsection under advanced usage that details use cases involving different behavior types, especially relevant for behaviors that take zero or two parameters. The parameter issue is a frequent question on the Discord and this would also help to make more explicit that hold-tap can work with (pretty much) any behavior.
> feat(docs): Add behavior types section for hold-tap

- docs/docs/features/bluetooth.md
- docs/docs/troubleshooting.md
Move BT-related items from under troubleshooting page to under the troubleshooting section under new BT feature page, then link to that from the original page.
In addition:
- note the known issue with Windows sometimes not receiving keystrokes and provide a workaround[^1]
- note that TX power config also improves split keyboard inter-half connectivity
[^1]: Recently (after the Zephyr 3.2 upgrade) this issue popped up, where some Windows devices can be properly connected but not receive key strokes from the keyboard. A simple un-pair/re-pair doesn't seem to solve it and other actions detailed here is required. 
I have seen this issue reported a few times and I experienced it myself once, and they were solved with these suggestions.
I think investigating the root cause would be good but …
> docs: Move BT troubleshooting items and note known issue for Windows

- docs/docs/features/bluetooth.md
Missed updating a link target while moving BT troubleshooting items in #1818.
> fix(docs): Fix broken link in BT troubleshooting

- app/Kconfig
- app/src/ble.c
- docs/docs/config/bluetooth.md
* Capture the last 6 entered digits, and then require pressing
Enter/Return to submit the entered digits. This matches the
messaging shown on hosts regarding how to complete pairing.
* Fix the wording on the Kconfig menu item to accurately describe
the feature.
Tested on Linux w/ GNOME and on Android, both properly show the expected dialog upon pairing, and pairing only succeeds when a valid value is typed in on the keyboard, followed by pressing Enter/Return.
> fix(bluetooth): Passkey pairing improvements.

- app/boards/arm/bluemicro840/bluemicro840_v1-pinctrl.dtsi
* Use the proper pin assignmets after the move to pinctrl for the
Zephyr 3.2 migration.
> fix(boards): Proper i2c pinctrl for BlueMicro840

- app/include/zmk/ble.h
- app/src/ble.c
- app/src/split/bluetooth/Kconfig
- app/src/split/bluetooth/central.c
This addresses #314 and #609.
This might also affect #281 and #718.
> feat(split): allow central to connect to multiple peripherals

- docs/docs/codes/modifiers.mdx
An an explicit documentation example of combining just modifiers.
> feat(docs): Add an example for combining just modifiers

- docs/src/data/hid.js
I found a typo. 
There is no Japanese word "カソマ". "カンマ" (or "コンマ") is correct. 
"ソ" and "ン" are different characters :)
> docs: Correction for Japanese charactor

- app/Kconfig
`BT_TINYCRYPT_ECC` is required for `BT_SMP_SC_PAIR_ONLY` to work on setups that use BT HCI like the nRF5340.
> fix: Enable BT_TINYCRYPT_ECC when using HCI

- app/boards/nrf5340dk_nrf5340_cpuapp.overlay
Increased the I2C buffer size again, since it needs to be at least 641 to support 128x64 displays.
> fix(boards): Bump nRF5340 DK I2C buffer size

- app/CMakeLists.txt
- app/Kconfig
- app/boards/shields/zmk_uno/boards/nrf52840dk_nrf52840.overlay
- app/boards/shields/zmk_uno/zmk_uno.overlay
- app/drivers/sensor/ec11/Kconfig
- app/drivers/sensor/ec11/ec11.c
- app/drivers/sensor/ec11/ec11.h
- app/drivers/zephyr/dts/bindings/sensor/alps,ec11.yaml
- app/dts/bindings/zmk,keymap-sensors.yaml
- app/include/drivers/behavior.h
- app/include/zmk/events/sensor_event.h
- app/include/zmk/sensors.h
- app/include/zmk/virtual_key_position.h
- app/src/behaviors/behavior_sensor_rotate.c
- app/src/behaviors/behavior_sensor_rotate_common.c
- app/src/behaviors/behavior_sensor_rotate_common.h
- app/src/behaviors/behavior_sensor_rotate_var.c
- app/src/keymap.c
- app/src/sensors.c
- docs/blog/2023-06-18-encoder-refactors.md
Some major refactors to sensors:
* Refactor ec11 sensor driver to align w/ Zephyr degree channel convention, that sensor data for that channel is in degrees of change since the last event.
* Refactor to allow specitying what angle delta triggers a given behavior.
* Move channel data into the sensor event, instead of requiring listeners to probe the sensor themselves upon events.
> Core encoder/sensor refactor

- app/src/split/bluetooth/Kconfig
- app/src/split/bluetooth/central.c
> refactor(split): allow central to define connection parameters

- app/src/behaviors/behavior_sensor_rotate_common.c
* Properly return transparent value when processing mode
for higher disabled layers means the processing is ignored.
> fix(sensors): Sensor rotate behavior fix for layers.

- app/boards/arm/pillbug/pillbug_defconfig
> Update pillbug_defconfig to have pinctrl on

- app/Kconfig
- app/drivers/sensor/battery/Kconfig
Currenly when `ZMK_BATTERY_REPORTING` is turned off, builds with battery sensors fail due to a kernel init priority missing (ex. [1](https://github.com/KLingO-MS/zmk-config-KgO-Sweep/actions/runs/5553387397/jobs/10141875080#step:9:417), [2](https://github.com/tsndr/zmk-config/actions/runs/5536781382/jobs/10104891126#step:9:400)), which I think is due to `SENSOR` Kconfig not getting selected.
Ideally the sensors wouldn't be enabled at all if battery level reporting is disabled but having them in the DT automatically enables them. This change disables them (in a bit of a roundabout way) through disabling `ZMK_BATTERY`: https://github.com/zmkfirmware/zmk/blob/bbb27ac02769c7bf5f20b76605f2b4e0f811e6e0/app/drivers/sensor/CMakeLists.txt#L4
Another option to directly disable the symbols would be …
> fix: Disable battery sensors if reporting is off

- app/boards/shields/settings_reset/settings_reset.keymap
- app/boards/shields/settings_reset/settings_reset.overlay
- app/src/ble.c
- app/src/split/bluetooth/central.c
- app/src/split/bluetooth/peripheral.c
* When the clear bonds Kconfig is set, also clear peripheral
address slots addresses from settings as well.
fix(shields): Make settings_reset more flexible.
* Don't reference `pro_micro` nexus node in settings_reset
so it can be used with other controllers.
* Use mock kscan node instead.
fix(bluetooth): Split improvements
* Proper usage of bt_uuid_cmp.
* Central's don't start scanning for peripherals if
`ZMK_BLE_CLEAR_BONDS_ON_START` is enabled.
* Split peripherals don't advertize if
`ZMK_BLE_CLEAR_BONDS_ON_START` is enabled.
fix(bluetooth): Corrected use of `bt_addr_le_cmp`
* Properly compare to zero when comparing LE addresses.
> Various settings reset improvements.

- app/boards/shields/splitkb_aurora_sofle/Kconfig.defconfig
- app/boards/shields/splitkb_aurora_sofle/Kconfig.shield
- app/boards/shields/splitkb_aurora_sofle/boards/nice_nano.overlay
- app/boards/shields/splitkb_aurora_sofle/boards/nice_nano_v2.overlay
- app/boards/shields/splitkb_aurora_sofle/splitkb_aurora_sofle.conf
- app/boards/shields/splitkb_aurora_sofle/splitkb_aurora_sofle.dtsi
- app/boards/shields/splitkb_aurora_sofle/splitkb_aurora_sofle.keymap
- app/boards/shields/splitkb_aurora_sofle/splitkb_aurora_sofle.zmk.yml
- app/boards/shields/splitkb_aurora_sofle/splitkb_aurora_sofle_left.overlay
- app/boards/shields/splitkb_aurora_sofle/splitkb_aurora_sofle_right.overlay
* Add new shield for splitkb.com Aurora Sofle, supporting keys, encoder(s), displays, and RGB.
> feat(shields): Add splitkb.com Aurora Sofle

- app/CMakeLists.txt
- app/Kconfig
- app/include/zmk/workqueue.h
- app/src/battery.c
- app/src/rgb_underglow.c
- app/src/workqueue.c
Blocking operations on the high priority system workqueue may result in deadlocks, particularly when Bluetooth is in use.
> refactor: use low priority workqueue for underglow and battery reporting

- app/drivers/sensor/battery/battery_nrf_vddh.c
- app/drivers/sensor/battery/battery_voltage_divider.c
With ADC pin, maximum 3.6V input needs gain 1/6 to be less than the 0.6V reference.
With VDDHDIV5, maximum 6V input corresponds to 1.2V so gain 1/2 will be less than the 0.6V reference and be slightly more precise.
> fix(battery): change nRF52 ADC gain

- docs/docs/features/underglow.md
Quite a few people have struggled with setting the correct `chain-length` for their `led_strip`. For some, this is their first time needing to change a pre-defined devicetree property, and so they aren't familiar with the technique. I commonly see folks adding a duplicate of the entire `*.overlay` file with only the `chain-length` value changed. Having clear documentation for this specific application of the property override technique could help forestall these problems, and give those of us helping out in Discord something to easily reference.
> fix(docs): detail overriding the `led_strip` `chain-length` property

- docs/docs/config/kscan.md
Fixes what is probably a copy paste mistake of including `diode-direction` property in direct scan nodes.
> fix(docs): Remove diode-direction from direct GPIO driver

- docs/docs/config/kscan.md
I noticed that the GPIO flags aren't really explained anywhere and they are frequently missed by people when they e.g. swap diode directions. This adds prescriptive paragraphs for matrix and direct pin kscans. It is not actually explaining what the flags do, but this doesn't seem to be the right place for it and in practice it should help.
~~Perhaps we should add a link to Zephyr docs for the explanations of the flags, I'll see if I can find one.~~ Added a link.
Also includes a fix for the examples, where `rows/cols` are incorrectly implied to be supported by the kscan nodes.
> docs: Document necessary flags for kscan GPIOs

- docs/docs/behaviors/macros.md
Two simple changes: update the wait/tap-ms default values in the macros behavior page which were missed, and add a remark on the limit of number of bindings you can pass (which came up from user questions before, and might come up until #1893 is merged). I tested the bindings limit and saw that it succeeded at 256 items and failed at 257.
> docs: Correct default macro timings, note DT limits

- docs/docs/behaviors/backlight.md
- docs/docs/behaviors/bluetooth.md
- docs/docs/behaviors/outputs.md
- docs/docs/behaviors/power.md
- docs/docs/behaviors/underglow.md
Document which behaviors lead to certain settings being persisted in flash memory. Also remark that settings save happens only after the debounce period.
(Random note: looking at the code, I don't think `&rgb_ug RGB_COLOR_HSB(...)` persists the setting, unlike the other commands.)
> feat(docs): Document persisted settings and debouncing

- app/src/split/bluetooth/central.c
In the event that the peripheral MAC address does not match, this allows scanning to continue.
> fix(split): reserve peripheral slot before stopping scanning

- app/boards/shields/kyria/kyria.keymap
- app/boards/shields/kyria/kyria_rev2.keymap
- app/boards/shields/kyria/kyria_rev3.keymap
Bluetooth bindings are useful for handling pairings with hosts. This change adds the header and a few default commands as template for new users to work with.
> feat(shields): Add Bluetooth bindings to kyria keymaps

- app/boards/shields/splitkb_aurora_helix/Kconfig.defconfig
- app/boards/shields/splitkb_aurora_helix/Kconfig.shield
- app/boards/shields/splitkb_aurora_helix/boards/nice_nano.overlay
- app/boards/shields/splitkb_aurora_helix/boards/nice_nano_v2.overlay
- app/boards/shields/splitkb_aurora_helix/splitkb_aurora_helix.conf
- app/boards/shields/splitkb_aurora_helix/splitkb_aurora_helix.dtsi
- app/boards/shields/splitkb_aurora_helix/splitkb_aurora_helix.keymap
- app/boards/shields/splitkb_aurora_helix/splitkb_aurora_helix.zmk.yml
- app/boards/shields/splitkb_aurora_helix/splitkb_aurora_helix_left.overlay
- app/boards/shields/splitkb_aurora_helix/splitkb_aurora_helix_right.overlay
* Add new shield for splitkb.com Aurora Helix, supporting keys, encoder(s), displays, and RGB.
> feat(shields): Add splitkb.com Aurora Helix

- app/boards/seeeduino_xiao_ble.overlay
The GD25Q16 flash connected via QSPI seems to be causing issues with excessive battery use and inability to sleep. Since ZMK doesn't use it, we can disable it as an easy fix. Credit goes to @rich-westarete for figuring out the issue in #1901.
I have been testing this setting in the last few days. Before the change my daily battery use on a split central varied between 3%-12% (with a 350 mAh battery). Deep sleep would not work properly, where about half the times I left it idle it went into sleep and the other half it was awake when I came back. After this change deep sleep is consistent and the battery usage has gone down to 1-2% per day.
> fix(boards): Disable QSPI for Xiao BLE

- docs/docs/troubleshooting.md
This adds a small tip to the troubleshooting documentation. I made this embarrassing mistake today, but thought a more complicated `&lt` was to blame, which lead to a bit of head scratching.
> doc: additional tip detailing missing `&kp`

- app/boards/shields/leeloo_micro/leeloo_micro.dtsi
Update Leeloo-Micro's .dtsi file to set encoder status to disabled; and, adjusted steps to be behave smoother.  
Thank yous to @mstralenya for catching the fix in Leeloo v2, and @petejohanson for approving and merging the change.
> Leeloo-Micro set status disabled for encoders.

- app/module/drivers/gpio/gpio_max7318.c
- app/module/dts/bindings/gpio/maxim,max7318.yaml
The driver got neglected and didn't compile. Now it does (:
Tested to work on real hardware.
EDIT: what's the best way to make a CI test for this so that it keeps being compiled?
> fix(driver): Fix broken compilation for MAX7318 driver

- app/src/hid_listener.c
- app/tests/key-repeat/tap-when-rolling/events.patterns
- app/tests/key-repeat/tap-when-rolling/keycode_events.snapshot
- app/tests/key-repeat/tap-when-rolling/native_posix.keymap
- app/tests/key-repeat/tap-when-rolling/native_posix_64.keymap
- app/tests/modifiers/implicit/kp-rolling-symbols-same-key/events.patterns
- app/tests/modifiers/implicit/kp-rolling-symbols-same-key/keycode_events.snapshot
- app/tests/modifiers/implicit/kp-rolling-symbols-same-key/native_posix_64.keymap
There are a couple of cases where a user may end up rolling two physical keys that happen to map to the same keycode. When this happens, we register a second key press, but this does nothing at the OS level, meaning only one key press will be registered by the computer.
The two cases I'm aware of are:
1. Rolling the key-repeat behavior (#1207)
2. Rolling symbols that map to the same keycode (#1076)
This PR solves both of these issues by simply releasing the keycode before it is pressed again.
I've also added some test suites to cover this behavior, though they rely on the new print out when pre-releasing keys in order to be effective.
This requires further testing, currently I'm running this without issue, but more users testing on different setups is needed. I'm curious if we're going to …
> feat(core): Adding pre-release for keys that were already pressed.

- app/src/combo.c
- app/tests/combo/overlapping-combos-4-different-timeouts/events.patterns
- app/tests/combo/overlapping-combos-4-different-timeouts/keycode_events.snapshot
- app/tests/combo/overlapping-combos-4-different-timeouts/native_posix_64.keymap
> ### This is a follow-up to #1944 . See the issue for more context.
> This PR fixes the bug mentioned in the issue
When a timeout fires, the code will filter the remaining combos. Eliminating the one the just timed out, and reordering the remaining ones.
The code _does_ filter the timed out combos correctly, and it does re-order the remaining ones correctly. But! It didn’t clean up properly the position of the very last candidate.
They all move one spot, so when they move, they override the one that was previously there. But the very last combo doesn’t get overridden by anything.
```
Timestamp = 60ms
Before filtering
Combo expires_at=60ms
Combo expires_at=70ms
Combo expires_at=80ms
Combo expires_at=90ms
After filtering
Combo expires_at=70ms
Combo expires_at=80ms
Combo expires_at=90ms …
```
> Fix bug with overlapping combos timeouts

- app/boards/shields/sofle/Kconfig.defconfig
- app/boards/shields/sofle/boards/nice_nano.overlay
- app/boards/shields/sofle/boards/nice_nano_v2.overlay
- app/boards/shields/sofle/boards/nrfmicro_11.overlay
- app/boards/shields/sofle/boards/nrfmicro_13.overlay
- app/boards/shields/sofle/sofle.conf
- app/boards/shields/sofle/sofle.keymap
- app/boards/shields/sofle/sofle.zmk.yml
Multiple folks on the ZMK Discord server have recently run into difficulties trying to get RGB underglow working on their Sofle, as a result of mainline Sofle not having `&led_strip` defined. This `nice_nano_v2.overlay`—similar to overlays for other boards (differing only in default `chain-length`)—should be sufficient to remove this hurdle for others.
> sofle: add underglow support with `&pinctrl` update

- docs/docs/behaviors/layers.md
Added documentation details for layer-tap.
The mod-tap documentation page has a configuration portion where it shows how to change some values for the behavior ( https://zmk.dev/docs/behaviors/mod-tap#configuration )
I suggest adding the same thing for the layer-tap behavior documentation portion.
Changes have been tested according to : 
https://zmk.dev/docs/development/documentation
>  Documentation update for layer-tap in docs/docs/behaviors/layers.md

- app/boards/shields/nice_view/widgets/status.c
- app/boards/shields/nice_view/widgets/util.h
Fixed an error in a previous commit where a member of the selected endpoint was used without checking if it was the correct transport type. The nice!view status screen displays the active BLE profile regardless of whether BLE is active, so we have to get that data directly from the BLE code instead of from the selected endpoint.
> fix(nice_view): Fix incorrect union access

- docs/docs/codes/_footnotes/globe.mdx
- docs/src/data/footnotes.js
- docs/src/data/hid.js
Adds the footnote for the issues documented with the new apple globe keycode discovered by some users in #1938
> feat(docs): Document globe key specific quirks

- docs/blog/2023-10-05-zmk-sotf-6.md
Fixes a mistake I made in the description of the deprecated `global-quick-tap` flag which was compared to the `require-prior-idle-ms` property.
> fix(blog): Correct incorrect info re: global-quick-tap

- app/boards/shields/zmk_uno/zmk_uno.overlay
Export the `nice_view_spi` node properly from the ZMK Uno overlay to ensure the shield will work when built along with the `nice_view` shield.
Example:
> feat(shields): Add ZMK Uno nice!view support.

- .github/workflows/build-user-config.yml
Added the combined devicetree file to the user config build action. Set it and the Kconfig output to run even on a failed build.
Depending on how far into the build it got before failing, zephyr.dts.pre might exist but not the much more readable zephyr.dts, so it tries to print zephyr.dts first, then zephyr.dts.pre (with its large spans of blank lines collapsed).
> feat: Print Kconfig and DTS for failed builds

- docs/docs/config/battery.md
- docs/docs/config/system.md
Whilst working on other battery reporting stuff i noticed `CONFIG_ZMK_BATTERY_REPORTING` is currently undocumented, A new KConfig heading for battery.md has been added in line with the other sections in the configuration section of the docs, `CONFIG_ZMK_BATTERY_REPORT_INTERVAL` has been moved from system to battery for consistency.
> feat(docs): Document ZMK_BATTERY_REPORTING config

- docs/docs/config/battery.md
- docs/docs/config/displays.md
- docs/docs/config/encoders.md
- docs/docs/config/kscan.md
Some of the driver code directory structure was reorganized recently to match Zephyr better, but the existing links in the documentation hadn't been updated.
I _think_ this is everything, after some manual checking I looked at the PR where the files were moved and used that to look for affected files.
> chore(docs): Fix links to relocated files

- app/boards/arm/bdn9/bdn9_rev2.dts
- app/boards/arm/bt60/bt60.dtsi
- app/boards/arm/ckp/ckp.dtsi
- app/boards/shields/knob_goblin/knob_goblin.overlay
- app/boards/shields/kyria/kyria_common.dtsi
- app/boards/shields/lily58/lily58.dtsi
- app/boards/shields/lotus58/lotus58.dtsi
- app/boards/shields/murphpad/murphpad.keymap
- app/boards/shields/murphpad/murphpad.overlay
- app/boards/shields/nibble/nibble.keymap
- app/boards/shields/nibble/nibble.overlay
- app/boards/shields/reviung5/reviung5.overlay
- app/boards/shields/romac_plus/romac_plus.dtsi
- app/boards/shields/snap/snap.dtsi
- app/boards/shields/snap/snap.keymap
- app/boards/shields/sofle/sofle.dtsi
- app/boards/shields/splitkb_aurora_corne/splitkb_aurora_corne.dtsi
- app/boards/shields/splitkb_aurora_lily58/splitkb_aurora_lily58.dtsi
- app/boards/shields/splitkb_aurora_sweep/splitkb_aurora_sweep.dtsi
- app/boards/shields/tidbit/tidbit.dtsi
- app/boards/shields/tidbit/tidbit.keymap
- app/boards/shields/zodiark/zodiark.dtsi
- docs/docs/config/encoders.md
- docs/docs/development/new-shield.md
* Update new shield guide for new sensor/encoder settings.
* Add DTS section to encoder config docs.
* Update existing in-tree shields/boards to use the new encoder configuration consistently.
> Updated encoder config docs & standardization of existing shields

- app/Kconfig
- app/include/zmk/hid.h
- app/include/zmk/usb_hid.h
- app/src/endpoints.c
- app/src/hid.c
- app/src/usb.c
- app/src/usb_hid.c
This PR adding boot protocol support is based on @rbitanga's https://github.com/zmkfirmware/zmk/pull/1140, with some refactoring and other changes that we think are improvements, and is rebased and presented for review as @joelspadin requested [here](https://github.com/zmkfirmware/zmk/pull/1140#issuecomment-1317924785) (sorry about the huge delay!). The work was largely done by @thefloweringash.
The changes from #1140 are as follows:
* Minimize the api changes for Bluetooth by keeping `zmk_hid_get_keyboard_report()` and returning the .body like before.
* Keeping the logic about "full" vs "body" entirely within the usb code path.
* The endpoint now calls either `zmk_usb_hid_send_keyboard_report()` and   `zmk_usb_hid_send_consumer_report()` instead of `zmk_usb_hid_send_report(...)`.
- These …
> Boot protocol support (based on #1140, with some refactoring)

- .github/workflows/build-user-config.yml
This change adds a new optional property `artifact-name` to `build.yaml`, so that if provided, the base of the output filename will be equal to that for an entry.
While it isn't discoverable because there isn't a way to document it (besides perhaps expanding the comment section in the template yaml), this field would allow users to build the same board+shield combination with different keymaps or different CMake args (like adding Kconfig settings).
Some context: https://discord.com/channels/719497620560543766/719909884769992755/1171174369045774406
[Example build.yaml](https://github.com/caksoylar/zmk-config/blob/test-artifact-name/build.yaml): 
```yaml
---
include:
- board: seeeduino_xiao_ble
shield: rommana_left rgbled_widget
artifact-name: my_rommana_left
- board: seeeduino_xiao_ble …
```
> feat(build): Add support for artifact-name in build.yaml

- app/Kconfig
- app/src/usb_hid.c
* Invert the logic so `get_keyboard_report` is sane when `ZMK_USB_BOOT`
is disabled.
> fix(usb): Build with ZMK_USB_BOOT disabled.

- app/include/dt-bindings/zmk/bt.h
- app/include/zmk/ble.h
- app/src/behaviors/behavior_bt.c
- app/src/ble.c
- docs/docs/behaviors/bluetooth.md
Adds new functionality and a behavior to disconnect an active BLE connection. The motivation for this is that for some devices like phones, the presence of an active BLE connection results in the onscreen keyboard being selected.
This behavior allows the active connection for a given profile to be explicitly disconnected, by calling [`bt_conn_disconnect()`](https://docs.zephyrproject.org/apidoc/latest/group__bt__conn.html#ga14e7c852b0271781594e742ae509c5d3). The connection will be re-established (via `update_advertising()`), when that profile is re-selected.
I believe this behavior is complementary to the proposed automatic disconnection of non-selected devices. Automatic disconnection without a timeout could be frustrating to use when actively switching between devices, as there's a …
> feat(ble): add behavior to disconnect from BLE profile

- .github/workflows/build-user-config.yml
Another try at #2004, this time with more exhaustive testing of following combinations:
- board only/board+shield/board+multiple shields
- no/given `artifact-name` (including spaces in the value)
- empty/non-empty `cmake-args` 
[Input file](https://github.com/caksoylar/zmk-config/blob/2deb21a/build.yaml):
```yaml
include:
- board: corneish_zen_v2_left    # board only
- board: corneish_zen_v1_right   # board only, with name
artifact-name: zen_right
- board: nice_nano_v2            # board+shield
shield: corne_left
- board: nice_nano_v2            # board+shield, with name
shield: corne_left
artifact-name: stock_corne_left
- board: nice_nano               # board+shield, cmake-args
shield: corne_left
cmake-args: -DKEYMAP_FILE=/__w/zmk-config/zmk-config/config/corneish_zen.keymap
- board: …
```
> feat(build): Add support for artifact-name in build.yaml, correctly

- docs/docs/development/usb-logging.md
Currently, this is only documented in the zephyr 3.0 upgrade blog. This explicitly documents it as well as when it doesn't need to be applied (i.e. when a mcu board is already in use)
> docs: Document adding USB logging to a standalone board

- app/src/battery.c
As a further mitigation against spurious wakeups (in addition to #1973) without having to disable the battery service entirely, the battery percentage can only be updated when the board is active i.e. when in use, which infers the computer is also in use
> feat(ble): Only update BAS when active

- app/src/ble.c
* Only upgrade security of new connections if BT_GATT_AUTO_SEC_REQ
is not enabled.
This is something @joelspadin was discussing recently as possibly improving our compatibility with some OSes, so making it easy for folks to test by not automatically setting security on new connections unless needed.
> feat(ble): Make it possible to use BT_GATT_AUTO_SEC_REQ

- app/src/ble.c
* Don't propogate any key press events while in the
middle of passkey entry, avoid funky state on hosts.
* Handle passkey on release, not press, to ensure key *releases*
are not accidentally sent, especially the Enter release
at the very end of passkey entry, which can trigger
cancel in the dialog if the keyboard is connected
via USB to the same host.
I know @joelspadin has a bigger refactor coming for this, but a few minor improvements to this feature in the meantime to make the current passkey support actually usable.
> fix(bt): Passkey entry pairing fixes.

- docs/docs/behaviors/bluetooth.md
Fix the double row for `BT_DISC` entry in Bluetooth behavior page. While touching, clean up the wording a bit on that and `BT_SEL`.
> fix(docs): Fix table for BT_DISC

- app/Kconfig
- app/include/zmk/hid.h
- docs/docs/config/system.md
By default, the maximum NKRO usage is set to maximize compatibility, but some keys don't work. This adds the ability to use those extended keys, at the cost of compatibility (android doesn't like the higher usage range, it seems). The chosen max was largely arbitrary, although it needs to be a multiple of 8 - 1 (otherwise windows will refuse to enumerate it properly, reporting "driver error"), For this reason I made it a configurable bool rather than a variable value. There's also no reason to have it variable across a wide range, a low and a high value seem like a good compromise
This fix addresses #1460 and is linked to #1236
> feat(hid): Add KConfig option for higher NKRO usages

- app/include/zmk/split/bluetooth/peripheral.h
- app/src/split/bluetooth/peripheral.c
There is already a function to see if the peripheral is connected, a matching one for if it's bonded is a useful addition for displays/indicators. `is_bonded` gets reset to false in the advertising function in preparation for runtime peripheral bond clearing (#1757)
Tested on a 360 Pro with some custom indicators stuff and seems to work as expected
> feat(split): Add is_bonded function to peripherals

- .github/workflows/build-user-config.yml
- app/CMakeLists.txt
- app/keymap-module/modules/modules.cmake
- app/keymap-module/zephyr/module.yml
- docs/docs/development/build-flash.md
- docs/docs/development/new-shield.md
* Shift to using an extra Zephyr module to do keymap location
work after all board roots are resolved. This avoids duplicate work
and allows us to load custom boards from Zephyr modules as well as
user config setups.
> refactor: Hook into CMake loading in a better spot.

- docs/docs/config/behaviors.md
This PR updates the behaviors config page to do the following, split into separate commits:
- Add a couple missing links to behavior docs
- Fix `#binding-cells` for sticky keys to `<1>`
- Add missing definition file links for parametrized macro variants
- Add sensor rotation behaviors that were missing
- Note how behaviors forward the parameters they receive to the behaviors they invoke
Mouse key press behavior is not documented here, but similar to key press, it has no options to tweak so IMO it doesn't seem necessary. However move/scroll behaviors will likely need to be documented in the future.
> feat(docs): Update behaviors config page

- app/boards/shields/settings_reset/settings_reset.overlay
This tweak would allow building the `settings_reset` shield with board-only keyboards, since previously the kscan name/label of the reset shield tended to conflict with the kscan of the boards. Happy to tweak the new name if anyone else has suggestions.
Discussion on the Discord: https://discord.com/channels/719497620560543766/719909884769992755/1171173924877373481
> feat(shields): Allow settings_reset to build with board-only keyboards

- .github/workflows/ble-test.yml
- .github/workflows/test.yml
* To address conflicts with identically named artifact uploads, include the
test name in the artifact name.
Bit of a chore after seeing failure in the dependabot PR to bump our `actions/upload-artifact` dep.
> fix(ci): Use unique artifact for test logs

- app/CMakeLists.txt
- app/Kconfig
* Add a new Kconfig symbol to enable the low priority queue, and make the two features that depend on it `select` the symbol to turn it on. This helps ensure no wasted RAM/ROM on devices that don't need it.
This came up while working on more resource constrained devices like SAMD21 and stm32f072.
> refactor(core): Make low priority queue optional.

- docs/blog/2023-12-17-nodefree-config.md
This is the second post in a series of blog posts highlighting the useful projects in the ZMK ecosystem. @urob penned this one introducing the [nodefree-config helpers](https://github.com/urob/zmk-nodefree-config/).
> feat(blog): Add nodefree-config post for spotlight series

- .gitignore
As per title. (Zephyr docs recommend installing Python packages in a virtual environment)
> Add some python things to `.gitignore`

- app/include/zmk/events/battery_state_changed.h
- app/include/zmk/split/bluetooth/central.h
- app/src/display/widgets/battery_status.c
- app/src/events/battery_state_changed.c
- app/src/split/bluetooth/CMakeLists.txt
- app/src/split/bluetooth/Kconfig
- app/src/split/bluetooth/central.c
- app/src/split/bluetooth/central_bas_proxy.c
- docs/docs/config/system.md
* Add ability to fetch and report peripheral battery levels on split centrals.
* Add additional support for adding a new Battery Level service to split centrals that exposes fetched peripheral battery levels to connected hosts.
This is a continuation of the great work from @Katona in #1243 with some important changes:
* Move both central fetching and reporting of peripheral battery levels behind new (documented) Kconfig flags
* After reviewing the Battery [Level Service specification](https://www.bluetooth.com/specifications/specs/battery-service/), it became clear to me there could be an easier structure for this. In particular, that spec lays out the requirements if you're going to have more that one battery level service, how to tag a particular battery level characteristic as the main …
> feat(ble): Support peripheral battery levels.

- app/boards/seeeduino_xiao_ble.overlay
I'm working a XIAO-BLE based keyboard and I noticed high idle and sleep currents, bearing in mind that my board:
- Uses matrix polling;
- has CA95xx gpio expander;
The 500uA current is similar to reported here: https://forum.seeedstudio.com/t/low-power-with-xiao-nrf52840-on-zephyr-rtos/270491/6
Which led me to https://github.com/zmkfirmware/zmk/pull/1927. Even tho the PR seems to address the issue somehow, I find it strange that it does since the nRF driver puts the flash on Deep Power-Down (DPD) [drivers/flash/nrf_qspi_nor.c#L1324](https://github.com/zmkfirmware/zephyr/blob/1ae0eb5ce8adafcec993e6fb8f4eeb6f818a7772/drivers/flash/nrf_qspi_nor.c#L1324), the reason for DPD not properly working I believe to be related to the fact that the ZMK fork of Zephyr use what seems the incorrect …
> Fix high idle/sleep current due to flash and use xiao-ble from upstream Zephyr

- app/src/wpm.c
* Recent refactor accidentally used the wrong signatures for a few WPM function definitions.
> fix: Fix function signatures for WPM.

- app/Kconfig
* Ensure split peripherals have `BT_GATT_AUTO_SEC_REQ` enabled so that
reconnects to centrals are automatically encrypted.
> fix(split): Split peripherals should auto sec req still.

- app/src/battery.c
zmk_battery_start_reporting() may be called from battery_event_listener(), which will result in a bus fault when attempting to read a battery that does not exist such as on a dongle.
> fix(battery): prevent bus fault when battery does not exist

- app/boards/arm/adv360pro/adv360pro.dtsi
* Restore setting loading by preserving old device name for the external power node.
> fix(boards): Fix up EXT_POWER naming for adv360pro;

- docs/docs/config/system.md
The |CONFIG_ZMK_USB_BOOT switch was missing from the documentation.
> Add zmk_usb_boot toggle to documentation

- .github/workflows/build.yml
* Treat build and upload as distinct steps during a build, and don't fail
a PR if only the upload portion fails.
---
This is needed to avoid hitting upload limits on PRs that make significant changes to shields and causes a large set of test build combinations.
> chore(ci): Split build and upload into separate steps

- app/Kconfig
- app/include/zmk/event_manager.h
- app/include/zmk/events/keycode_state_changed.h
- app/include/zmk/events/layer_state_changed.h
- app/include/zmk/events/mouse_button_state_changed.h
- app/src/activity.c
- app/src/battery.c
- app/src/behaviors/behavior_hold_tap.c
- app/src/behaviors/behavior_key_press.c
- app/src/behaviors/behavior_key_repeat.c
- app/src/behaviors/behavior_key_toggle.c
- app/src/behaviors/behavior_mouse_key_press.c
- app/src/behaviors/behavior_sticky_key.c
- app/src/ble.c
- app/src/combo.c
- app/src/endpoints.c
- app/src/event_manager.c
- app/src/keymap.c
- app/src/kscan.c
- app/src/sensors.c
- app/src/split/bluetooth/central.c
- app/src/split/bluetooth/peripheral.c
- app/src/usb.c
- app/src/wpm.c
Ok, this is a semi-major core refactor to address one of the major nits I had with the initial design for the event manager API I added to ZMK, mainly that it depending on dynamic memory allocation for alloc/free of the event structs. As a result, we need to use some large, arbitrary heap pool in ZMK to be sure we have enough allocated for whatever odd combination of events get raised/captured in the system.
This PR moves to stack allocated event structures, and change the expectation that anyone wanting to capture an even should copy it into a locally allocated storage for it's use as needed. See updates to hold-tap, combos, etc that demonstrate this kind of change.
This potentially disrupts any open behavior PRs, so need to consider the *timing* of the merge of this, but want to get …
> Refactor events API to avoid heap/dynamic allocations

- .github/workflows/test.yml
- app/include/zmk/event_manager.h
- app/run-test.sh
* __ASSERT is converted to a do/while loop when asserts are enabled,
which doesn't work with our usage, so revert that addition.
Also adds a commit to enable asserts for our tests to catch this better next time.
> fix(events): Remove our usage of assert.

- .github/workflows/build-user-config.yml
Reverts zmkfirmware/zmk#2136
This causes issues with artifact uploads. Reverting for now.
> Revert "fix(ci): Update one lingering upload-artifacts action."

- app/Kconfig
`zmk_rgb_underglow_effect_swirl()` with 256 LEDs on Nordic nRF52833 takes around 170 ticks (32.768kHz) without FPU and around 32 ticks with FPU.
Fixes #1641
> feat(core): enable FPU if CPU has FPU

- docs/docs/behaviors/mod-morph.md
Small docs change to document the issues caused by having Karabiner running and Modify Events on for a keyboard sending morphed keypresses.
> feat(docs): Document Karabiner interference with Mod-Morphs

- app/boards/shields/crbn/crbn.overlay
- app/boards/shields/kyria/kyria_rev3.dtsi
- app/boards/shields/leeloo/leeloo_common.dtsi
- app/boards/shields/leeloo_micro/leeloo_micro.dtsi
- app/boards/shields/murphpad/murphpad.keymap
- app/boards/shields/nibble/nibble.keymap
- app/boards/shields/snap/snap.keymap
- app/boards/shields/splitkb_aurora_helix/splitkb_aurora_helix.dtsi
- app/boards/shields/splitkb_aurora_sofle/splitkb_aurora_sofle.dtsi
- app/boards/shields/tidbit/tidbit.keymap
- app/boards/shields/tidbit/tidbit_19key.keymap
- app/boards/shields/waterfowl/waterfowl.dtsi
- app/boards/shields/zmk_uno/zmk_uno.overlay
- app/boards/shields/zmk_uno/zmk_uno_split.dtsi
- docs/src/keymap-upgrade/encoder.ts
- docs/src/keymap-upgrade/index.ts
- docs/src/keymap-upgrade/parser.ts
Updated the keymap upgrader to upgrade the encoder `resolution` property to `steps` and `triggers-per-rotation`. 
The `steps` property will be set assuming triggers-per-rotation is 20. To simplify the code, it does not go looking for an existing triggers value since it's unlikely that you would have set `triggers-per-rotation` but not `steps`.
If `steps` is added and `triggers-per-rotation` is not present, a new `&sensors { ... }` block is added with the property set to 20. To simplify the code, it does not go looking for an existing sensors node to insert the property into.
Both added properties include a comment explaining how to fix the value to match your encoder.
Fixed an issue where appending text to the end of the file would highlight the wrong lines.
Also updated the shields that …
> Add encoder resolution fix to keymap upgrader

- app/src/behaviors/behavior_ext_power.c
After Zephyr 3.5 was merged, I got an error compiling with a board that used both rgb_toggle and ext_power behaviors:
`ERROR: /behaviors/rgb_toggle POST_KERNEL 5 < /behaviors/extpower POST_KERNEL 55`
This change fixes the compile error.
> Fix compile issue on zephyr 3.5 with ext_power and rgb_toggle

- docs/docs/config/battery.md
- docs/docs/features/battery.md
> Added documentation for multiple battery monitoring

- app/boards/arm/ferris/ferris_rev02.dts
* Enable missing clock and set up USB pinctrl.
> fix(boards): Tweaks for Ferris rev0.2 for Zephyr.

- app/boards/arm/nrfmicro/nrfmicro_11.dts
- app/boards/arm/nrfmicro/nrfmicro_11_flipped.dts
- app/boards/arm/nrfmicro/nrfmicro_13.dts
- app/boards/arm/nrfmicro/nrfmicro_13_52833.dts
After Apr 6 2023(ae8299edb3d638f1332475b1da0fdf40afa43fe4), the nrfMicro can not driver oled, because of missing a line.
> Fix nrfMicro oled display

- app/boards/arm/planck/planck_rev6.dts
- app/boards/arm/planck/planck_rev6.keymap
- app/boards/arm/planck/planck_rev6.zmk.yml
- app/boards/arm/planck/planck_rev6_defconfig
This adds support for an optional rotary encoder in the leftmost column of the Planck rev6. All positions for the encoder map to the same pins on the board, so this ought to work regardless of which position is chosen.
I have been using this regularly for the last week without any issues. FWIW, my encoder is in the bottom row.
> feat(boards): add encoder support to planck

- app/src/endpoints.c
When building without USB or Bluetooth, the compiler would emit a warning due to ZMK_TRANSPORT_USB or ZMK_TRANSPORT_BLE not being handled.
> refactor: address transport switch enumeration warning

- app/dts/bindings/behaviors/zmk,behavior-hold-tap.yaml
- app/src/behaviors/behavior_hold_tap.c
- app/tests/hold-tap/hold-while-undecided/1-tap/events.patterns
- app/tests/hold-tap/hold-while-undecided/1-tap/keycode_events.snapshot
- app/tests/hold-tap/hold-while-undecided/1-tap/native_posix_64.keymap
- app/tests/hold-tap/hold-while-undecided/2-hold/events.patterns
- app/tests/hold-tap/hold-while-undecided/2-hold/keycode_events.snapshot
- app/tests/hold-tap/hold-while-undecided/2-hold/native_posix_64.keymap
- app/tests/hold-tap/hold-while-undecided/3-linger/events.patterns
- app/tests/hold-tap/hold-while-undecided/3-linger/keycode_events.snapshot
- app/tests/hold-tap/hold-while-undecided/3-linger/native_posix_64.keymap
- app/tests/hold-tap/hold-while-undecided/4-linger-sk/events.patterns
- app/tests/hold-tap/hold-while-undecided/4-linger-sk/keycode_events.snapshot
- app/tests/hold-tap/hold-while-undecided/4-linger-sk/native_posix_64.keymap
- docs/docs/behaviors/hold-tap.mdx
- docs/docs/config/behaviors.md
This PR builds on the changes from #1398 and attempts to implement @okke-formsma 's suggestions. Addresses https://github.com/zmkfirmware/zmk/issues/1393.
If enabled, the hold behavior will immediately be held on hold-tap press, and will release before the tap behavior is sent.
If your tap behavior activates the same modifier as the hold behavior, and you want to avoid a double tap when transitioning from the hold to the tap, you can use `hold-while-undecided-linger`. When enabled, the hold behavior will continue to be held until _after_ the tap behavior is released. For example, if the hold is `&kp LGUI` and the tap is `&sk LGUI`, then with `hold-while-undecided-linger` enabled, the host will see `LGUI` held down continuously until the sticky key is finished, instead of seeing a release …
> feat(behaviors): hold-tap hold while undecided

- docs/docs/config/underglow.md
I'm not sure if these exist somewhere else, but I couldn't find them.
Adding them here because I think it's appropriate.
Feel free to close if I am off base!
> fix(docs): Add Underglow Brightness Min/Max to Docs

- CONTRIBUTING.md
- docs/docs/development/new-shield.mdx
Resolves #2183
Added a warning to the shield section explaining that Kconfig does not ignore whitespaces on function calls and therefore adding whitespaces after the comma will break functionality.
> feat(docs): Add warning to new shield docs how Kconfig treats whitspaces

- app/CMakeLists.txt
- app/Kconfig
- app/boards/shields/settings_reset/settings_reset.conf
- app/include/zmk/settings.h
- app/src/settings/CMakeLists.txt
- app/src/settings/reset_settings_fcb.c
- app/src/settings/reset_settings_file.c
- app/src/settings/reset_settings_none.c
- app/src/settings/reset_settings_nvs.c
- app/src/settings/reset_settings_on_start.c
- docs/docs/config/system.md
- docs/docs/troubleshooting.md
- Added `zmk_settings_erase()`, which directly clears the backend data for settings.
- Changed the `settings_reset` shield to run this function on startup instead of using `CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START`, so it now resets all settings instead of just Bluetooth ones.
- Removed `CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START`, as it is no longer needed.
Future PRs can add additional ways to trigger `zmk_settings_erase()`.
> Make settings_reset builds reset all settings

- app/src/keymap.c
- docs/docs/troubleshooting.md
Little fix to address #1416 to throw an explicit error if a node with `compatible = zmk,keymap` is not set. In testing, the `ZMK_KEYMAP_LAYERS_LEN` error is still present but the explicit error gets presented as well, which should still help users diagnose problems.
Some documentation on the error has also been added to the troubleshooting section of the docs.
> feat(build): Explicit keymap node error

- docs/docs/behaviors/mouse-emulation.md
- docs/docs/config/system.md
- docs/docs/features/bluetooth.md
Added a section under the BT features page that describes when it might be necessary, and how to do it. This will be a more common ask with more mouse functionality getting integrated in the future.
Also took the opportunity to remove the guidance on Windows battery refresh Kconfig. This doesn't seem to be necessary anymore in W10/W11, according to reports.
> feat(docs): Document HID report descriptor refresh

- app/boards/arm/ferris/ferris_rev02.keymap
- app/boards/shields/clog/clog.keymap
- app/boards/shields/hummingbird/hummingbird.keymap
- app/boards/shields/jian/jian.keymap
- app/boards/shields/osprette/osprette.keymap
- app/boards/shields/splitkb_aurora_sweep/splitkb_aurora_sweep.keymap
- app/tests/hold-tap/balanced/6-retro-tap/native_posix_64.keymap
- app/tests/hold-tap/hold-preferred/6-retro-tap/native_posix_64.keymap
- app/tests/tap-dance/behavior_keymap.dtsi
A few overlays scattered across boards, shields and tests appear to have been missed when updating/upgrading these properties.
~~Tagging @ReFil who may or may not be `crbn`'s maintainer: `resolution` was replaced with sane defaults for `steps` and `triggers-per-rotation`, but I am unfamiliar with this shield. If there are specific known values that should go here, please suggest.~~ Handled in #2143.
> refactor: remove/replace deprecated properties

- docs/docs/behaviors/hold-tap.mdx
The hold-while-undecided callout does not properly render in the docs. This fixes it.
> chore(docs): fix hold-tap info callout

- docs/docs/troubleshooting.md
Add a troubleshooting section for `empty_file.c` `lacks #binding-cells` error
> feat(docs): Add troubleshooting section for empty_file error

- app/Kconfig
- app/src/settings/reset_settings_on_start.c
* Add a dedicated settings reset on start init priority and default it to lower priority (high number) than default FLASH_INIT_PRIORITY to be sure flash is initialized before we open the area.
I haven't had a chance to test this on hardware yet, but this likely is the issue with reported settings reset:
```
[00:00:00.309,143] <inf> zmk: Erasing settings flash partition
[00:00:00.309,143] <err> zmk: Failed to open settings flash: -19
[00:00:00.316,070] <inf> fs_nvs: 8 Sectors of 4096 bytes
[00:00:00.316,070] <inf> fs_nvs: alloc wra: 0, fd8
[00:00:00.316,070] <inf> fs_nvs: data wra: 0, 18
```
> fix: Add settings reset on start init priority.

- app/Kconfig
- app/src/battery.c
* To be able to use the Zephyr `voltage-divider` driver,
add a mode for fetching raw voltage from the sensor
and do state of charge calculation outside of the driver.
I hit this when trying to look at using the Zephyr build in voltage-divider sensor driver. That sensor only allows fetching a `SENSOR_CHAN_VOLTAGE` value, so this adds a new Kconfig option to make our battery code able to simply fetch a raw voltage, and do the lithium state-of-charge calculation "outside" of the driver.
This does need a small Zephyr fix where-by their `voltage_divider_scale_dt` implementation has an overflow issue, will be adding that fix to our branch (https://github.com/zmkfirmware/zephyr/pull/31) and submitting upstream.
Edit: Looks like this was already fixed in upstream via …
> feat: Add ability to fetch battery voltage.

- docs/docs/behaviors/index.mdx
- docs/sidebars.js
Resolves #1044 
Resolves #525 
@petejohanson this is an initial draft of the behavior overview page, structured with groupings I deemed sensible. While I'm not entirely satisfied with all the descriptions yet, I aimed to steer clear of excessive repetition from the detailed behavior pages to prevent duplication of content yet give a good idea to readers what each behavior is for.
I opted not to include an example column because the majority of examples would be quite basic, typically consisting of bindings and keycodes. Additionally, the provided links typically direct users straight to the relevant section of the documentation explaining the usage.
As for behaviors that don't have their own binding, such as macros and sensors, I wasn't entirely sure where to put them. Currently, I've …
> feat(docs): Add Behavior overview page

- docs/docs/development/new-behavior.mdx
- docs/docs/development/new-shield.mdx
- docs/docs/features/keymaps.mdx
Thanks to @huber-th in #2193 we now have an overview page for behaviors. Add references to that page instead of mentioning key press page in places where we would like to refer to behaviors in general.
> refactor(docs): Refer to overview page for behaviors

- .github/workflows/build-user-config.yml
* Allow using snippets https://docs.zephyrproject.org/latest/build/snippets/using.html for user builds in a `snippets` array propertly.
You can see this in action in https://github.com/petejohanson/le-capybara-zmk-config/actions/runs/8412145898 which enables an extra EC calibration utility using a snippet there.
> feat(build): Allow specifying snippets for a build.

- app/src/behaviors/behavior_sticky_key.c
Function [sticky_key_timeout](https://github.com/zmkfirmware/zmk/blob/main/app/src/behaviors/behavior_sticky_key.c#L124) is defined with return type `int`, yet it is not returning any value. Both calls to this function also ignore the return value. Therefore the return type is modified to `void` to remove this warning.
> fix(build): Modify function return type to remove compiler warning

- docs/src/templates/setup.ps1.mustache
- docs/src/templates/setup.sh.mustache
- schema/hardware-metadata.schema.json
Split off from #1946; this is just the zmk infrastructure part to support board revisions.
Changes:
1. Updated schema to support a list of revisions, as well as a default revision
2. Updated `setup.sh` to prompt the user for revisions if the board yml defines revisions (and will also say which one is the default — if any)
3. `setup.sh` will append `@revision` to the board name.
The script doesn't support revisions for shields yet, but if the approach is sound I'll add that as well as fix up the powershell script.
I've set up a repo to test: https://github.com/zhiayang/zmk-test, but this depends on #1946.
> feat(boards): Support board revisions

- docs/docs/config/behaviors.md
Fixes the incorrect types for `bindings` prop in `docs/config/behaviors`, for hold-tap, sticky key and sensor rotate behaviors.
In a separate commit, I split the sensor rotate table into two separate tables for `sensor-rotate` and `sensor-rotate-var` since there didn't seem to be enough common properties anymore to make the single table worth it.
> fix(docs): Fix bindings types in behaviors config page

- app/module/drivers/kscan/kscan_gpio_charlieplex.c
- docs/docs/config/kscan.md
This PR has a fix for the issue with interrupt not being enabled if just one compatible device is configured (see [issue](https://github.com/zmkfirmware/zmk/issues/2201)).
Further in the current documentation, in the example the pins used for scanning the matrix are configured with `GPIO_PULL_DOWN`. This results of a current draw of 260mAh per configured pin during sleep. This is not necessary as the pull flags are set as needed during the scan.
> charlieplex fix interrupt and documentation for pull down config

- docs/docs/troubleshooting.md
* Update error string to reflect current version
* Merge them under the same devicetree errors title
> feat(docs): Update section for devicetree_generated error

- docs/docs/development/new-shield.mdx
- Add a tip that links to ZMK shields folder for users to use as starting points
- I think it's a good idea, but I am open to discussion if anyone has concerns.
- Add some comments in the matrix transform example to look less like a complete overlay, but also add the closing brace just in case.
> feat(docs): Add pointer to shield folder in new shield guide

- app/include/zmk/hid.h
- app/src/hid.c
We correct an off-by-one buffer overflow I found while diagnosing #2257. The problem is that we should be rounding up the computed key array length; consider the case where we want to show 10 keys, i.e. `ZMK_HID_KEYBOARD_NKRO_MAX_USAGE` is 9 and so we need 10 bits (because this range is inclusive); then we only use an array of length 1, which doesn't have enough space.
(An actual buffer overflow by one byte occurs e.g. here: https://github.com/zmkfirmware/zmk/blob/20df20009d6e38c55fc062fc449371b4470021b3/app/src/hid.c#L151 but in any case the `1` will not be observed because the number of bytes transmitted to the USB endpoint will be too small.)
> fix(hid): Correct off-by-one buffer overflow with NKRO

- app/boards/arm/bluemicro840/arduino_pro_micro_pins.dtsi
- app/boards/arm/bluemicro840/bluemicro840_v1-pinctrl.dtsi
- app/boards/arm/bluemicro840/bluemicro840_v1.dts
- app/boards/arm/mikoto/arduino_pro_micro_pins.dtsi
- app/boards/arm/mikoto/mikoto_520-pinctrl.dtsi
- app/boards/arm/mikoto/mikoto_520.dts
- app/boards/arm/nice_nano/arduino_pro_micro_pins.dtsi
- app/boards/arm/nice_nano/nice_nano-pinctrl.dtsi
- app/boards/arm/nice_nano/nice_nano.dtsi
- app/boards/arm/nrfmicro/arduino_pro_micro_pins.dtsi
- app/boards/arm/nrfmicro/arduino_pro_micro_pins_52833.dtsi
- app/boards/arm/nrfmicro/arduino_pro_micro_pins_flipped.dtsi
- app/boards/arm/nrfmicro/nrfmicro-flipped-pinctrl.dtsi
- app/boards/arm/nrfmicro/nrfmicro-pinctrl.dtsi
- app/boards/arm/nrfmicro/nrfmicro_11.dts
- app/boards/arm/nrfmicro/nrfmicro_11_flipped.dts
- app/boards/arm/nrfmicro/nrfmicro_13.dts
- app/boards/arm/nrfmicro/nrfmicro_13_52833.dts
nice nano didn't have definitions for SPI in pinctrl and dtsi, requiring users to manually define in their shield definitions if they wanted to use SPI. This should be defined at the board level.
> fix(boards): nrf boards missing SPI definitions for pro_micro pins at the board level

- app/src/rgb_underglow.c
This fixes a bug introduced in #2244
> Correctly set underglow state when entering sleep

- app/dts/behaviors/soft_off.dtsi
This PR is aiming to fix #2274 
The behavior label gets truncated because the len is 9, defined in app/include/zmk/split/bluetooth/service.h as ZMK_SPLIT_RUN_BEHAVIOR_DEV_LEN
Shortening the keymap_soft_off solves the issue. 
Thanks bravekarma (discord) for the advice.
> shortening keymap_soft_off behavior label

- app/src/kscan_sideband_behaviors.c
* In order to be sure the rest of the system is fully ready before initializing, because init may result in immediate events being triggered when used with toggle direct kscan inner devices.
Hit this with problems with the ZMK Uno shield after the soft off refactor. Without this change, the code attempts to schedule work items before that's allowed by Zephyr, leading to unexpected crashes.
> fix: Initialize sideband kscan in APPLICATION.

- app/boards/shields/zmk_uno/zmk_uno.dtsi
The devicetree pulls always add on to the extra pulls configured by toggle mode, so these should not have pulls defined in the devicetree. Saved ~200uA avg on another board with a 3t toggle switch.
AFAIK there are no other upstream board using `toggle-mode;` where this needs to be corrected
> fix(boards): Fix pulls on ZMK uno toggle switch

- docs/docs/config/kscan.md
The documentation for `toggle-mode` is unclear and leaves room for interpretation around the activation of the pull resistors.
This documents an example implementation, as well as writing up some of the quirks and features someone trying to implement toggle-mdoe functionality may not know (e.g. the power on behaviour and gpio requirements)
> feat(docs): Document example toggle-mode implementation

- app/boards/arm/mikoto/Kconfig
- app/boards/arm/nice_nano/Kconfig
Added a Kconfig option to enable SOC_DCDC_NRF52X_HV for nice_nano_v2 and mikoto. According to Nordic's documentation, the DC/DC regulator is more efficient than the LDO regulator, so this is enabled by default.
The following boards do not support this mode and were not changed:
- nice_nano
- nice60
- nrfmicro_11, nrfmicro_13
- nrf52840_m2
- bluemicro840
I could not find schematics to confirm whether the following boards support this mode:
- bt60_v1, bt60_v2
- bt65_v1
- bt75_v1
- corneish_zen_v1, corneish_zen_v2
- pillbug
- puchi_ble_v1
- s40nc
> feat(boards): Add nRF52 high voltage DC/DC config

- docs/blog/2023-04-06-zephyr-3-2.md
- docs/docs/behaviors/caps-word.md
- docs/docs/features/backlight.mdx
Credit for noticing these typos go to [slashfoo on discord](https://discord.com/channels/719497620560543766/883452966114324550/1231473298538496121), I happened to have a spare moment to sort it.
> fix(docs) removing "to to" typos

- app/Kconfig
- app/src/usb_hid.c
* To avoid USB init issues due to other initialization disrupting USB setup, move USB setup to a lower priority.
Hit this as part of the Studio work... that adds just enough additional init time that splitting up the USB and USB HID earlier in init levels caused failures on my host, so defer USB until the very end of startup.
> fix(usb): Ensure USB init is last

- app/core-coverage.yml
* Include an rp2040 core build target, and include USB logging snippet for completeness.
> chore: Add rp2040/USB logging core coverage.

- .github/workflows/build.yml
[All `push` event runs of the Build action since 2024-01-25 have failed](https://github.com/zmkfirmware/zmk/actions/workflows/build.yml?query=event%3Apush+is%3Afailure) in part[^1] because `actions/checkout` is not being run prior to `tj-actions/changed-files`.
~~This primarily presents a problem for novice end-users looking for `settings_reset` firmware [as linked from the documentation](https://zmk.dev/docs/troubleshooting#option-2-download-reset-uf2-from-zmks-workflow). The outdated binaries appear to be entirely ineffective on Zephyr 3.5 firmware[^2].~~ All artifacts containing the outdated firmware have now expired.
<details>
<summary>Remaining commits are general improvements to security and efficiency:</summary>
Group builds by workflow and [github …
> Build CI fixes/improvements

- docs/docs/troubleshooting/connection-issues.mdx
I would argue that #2262 is a prerequisite for this.
- Link directly to the Build workflow. Should the filename of the workflow change without a corresponding docs update (oops) users will still end up on the Actions tab and can navigate to the new "Build" action.
- Filter on successful runs from jump.
- Minor rewording.
> docs: improve settings_reset link

- app/Kconfig
- app/src/hid_listener.c
- docs/docs/config/system.md
This adds a new config value `ZMK_HID_SEPARATE_MOD_RELEASE_REPORT` where, if enabled, the report for a key release is sent separately to the accompanying modifier release signals, which are then sent in a second report.
This fixes an issue where certain applications are unable to work with implicitly modified keys (e.g. colon) due to them registering the modifier release prior to the actual key release.
Have tested this on my personal keyboard and `wev` now shows the signals in the correct order.
=> **Previously:** ```LSHIFT (pressed) -> colon (pressed) -> LSHIFT (released) -> **semi**colon (released)```
=> **Now:** ```LSHIFT (pressed) -> colon (pressed) -> colon (released) -> LSHIFT (released)```
> fix: adding option to separate implicit mod release from key release

- app/include/zmk/event_manager.h
* Used for ZMK Studio even remappers to be sure the one RPC event listener subscribes to their mapped events.
> feat(core): Support adding subs to other listeners.

- app/include/zmk/ble.h
- app/src/ble.c
- app/src/hog.c
Small refactor to make it easier to get a `struct bt_conn *` for the active profile, if we are connected.
> refactor(ble): Extract API to get active profile connection.

- app/CMakeLists.txt
- app/Kconfig.behaviors
- app/include/drivers/behavior.h
- app/include/linker/zmk-behavior-local-id-map.ld
- app/include/zmk/behavior.h
- app/src/behavior.c
* Add a new feature for tracking a given behavior by a new concept of a "behavior local ID" which is a stable 16-bit identifier for a given behavior, that is resilient to new behaviors being added and requires no additional work on the part of the behavior authors.
* Add implementations for either settings lookup table, or CRC16 hashing of behavior device names for generating behavior local IDs.
> feat(behaviors): Add local ID system for behaviors

- app/src/hid_indicators.c
* Avoid static listener to prevent subscription
issue.
> fix: Adjust hid indicator listeners for event refactor

- app/Kconfig.behaviors
- app/include/zmk/behavior.h
- app/src/backlight.c
- app/src/behavior.c
- app/src/ble.c
- app/src/endpoints.c
- app/src/ext_power_generic.c
- app/src/main.c
- app/src/rgb_underglow.c
- app/src/split/bluetooth/central.c
- app/src/split/bluetooth/peripheral.c
* Avoid doing duplicate calls to setings_load_subtree, which iterates NVS fully each time under the hood, and instead use on settings_load later in the lifecycle.
Found this during Studio work, after we ended up with many more settings entries. Pinned it down to the many calls to `settings_load_subtree` which under the hood was actually loading the full NVS data each time, doing a ton of duplicate work. This refactor moves away from duplicate subtree loads. Doing so requires a bit of care to make timing work and have the right things loaded when needed, especially for BT initialization.
> fix: Improve startup time with proper settings loading.

- app/src/ext_power_generic.c
* Because settings load is delayed now, enable external
power on init, and let it be disabled on settings load
later, to ensure power is on early for
other peripheral initialization.
Fixes: #2361
> fix: Fix external power settings load issue.

- docs/docs/development/new-shield.mdx
The property is required but is missing from the examples in the new shield guide.
> fix(docs): Add required display-name in physical layout examples

- .vscode/extensions.json
The docs use .mdx files, this extension gives them proper syntax highlighting.
> chore(vscode) Added a recommended extension for .mdx files

- docs/docs/behaviors/layers.md
- docs/docs/features/keymaps.mdx
- docs/docs/keymap-example.md
Rephased some things and added some clarification. The goal is to resolve #1284.
> mini-feat(docs) Improvements to the layer documentation

- docs/docs/config/kscan.md
Fixes broken link from config section to new shield guide.
> fix(docs): Fix link for matrix transform

- docs/docs/config/system.md
Just documenting the Kconfig option, not addressing the general issue on "dongle" documentation.
Fixes #2373.
> fix(docs): Document number of peripherals Kconfig

- docs/docs/behaviors/layers.md
The example here was malformed and a bit weird with the extra `#define` etc. I thought I'd fix that, then decided that the example wasn't actually useful here and it was inconsistent with the rest of the page.
Also included a couple tweaks to other behavior descriptions to make them more technically correct.
> fix(docs): Fix toggle layer docs

- app/src/gpio_key_wakeup_trigger.c
* Other drivers properly disconnect/de-config pins now, so we need to be sure the wakeup trigger connects the wake pin as input.
> fix(pm): Properly configure a wakeup as input.

- app/module/drivers/kscan/kscan_composite.c
* Clean up composite kscan to allow multiple instances properly.
* Implement PM hook and properly suspend/resume the child devices.
Fixes: #2388
Note: I don't have my Ferris on hand to properly test this, so hoping Scalee on #2388 can test.
> fix: Proper device PM support for composite kscan.

- docs/docs/behaviors/backlight.md
- docs/docs/behaviors/power.md
- docs/docs/behaviors/reset.md
- docs/docs/behaviors/underglow.md
- docs/docs/config/index.md
- docs/docs/config/system.md
- docs/docs/customization.md
- docs/docs/development/new-behavior.mdx
- docs/docs/development/new-shield.mdx
- docs/docs/features/battery.md
- docs/docs/features/bluetooth.md
- docs/docs/features/combos.md
- docs/docs/features/split-keyboards.md
- docs/docs/troubleshooting/connection-issues.mdx
- docs/docs/user-setup.mdx
- docs/sidebars.js
This is an explainer page to describe how split keyboards work in ZMK, with specific details on flashing, pairing, split communications and behaviors with locality. Fixes #948.
> feat(docs): Add a split keyboards feature page

- .github/workflows/hardware-metadata-validation.yml
* Newer Docker image requires --break-system-packages for pip.
> fix: Fix hardware metadata validation after image changes.

- docs/docs/behaviors/reset.md
Somehow a second `#` snuck in, breaking the link. `npm build` warns about these, note to self and others for the next time.
> fix(docs): Fix broken anchor in reset behaviors

- docs/docs/troubleshooting/building-issues.md
Add a small remark to avoid confusing users with the column number in troubleshooting build errors.
> feat(docs): Add a note on column numbers for DTS errors

- docs/docs/behaviors/mod-morph.md
Added more precision to docs, where we don't want to conflate keycodes vs behavior bindings. Also elaborated on the grave escape behavior just in case it isn't clear from the definition.
As an aside, I want to do a pass on all the behavior pages to make them more consistent. Currently the header levels, overall organization, examples etc. are different across many of them.
> fix(docs): Fix mod-morph terms from keycodes to bindings

- docs/docs/user-setup-cli.mdx
- docs/docs/user-setup.mdx
The page is hidden in the sidebar, and only accessible through a link in an `info` box under `user-setup.mdx`.
By making it publically available in this way while marking it as experimental repeatedly, we should be able to get some useful feedback on it prior to switching over to it officially.
Obviously, credit goes to @joelspadin for writing the tool and most of the doc page, I just reformatted it.
> feat(docs): Added and modified docs to point users to the experimental zmk-cli.

- app/src/display/widgets/layer_status.c
- app/src/display/widgets/output_status.c
Increase buffer size used for placing LVGL symbols on displays. This prevents array overflow warnings as discussed in #2444.
Also convert one sprintf to snprintf to ensure the buffers are always null terminated and never overflow.
Resolves #2444
>   fix(display): widgets: increase buffer size for symbols

- docs/blog/2020-05-24-wip.md
- docs/blog/2020-08-12-zmk-sotf-1.md
- docs/blog/2020-09-21-zmk-sotf-2.md
- docs/blog/2020-10-03-bootloader-fix.md
- docs/blog/2020-11-09-zmk-sotf-3.md
- docs/blog/2021-01-27-zmk-sotf-4.md
- docs/blog/2021-07-17-zephyr-2-5.md
- docs/blog/2022-03-08-zephyr-3-0-upgrade-prep.md
- docs/blog/2022-04-02-zephyr-3-0.md
- docs/blog/2022-04-10-zmk-sotf-5.md
- docs/blog/2022-04-21-zmk-2yo.md
- docs/blog/2023-04-06-zephyr-3-2.md
- docs/blog/2023-06-18-encoder-refactors.md
- docs/blog/2023-10-05-zmk-sotf-6.md
- docs/blog/2023-11-09-keymap-editor.mdx
- docs/blog/2023-12-17-nodefree-config.md
- docs/blog/2024-01-05-zmk-tools.md
- docs/blog/2024-02-09-zephyr-3-5.md
- docs/blog/authors.yml
- docs/docusaurus.config.js
Build now complains about two things related to the blog:
- not using global authors with `authors.yml`
- not putting truncate markers in blog posts so they can be truncated in the main page
While both behaviors can be disabled, I think it's nicer to follow the recommendation in these cases.
When putting truncate markers I ran into the issue that `.md` files are also considered mdx by default, in Docusaurus 3. This causes an issue: We can't use `` in .md files because that's invalid mdx. But if we use the mdx format `{/* ... */}` instead, then prettier tries to fix it to `{/_ ... _/}` thinking it's markdown. 
The [`format` config](https://docusaurus.io/docs/api/docusaurus-config#markdown) controls this and can be set to `detect` to fix this, so I did that. The alternative would be to try …
> refactor(blog): Add global authors file and truncate markers

- app/src/behaviors/behavior_backlight.c
Spotted this whilst working on a custom backlight behavior. The set brightness function in the backlighting code has a max of 100, as does the zephyr led-pwm driver https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/led/led_pwm.c
The range for the set brightness function should reflect this max, otherwise ~2/3rds of the possible brightness range will set the leds to the same brightness
> Fix max brightness in backlight metadata

- app/scripts/west_commands/test.py
> Fix path to `run-test.sh` when ZMK is used as a module

- app/boards/arm/nice60/nice60-pinctrl.dtsi
- app/boards/arm/nice60/nice60.dts
Add spi3_sleep pinctrl node to fix nice!60 builds with both RGB underglow and sleep enabled.
> fix(boards): add sleep pinctrl node for nice!60

- app/src/ble.c
* Refactor broke the build when clearing bonds on start.
> fix(bt): Fix compilation failure for clearing bonds.

- .pre-commit-config.yaml
- app/boards/arm/corneish_zen/widgets/battery_status.c
- app/boards/shields/nice_view/widgets/peripheral_status.c
- app/boards/shields/nice_view/widgets/status.c
- app/include/drivers/behavior.h
- app/include/zmk/virtual_key_position.h
- app/src/behaviors/behavior_caps_word.c
- app/src/behaviors/behavior_tap_dance.c
- app/src/display/widgets/battery_status.c
- app/src/endpoints.c
- app/src/hid.c
- app/src/keymap.c
- app/src/kscan_sideband_behaviors.c
- app/src/physical_layouts.c
- app/src/sensors.c
- app/src/studio/rpc.c
- app/src/workqueue.c
slight change to the `pre-commit` config.
the version of clang-format used determined the way the code is formatted.
I was having a lot of trouble because my local version of clang-format (Arch Linux) is more recent than the one running on Github Actions. Therefore, the pre-commit action would almost always fail because of difference in clang-format output.
Using this version of the `pre-commit` config, it specifies the exact version of `clang-format` to be used, which I believe matches what is currently using on Github.
> pre-commit: use versioned clang-format hook

- app/src/kscan_sideband_behaviors.c
- app/src/physical_layouts.c
* If using a sideband kscan device to wrap a native kscan device, ensure the inner kscan device is also wakeup enabled to it can be waken from a deep sleep state by key press.
> fix: Fix wakeup from kscan wrapped in sideband.

- app/src/keymap.c
* When not building with runtime keymap support, make the keymap const.
> fix: Reduce RAM usage in the keymap

- app/src/physical_layouts.c
`DT_HAS_COMPAT_STATUS_OKAY` expects a compatible, what we actually want to do is check if the physical layout node in a position map is compatible with zmk_physical_layout and in ok status.
For that, we'd use `DT_NODE_HAS_COMPAT_STATUS` but `COND_CODE_1` only supports functions with one or two args, so we have to use UTIL_AND to accomplish the same behavior.
> fix(studio): Update position map querying

- app/src/keymap.c
This fixes the string leak when a layer name is changed to a longer one, but is discarded and reverted to the original shorter one from ZMK Studio.
> fix(studio): Ensure null-termination of layer name read from settings

- app/include/zmk/matrix.h
- app/src/physical_layouts.c
* Instead of erroring out, simply ignore physical layouts if we detect a chosen matrix transform, and warn instead.
I see this as a prerequisite to merging #2469 so existing folks with setups and chosen nodes no longer encounter build failures.
> fix(core): Warn only with layouts + chosen transform

- app/include/zmk/behavior.h
- app/include/zmk/behavior_queue.h
- app/include/zmk/split/bluetooth/service.h
- app/src/behavior.c
- app/src/behavior_queue.c
- app/src/behaviors/behavior_hold_tap.c
- app/src/behaviors/behavior_macro.c
- app/src/behaviors/behavior_mod_morph.c
- app/src/behaviors/behavior_sensor_rotate_common.c
- app/src/behaviors/behavior_sticky_key.c
- app/src/behaviors/behavior_tap_dance.c
- app/src/combo.c
- app/src/keymap.c
- app/src/split/bluetooth/central.c
- docs/docs/features/split-keyboards.md
This is another attempt to solve #1494. My understanding is that #1630 only covers the case of macros invoking global behaviors. I incorporated the changes in it and attempted to address the existing comments.
In addition to the other PR, this should cover sticky keys, hold-taps, mod-morphs and work with source+global locality behaviors. I tested the reset behaviors with hold-taps and tap dances so far.
I am not familiar with these parts of the code; so far I stuck an extra field `source` wherever I saw a `position` and passed it around. Specifically, it is a new field in `zmk_behavior_binding_event`. Any recommendations are welcome on how better to do it.
TODO:
> fix(split): Make locality work for nested behaviors

- .github/workflows/build-user-config.yml
Address reported build failures in the community for those affected by `ubuntu-latest` roll out to 24.04: https://github.com/actions/runner-images/issues/10636
> fix: Force Ubuntu 22.04, pending CI fixes.

- docs/docs/development/hardware-integration/new-shield.mdx
Some broken anchors as a result of #2515 that didn't get picked up during `npm run build`.
> docs: fixed broken anchors

- docs/blog/2023-10-05-zmk-sotf-6.md
Removed dated reference to spaceman a username no longer assigned to me and replaced with the spaceboards organization https://github.com/spaceboards
> Remove reference to spaceman

- app/src/keymap.c
- app/src/studio/keymap_subsystem.c
- app/west.yml
* More fine grained status reporting when saving changes. Needed to we can notify the client if we've got errors saving settings due to running out of space, etc.
* Return the max layer name lenght in the keymap payload, for the UI to leverage.
> feat: A few enhancements to our RPC messages.

- app/boards/shields/nice_view/widgets/status.c
Fixes https://github.com/zmkfirmware/zmk/issues/2540
When display names are not present, the `layer_label` field may appear as an empty (zero-length) string rather than `NULL`; in either case, the status widget should show "LAYER N" where N is the 0-indexed layer number.
> Adding length check to layer_label in nice_view status widget, to enable numeric layer display. (fixes #2540)

- app/west.yml
Worked on some tweaks to reduce our stack usage for our RPC stack, in particular with some tweaks to nanopb that bring it's stack size usage down.
See https://github.com/zmkfirmware/nanopb/commit/bf328175df765d05cbc0c19734af85378af0280c for the change to nanopb (which we now have a fork of) and the small changes to Zephyr that I'll merge into our fork when we're happy.
With this change, on USB on stm32f072, I can drop the RPC stack size to 2048 and have enough wiggle room to space (normal usage seems to go up to 1700 bytes or so).
Needs more testing, but the nanopb code changes are fairly innocuous.
> feat: Tweaks for reduced nanopb stack usage.

- app/include/zmk/usb.h
- app/src/usb.c
- app/src/usb_hid.c
Update `zmk_usb_is_hid_ready` to check that HID configuration from the host has been done, before allowing the keyboard to be used as a HID device.
This is done by adding `bool is_configured` and toggling it off when the device is disconnected, and enabling it when `usb_status == USB_DC_CONFIGURED`.
This is a naive solution for https://github.com/zmkfirmware/zmk/issues/841, where having a USB-power cable without data driving the keyboard, like a power bank, still has the firmware thinking that it's connected to a host and futilely sending data over USB.
When the cable to a power source is plugged in, the USB DC status (from Zephyr) goes through the following states:
```
USB_DC_CONNECTED -> USB_DC_SUSPEND
```
While for cables to a host machine:
```
USB_DC_CONNECTED -> USB_DC_SUSPEND -> …
```
> fix(usb): detect USB power mode to fallback to BLE

- app/boards/shields/jian/jian.dtsi
- app/boards/shields/jian/jian.keymap
- app/boards/shields/jiran/jiran.dtsi
- app/boards/shields/jiran/jiran.keymap
- app/boards/shields/jiran/layouts/6column.dtsi
- app/boards/shields/jiran/layouts/full.dtsi
- app/boards/shields/jiran/layouts/jian.dtsi
- app/boards/shields/jiran/layouts/position_map.dtsi
- app/boards/shields/jorne/jorne.dtsi
- app/boards/shields/jorne/jorne.keymap
- app/boards/shields/jorne/layouts/5column.dtsi
- app/boards/shields/jorne/layouts/6column.dtsi
- app/boards/shields/jorne/layouts/full.dtsi
- app/boards/shields/jorne/layouts/position_map.dtsi
- app/dts/layouts/kgoh/jian/5column.dtsi
- app/dts/layouts/kgoh/jian/6column.dtsi
- app/dts/layouts/kgoh/jian/full.dtsi
- app/dts/layouts/kgoh/jian/position_map.dtsi
Adding physical layouts and updating keymaps for Jian, Jiran and Jorne keyboards.
> feat(shields): add physical layouts for Jian, Jiran and Jorne

- app/boards/shields/murphpad/Kconfig.defconfig
- app/boards/shields/murphpad/boards/nice_nano.conf
- app/boards/shields/murphpad/boards/nice_nano.overlay
- app/boards/shields/murphpad/boards/nice_nano_v2.overlay
- app/boards/shields/murphpad/murphpad-layout.dtsi
- app/boards/shields/murphpad/murphpad.conf
- app/boards/shields/murphpad/murphpad.keymap
- app/boards/shields/murphpad/murphpad.overlay
- **Added matrix transforms and physical layouts for three configurations.** This is a numpad, but notably the first three positions of column 0 are actually tact switches on the back of the PCB. I believe the new transforms make this clearer (the keymap appearance matches QMK Configurator now, too)
- Tweaked default keymap:
- more closely resembles the QMK Configurator default map (reduces confusion for users who are new to ZMK; also generally less niche)
- more useful OOTB for ZMK (immediate access to output selection, easier BT profile switching).
- Cleaned up formatting a bit.
- Updated encoder configuration to current ZMK standards.
- Avoid forcing RGB on for `nice_nano`.
- Corrected the number of default LEDs. While some users may opt for less or more, there are exactly eight …
> refactor(shields): MurphPad

- app/include/zmk/physical_layouts.h
- app/src/keymap.c
- app/src/physical_layouts.c
- app/src/studio/keymap_subsystem.c
* To avoid tons of migration, extra flash writes, etc, we keep the keymaps and settings using a key position index that's tied to the stock layout, and at runtime mapping key positions as needed.
> fix: Optimize layout changes by doing runtime mapping

- docs/package-lock.json
This was giving out security vulnerabilities and dependabot couldn't do it automatically. Ran `npm audit fix` twice, then checked stuff for any obvious weirdness. Should be fine.
> chore: updated path-to-regexp in docs

- app/west.yml
* Pull in fixes for prefering generator/protoc instead of the host protoc, for better compatibility.
See https://github.com/nanopb/nanopb/pull/958 and https://github.com/zmkfirmware/nanopb/pull/4
> fix(studio): Bump nanopb version with build fixes.

- docs/docs/features/studio.md
Trying to resolve [studio 70](https://github.com/zmkfirmware/zmk-studio/issues/70).
Likely there are things that I've missed and need to be listed. I think this table makes the most sense in this page, at least for now.
> docs: studio features list

- docs/docs/features/underglow.md
Using PIO SPI for the "Other Boards" example:
1. Does a better job of demonstrating how the RGB config for hardware X can differ from hardware Y (the current examples are nearly-identical).
2. Provides a reference configuration which an increasing number of hobbyist keyboard makers will inevitably end up looking for in the near term. (When/if ZMK moves to Zephyr 3.7, switching to `worldsemi,ws2812-pio` might be a good idea for further emphasis on point 1.)
---
- Since the primary motivation is to expand beyond a single hardware configuration, much of the rest of the page was edited with [TMTOWTDI](https://en.wiktionary.org/wiki/TMTOWTDI) in mind.
- That said, I don't know if any ZMKers have *ever* tested any of the other LED ICs in the list. Rather than affirmatively stating "ZMK supports …
> docs(feat): further generalize RGB information

- app/dts/layouts/common/numpad/17_key.dtsi
- app/dts/layouts/common/numpad/18_key.dtsi
- app/dts/layouts/common/numpad/18_key_00.dtsi
- app/dts/layouts/common/numpad/19_key_00.dtsi
- app/dts/layouts/common/numpad/20_key.dtsi
- app/dts/layouts/common/numpad/21_key.dtsi
- app/dts/layouts/common/numpad/22_key.dtsi
- app/dts/layouts/common/numpad/22_key_00.dtsi
- app/dts/layouts/common/numpad/23_key_00.dtsi
- app/dts/layouts/common/numpad/24_key.dtsi
- app/dts/layouts/common/numpad/position_map.dtsi
Added physical layouts for the following variants of numpads:
- With and without extra top row
- 2U plus key or 1U plus and backspace keys
- 2U 0 key or 1U 0 and 00 keys
- Full 1U grid/macropad layout
Other layouts exist, such as "southpaw" horizontally mirrored layouts, and layouts with a fifth column, but those seem to be much less common. There are a lot of layouts here already, so we can add the less common ones later if anyone asks for them.
> feat(boards): Add numpad layouts

- docs/docs/development/hardware-integration/physical-layouts.md
Resolving [Studio 72](https://github.com/zmkfirmware/zmk-studio/issues/72) by adding the links in tip boxes. Also adjusted the content to reflect the new underlying layout system, which doesn't have lossy position maps anymore.
> docs: physical layouts page adjustments

- docs/docs/development/local-toolchain/setup/container.mdx
Just noticed there's a typo in the docs. I believe it should be `/workspaces/*`, not `/workspace/*`.
> docs: Fix typos in local-toolchain/setup

- .github/dependabot.yml
Attempt to organize dependabot so that:
- we don't have individual "version" (as opposed to "security") updates
- PRs are grouped into separate production and dev groups
- for production, two groups for major vs. minor+patch
- for dev, only minor+patch
- security updates aren't touched, so there will be individual PRs as is
The resulting PRs can be seen at https://github.com/caksoylar/zmk/pulls
Config reference: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
Open question/points for discussion:
- should we also have a separate major updates group for dev deps? or alternatively, remove minor+patch constraint?
- should security updates be constrained to minor+patch?
- any need to create other groups for …
> chore: Config dependabot for grouped npm updates

- app/boards/arm/ferris/ferris_rev02.dts
- app/boards/shields/snap/snap_right.overlay
- app/dts/bindings/zmk,kscan-composite.yaml
- app/module/drivers/kscan/kscan_composite.c
- docs/docs/config/kscan.md
Renamed the composite kscan's column-offset property to col-offset for consistency with other properties such as matrix transform's col-offset and matrix kscan's col-gpios.
column-offset remains supported but is deprecated.
> fix: Fix inconsistent column offset property

- docs/docs/features/studio.md
Some users were running into permission errors when trying to access Studio, added a note in the docs to help prevent this.
> docs: Added permissions note for ZMK Studio USB use

- app/boards/arm/ckp/bt75_v1.zmk.yml
Spotted this underscore that shouldn't be there when reading the studio blog post, as per the other BTxx / CKP series boards it should just have a space
> fix(boards): Fix typo in BT75 metadata

- app/snippets/nrf52833-nosd/nrf52833-nosd.overlay
- app/snippets/nrf52833-nosd/snippet.yml
- app/snippets/nrf52840-nosd/nrf52840-nosd.overlay
- app/snippets/nrf52840-nosd/snippet.yml
- docs/docs/config/system.md
Add snippet to build for nRF52833/52840 boards while ignoring the SoftDevice. This is necessary as nRF52833 boards are memory-constrained and nRF52840 boards can accidentally erase the SoftDevice.
> feat(boards): add nrf52 nosd snippets

- app/boards/shields/settings_reset/settings_reset.conf
Without this tweak, a build like `west build -b corneish_zen_v2_left -- -DSHIELD=settings_reset` fails because the status screens are enabled and they expect certain APIs related to e.g. BT profiles that don't get built. This can be an issue with any onboard controller keyboard that enables a display with status screen by default, like ones that live in modules. While good practice would be to `#if defined` guard the appropriate widgets, there is also no reason to have display enabled with settings reset.
> fix: Disable display feature for settings_reset

- .gitlint
- .pre-commit-config.yaml
- docs/docs/development/contributing/commit-messages.md
- docs/docs/development/local-toolchain/pre-commit.md
- docs/sidebars.js
* Add gitlint to pre-commit setup
* Update pre-commit setup for installing commit-hooks
* Add "Commit Conventions" contributing docs
> ci: Add gitlint and document commit conventions

- docs/docs/features/studio.md
Added some notes on additional things to check when setting up Studio for a device, namely RAM consumption and CDC-ACM snippet support.
Also added a note to the top of the features page informing users that the keyboard needs to be configured correctly for use with Studio.
> docs: Some minor improvements to the studio features page

- docs/docs/features/studio.md
A tiny tweak to reduce any user confusion on where to apply these changes to enable ZMK Studio.
> docs: Mention build.yaml in Studio instructions

- docs/docs/development/hardware-integration/includes/_gpio-key-matrix.md
- docs/docs/development/hardware-integration/includes/_gpio-key-wakeup.md
- docs/docs/development/hardware-integration/includes/_soft-off-behavior.md
- docs/docs/development/hardware-integration/includes/_soft-off-waker.md
- docs/docs/keymaps/behaviors/soft-off.md
Minor improvements to the soft off setup docs to improve some clarity things. Also documented the split peripheral off on press property with information on its purpose.
Makes #2299 redundant.
> docs: touchups on the soft off information for improved clarity.

- app/module/drivers/gpio/gpio_595.c
Add support for initializing a pin to a given high/low value during configuration. Needed for proper initialization by systems like GPIO hogs or gpio-leds Zephyr drivers.
> feat(drivers): Support init high/low in 595 driver

- app/boards/shields/tester_xiao/tester_xiao.overlay
This PR is for tester_xiao.
To test the following article, I specified `seeeduino_xiao_ble` and `tester_xiao` for `west build`, but a `devicetree error` occurred. This happened on Github Actions using the new zmk-config.
https://zmk.dev/docs/troubleshooting/hardware-issues
The issue occurred because the RC macro was not defined, and I addressed it by adding `#include <dt-bindings/zmk/matrix_transform.h>` to the `.overlay` file.
I would appreciate it if you could comment if there is a more appropriate solution or if there is any additional code that needs to be included.
> fix: include a header file for RC macros

- docs/docs/development/hardware-integration/new-shield.mdx
I happened to notice that in the documentation about creating a new keyboard shield, ``my_keyboard_left.conf``` is repeated twice. I decided to fix this small but minor issue.
> Docs: Сorrecting a wrong file name in new-shield.mdx

- docs/docs/keymaps/behaviors/layers.md
Moved the section about defines to the bottom, clearifing layer behaviors take a number as argument.
> docs: move layer defines to reduce confusion

- app/boards/arm/glove80/glove80_lh.dts
- app/boards/arm/glove80/glove80_rh.dts
- app/dts/bindings/gpio/moergo,glove80-ext.yaml
- app/dts/bindings/vendor-prefixes.txt
Added based on the docs from https://docs.moergo.com/glove80-user-guide/appendix-more-customizations/#extending-the-glove80-electronics to make it easier to address the GPIO on the glove80 in a uniform way across halves.
> feat(boards): Add glove80 nexus node for extension GPIO.

- app/boards/seeeduino_xiao_ble.overlay
`xiao_serial` node corresponds to `uart0`, which uses D6 and D7 pins by default on Xiaos. When logging or Studio USB snippets are used, they turn on `CONFIG_SERIAL` and this prevents those pins from being used for other things, even though both use serial over USB. 
For RP2040 this is disabled in https://github.com/zmkfirmware/zmk/blob/main/app/boards/seeeduino_xiao_rp2040.overlay#L7, for Hummingbird shield this was disabled at the shield level but was (mistakenly?) removed in https://github.com/zmkfirmware/zmk/commit/e0339a2a57c33b86e351f31b04345ee8c984b075#diff-b0c154eb8d05802c1c61671a7e9e2ca6021c2ec81127f2c57194a84d7a85cdbfL57.
Is there a reason to not disable it by default for ZMK at the board level, like this? I can't think of any. Other boards like nice!nano don't set `status = …
> fix(boards): Disable uart serial node in Xiao BLE by default

- docs/docs/keymaps/behaviors/reset.md
> docs: Mention combos in reset behaviors

- docs/docs/development/hardware-integration/boards-shields-keymaps.md
- docs/docs/development/hardware-integration/index.md
- docs/docs/development/hardware-integration/index.mdx
- docs/docs/faq.md
- docs/docs/hardware.mdx
- docs/sidebars.js
This page https://zmk.dev/docs/development/hardware-integration/boards-shields-keymaps is a good explainer for both the high level concepts needed to define a ZMK keyboard, and also a decent overview for file/folder structure. However it contained some errors and was also outdated in some respects. 
~~I attempted to fix the issues, update and generalize it a little further. I think this page is a bit out-of-place as an explainer and can be refactored into other places later, but meanwhile it still seems valuable to keep.~~
~~*However*, I have an issue with the name and title of this page. "Boards, shields, and keymaps" does not seem descriptive of this overview/explainer but I am drawing a blank on a better name right now. Any suggestions welcome.~~
With Nick's suggestion, I converted …
> docs: Create a Hardware Integration index page

- app/Kconfig
- app/Kconfig.defaults
- app/module/drivers/sensor/ec11/Kconfig
- app/src/split/Kconfig
- app/src/split/Kconfig.defaults
- app/src/split/bluetooth/Kconfig
- app/src/split/bluetooth/Kconfig.defaults
- docs/docs/config/system.md
This is an alternative approach to #1886, with the same end goal. All of the "designer configurable" defaults are extracted out to separate files named `Kconfig.defaults`. The *definitions* stay in the same `Kconfig` file, only the defaults move. The defaults are imported after the keyboard config options, allowing them to be overridden by designers.
I used my own judgement to decide whether an option should be treated as "designer configurable". In general:
- Anything related to behaviors or how the keyboard would be *used* is a user config option and the designer has no business touching it
- Anything listed under our docs that isn't strictly a user config option is made available to designers
- ~~Specific additional options are made available to designers, such as USB vendor ID -- …
> refactor(Kconfig): Extracted designer defaults out into new files

- app/src/studio/keymap_subsystem.c
Ensure the set active physical layout RPC returns the full keymap details including the available layers.
> fix(studio): Properly return complete keymap from RPC

- app/dts/bindings/zmk,kscan-composite.yaml
- app/module/drivers/kscan/kscan_composite.c
- docs/docs/config/kscan.md
The kscan-composite driver does not respect the wakeup capabilities of its child kscans.
This branch fixes that by checking for their capabilities and whether the composite kscan is a wakeup source, before disabling them.
Relates to https://github.com/zmkfirmware/zmk/issues/2654 and https://github.com/zmkfirmware/zmk/pull/2673
> Fix: allow kscan-composite to wake up device.

- app/src/studio/behavior_subsystem.c
- app/src/studio/keymap_subsystem.c
The `arg` field on nanopb structs is a `void*` because it is shared between the encode and decode callbacks, even though the encode callback probably should not modify the data. We are passing const data using this non-const pointer, which causes warnings about discarding const. This commit explicitly casts to `void*` to suppress these warnings.
> fix: Fix warnings in nanopb encoding code

- app/dts/bindings/behaviors/zmk,behavior-key-toggle.yaml
- app/dts/bindings/behaviors/zmk,behavior-toggle-layer.yaml
- app/src/behaviors/behavior_key_toggle.c
- app/src/behaviors/behavior_toggle_layer.c
- app/tests/keytoggle/kt-off/events.patterns
- app/tests/keytoggle/kt-off/keycode_events.snapshot
- app/tests/keytoggle/kt-off/native_posix_64.keymap
- app/tests/keytoggle/kt-on/events.patterns
- app/tests/keytoggle/kt-on/keycode_events.snapshot
- app/tests/keytoggle/kt-on/native_posix_64.keymap
- app/tests/toggle-layer/behavior_keymap.dtsi
- app/tests/toggle-layer/early-key-release/native_posix_64.keymap
- app/tests/toggle-layer/toggle-mode-off/events.patterns
- app/tests/toggle-layer/toggle-mode-off/keycode_events.snapshot
- app/tests/toggle-layer/toggle-mode-off/native_posix_64.keymap
- app/tests/toggle-layer/toggle-mode-on/events.patterns
- app/tests/toggle-layer/toggle-mode-on/keycode_events.snapshot
- app/tests/toggle-layer/toggle-mode-on/native_posix_64.keymap
- docs/docs/config/behaviors.md
- docs/docs/keymaps/behaviors/key-toggle.md
- docs/docs/keymaps/behaviors/layers.md
Added `toggle-mode` flag to both the key toggle and toggle layer behaviors. Toggle mode can be set to
- "on"
- "off"
- "flip" (default when not present)
Tested locally with basic functionality. I don't see an edge case where this might cause issues.
Note that if key toggle on is spammed, it will repeatedly send over the "press" code. 
Resolves #2523.
> feat: Added `toggle-mode`, allowing toggle-on and toggle-off

- app/Kconfig
The refactor of 2537 didn't account for external module boards and shields. This fixes it by pulling in the relevant Kconfig bits from `kconfig.zephyr` a bit earlier. Results in some duplication of defaults, but acceptable duplication I'd say.
> fix: Kconfig refactor now works correctly with external modules

- .github/workflows/test.yml
- app/run-test.sh
This includes a few tweaks to `run-tests.sh`
- Properly deal with paths so the the script can be run from any working directory
- Add environment variables to set non-standard `ZMK_SRC_DIR` and `ZMK_BUILD_DIR` paths
- Add option to specify `ZMK_EXTRA_MODULES`
- Path arguments can be either absolute paths or relative to the current working directory. This applies to:
- location of script (e.g., `app/run-tests.sh` or `/workspace/zmk/app/run-tests.sh`)
- test path (e.g., `app/tests/gresc` or `/workspace/zmk/app/tests/gresc`, or even `gresc` if we are in `.../tests`)
- values of `ZMK_SRC_DIR`, `ZMK_BUILD_DIR` and `ZMK_EXTRA_MODULES`
---
Being able to run tests from anywhere in the workspace is mostly a quality-of-life improvement. The real application is to test modules without having to …
> Allow running tests from anywhere and support EXTRA_MODULES

- app/include/zmk/combos.h
- app/tests/pointing/mouse-move/processors/behaviors_hold_tap/native_posix_64.keymap
Handle the scenario where there is an empty combos block and return a zero combos length.
> fix(combos): Properly report combos len with emply block

- docs/docs/development/hardware-integration/dongle.mdx
- docs/docs/features/split-keyboards.md
- docs/sidebars.js
Added a page on configuring dongles, building on the work that @rasmuskoit did in #2401. The method recommended is personal to each user, but works for both boards and shield based keyboards (requires a board for the dongle, to avoid users messing with flash etc).
Subsumes #2401, closes #2044.
> docs: added a page on dongles

- app/src/studio/keymap_subsystem.c
Properly return the available layers in the move layer response.
> fix(studio): Allow adding layers after a layer move

- docs/docs/config/pointing.md
- docs/docs/development/hardware-integration/pointing.mdx
- docs/docs/keymaps/behaviors/mouse-emulation.md
- docs/docs/keymaps/input-processors/index.md
- docs/docs/keymaps/input-processors/transformer.md
A few miscellaneous tweaks to improve the newly added pointing-related docs:
- Add missing code fence languages
- Fix default `&msc` value in example
- Refactor hardware integration page so that tabs work fine
- This made me rewrite the page so that the headers follow a semantic structure, rather than going file by file. This way we can have proper headers that apply for both unibody/split use cases.
Last one was discussed in the 2477 PR review. Feedback welcome on the approach, though I feel this is the best way. (Unfortunately the diff is hard to follow due to many moved chunks, so you might want to review the final page.)
> docs: Improve pointing docs

- docs/docs/development/hardware-integration/dongle.mdx
Noticed these while working on #2704, I guess we overlooked it before the final merge.
> docs: Fix broken anchors in dongle page

- app/module/drivers/display/il0323.c
- app/module/drivers/gpio/gpio_595.c
- app/module/drivers/gpio/gpio_max7318.c
- app/module/drivers/input/input_mock.c
- app/module/drivers/kscan/kscan_gpio_charlieplex.c
- app/module/drivers/kscan/kscan_gpio_direct.c
- app/module/drivers/kscan/kscan_gpio_matrix.c
- app/module/drivers/sensor/ec11/ec11.c
- app/module/drivers/sensor/max17048/max17048.c
Save a tiny bit of RAM by properly marking our device config struct instances const consistently, and also add missing static modifiers to properly isolate config/data for drivers.
> fix(drivers): Proper static/const for data/config

- app/Kconfig
- app/include/zmk/physical_layouts.h
- app/src/physical_layouts.c
- app/src/studio/keymap_subsystem.c
- docs/docs/config/layout.md
To be able to save on flash space, for layouts on space constrained devices that don't require rotation, make key rotation props optional behind a new Kconfig flag.
> feat(core): Make physical layout key rotation optional

- app/include/zmk/keymap.h
- app/src/keymap.c
When building for ZMK Studio, we can use the constant stock keymap for init of the in-memory keymap, to avoid duplicate flash usage for the keymap from the devicetree.
> refactor(keymap): Reduce flash usage for studio builds

- docs/docs/intro.md
- docs/docs/intro.mdx
- docs/src/components/columns.tsx
- docs/src/css/custom.css
Attempt to update the intro page to docs, converting the comparison table to a feature/capabilities list. Then, split it into categories and add new items for in-progress work.
The last two are split into different commits, if you want to see intermediate states (but I'll squash them all into one before merging).
> docs: Update intro page

- app/module/drivers/kscan/kscan_gpio_charlieplex.c
`kscan_charlieplex_disconnect_all` is only used within a `CONFIG_PM_DEVICE` block, so if the firmware is built without the flag it spits out a warning.
> fix(kscan): Remove warning when charlieplex is built without CONFIG_PM_DEVICE

- app/src/display/Kconfig
- app/src/display/main.c
- app/src/main.c
- app/src/usb_hid.c
@caksoylar Can you test this there as well? These fixes were needed for me to get LVGL working properly on `native_posix_64` target here.
> Posix lvgl fixes

- app/boards/shields/lotus58/lotus58-layouts.dtsi
- app/boards/shields/lotus58/lotus58.dtsi
- app/boards/shields/lotus58/lotus58.zmk.yml
Added physical layout and studio support for Lotus58.
I've tested changes on my board with this [firmware](https://github.com/ralex2304/lotus58-zmk-config/actions/runs/12624124266) and studio in chrome.
Layout is based on existing zmk layout for Lily58.
> feat(shields): Add physical layout for Lotus58

- app/src/display/main.c
- docs/docs/config/displays.md
Zephyr is still working on the plan upstream for generically controlling display "backlight" pins with GPIO/PWM, so in the meantime, add our own chosen property `zmk,display-led` that is set to an LED device child to allow blanking/unblanking of devices that use a dedicated backlight control pin.
Basically looks like this in the devicetree:
```
/ {
chosen {
zephyr,display = &vik_st7789v;
zmk,display-led = &disp_led;
};
leds {
compatible = "gpio-leds";
disp_led: disp_led {
gpios = <&vik_conn 3 GPIO_ACTIVE_HIGH>;
label = "Display LED";
};
};
};
```
And then you need to enable the `CONFIG_LED=y` Kconfig flag to build that driver subsystem in.
> feat(display): Add ability to set display on/off pin.

- app/src/display/Kconfig
- app/src/display/main.c
- docs/docs/config/displays.md
Add `CONFIG_ZMK_DISPLAY_TICK_PERIOD_MS` Kconfig to allow tweaking the period between display updates.
> feat(display): Add config for display update period

- docs/docs/development/module-creation.md
- docs/sidebars.js
Added a page on module creation, much nicer this time.
This page makes use of another repository, `zmk-module-template`, which we should fork into the project if this approach is approved.
~~This page also makes reference to a second repository, `zmk-modules`. Work regarding `zmk-modules` is still in progress, but it is there to read and provide feedback on. If this is merged before `zmk-modules` is ready, then I suggest we comment out the parts on `zmk-modules` for the time being.~~
> feat(docs): Added a page on module creation

- docs/docs/development/hardware-integration/physical-layouts.md
Titles for improved clarity. Knowing that the tool can import KiCAD is a useful note.
> docs: Add KiCAD note and titles to physical layouts page

- docs/docs/development/hardware-integration/dongle.mdx
- docs/docs/development/hardware-integration/index.mdx
- docs/docs/development/hardware-integration/lighting/backlight.mdx
- docs/docs/development/hardware-integration/new-shield.mdx
- docs/docs/development/hardware-integration/pinctrl.mdx
- docs/docs/development/hardware-integration/pointing.mdx
- docs/docs/development/hardware-integration/soft-off-setup.mdx
- docs/docs/development/local-toolchain/build-flash.mdx
- docs/docs/development/local-toolchain/setup/container.mdx
- docs/docs/development/local-toolchain/setup/native.mdx
- docs/docs/development/usb-logging.mdx
- docs/docs/keymaps/behaviors/hold-tap.mdx
- docs/docs/keymaps/behaviors/tap-dance.mdx
- docs/docs/troubleshooting/hardware-issues.mdx
- docs/docs/user-setup.mdx
- docs/src/components/interconnect-tabs.tsx
Apparently docusaurus tabs support query strings, which lets you persist the selected tab to the URL: https://docusaurus.io/docs/markdown-features/tabs#query-string. I think this will be useful to share links to the docs where we can point to the right tab value, so I added it in most places that tabs are used -- skipped a few that didn't seem necessary.
Note: when value of `queryString` is skipped it falls back to using `groupId`, so I preferred that whenever the latter exists.
> docs: Add query strings to tabs

- app/src/behaviors/behavior_sticky_key.c
- app/tests/sticky-keys/12-macro/events.patterns
- app/tests/sticky-keys/12-macro/keycode_events.snapshot
- app/tests/sticky-keys/12-macro/native_posix_64.keymap
- app/tests/sticky-keys/12-same-position-mods/events.patterns
- app/tests/sticky-keys/12-same-position-mods/keycode_events.snapshot
- app/tests/sticky-keys/12-same-position-mods/native_posix_64.keymap
- app/tests/sticky-keys/12-same-position-sk-sl/events.patterns
- app/tests/sticky-keys/12-same-position-sk-sl/keycode_events.snapshot
- app/tests/sticky-keys/12-same-position-sk-sl/native_posix_64.keymap
Sticky keys have logic implemented so that if you press the same sticky key a second time, it releases the first press before activating a sticky key press again. However, multiple sticky keys are only disambiguated by key position, which means that you currently cannot have active multiple sticky keys that are triggered from the same key position. This scenario occurs under a couple conditions:
- You activate a sticky key (e.g. `&sk LCTRL`), then activate a different sticky key e.g. (`&sk LSHIFT`) on a different layer but at the same key position
- You activate multiple sticky keys on a macro invocation (e.g. with `bindings = <&sk LSHIFT>, <&sl 1>;`)
Using only the key position is usually enough to disambiguate multiple active instances of a behavior; for instance for hold-taps, you …
> fix(behaviors): Make multiple sticky keys work on same key position

- app/src/behaviors/behavior_backlight.c
- app/src/behaviors/behavior_bt.c
- app/src/behaviors/behavior_ext_power.c
- app/src/behaviors/behavior_key_press.c
- app/src/behaviors/behavior_key_repeat.c
- app/src/behaviors/behavior_key_toggle.c
- app/src/behaviors/behavior_mod_morph.c
- app/src/behaviors/behavior_momentary_layer.c
- app/src/behaviors/behavior_mouse_key_press.c
- app/src/behaviors/behavior_none.c
- app/src/behaviors/behavior_outputs.c
- app/src/behaviors/behavior_reset.c
- app/src/behaviors/behavior_rgb_underglow.c
- app/src/behaviors/behavior_sensor_rotate.c
- app/src/behaviors/behavior_sensor_rotate_var.c
- app/src/behaviors/behavior_soft_off.c
- app/src/behaviors/behavior_studio_unlock.c
- app/src/behaviors/behavior_to_layer.c
- app/src/behaviors/behavior_toggle_layer.c
- app/src/behaviors/behavior_transparent.c
- docs/docs/development/new-behavior.mdx
Initialization functions are optional for Zephyr drivers, so remove all our superfluous empty init functions.
Good call out from @Nick-Munnich on #2842
> refactor(behaviors): Remove unneeded init funcs.

- app/src/behaviors/behavior_caps_word.c
- app/src/behaviors/behavior_key_repeat.c
Properly generate the comma separated list of devs in caps word/ key repeat.
> fix(behaviors): Proper comma separated device list

- app/boards/shields/tester_pro_micro/tester_pro_micro-layouts.dtsi
- app/boards/shields/tester_pro_micro/tester_pro_micro.overlay
- app/boards/shields/tester_xiao/tester_xiao-layouts.dtsi
- app/boards/shields/tester_xiao/tester_xiao.overlay
> feat(shields): Add physical layouts for tester_xiao and tester_pro_micro

- docs/docs/config/kscan.md
Move the property from child nodes table to the node itself to fix docs bug. Also clarify that the property needs to be set both for child kscan(s) and the composite itself.
Originally came up in [Discord](https://discord.com/channels/719497620560543766/719909884769992755/1346746447122530304).
> docs: Fix wakeup-source property location for composite kscan

- .github/workflows/build.yml
Ideally it's be swapped out for an alternative but for now this is to mitigate running known compromised code.
Or, y'all can locally clone the Action's repo from the hash that's been pinned and push it as a mirror to the zmkfirmware org to be more safe for now?
Additionally, automerge and PR creation of updates for this action should be disabled for now to prevent accidental updates to the latest hash.
https://github.com/tj-actions/changed-files/issues/2463
https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
(Forked, edited and PRed from GitHub Mobile app to make it quick so none of the below have been done, hope y'all don't mind for a simple change)
> fix(build.yaml): pin tj-actions/changed-files action due to compromise

- app/CMakeLists.txt
Don't add the split CMake subdirectory unless the feature is enabled.
> fix(split): Conditionally build all split code

- docs/docs/keymaps/input-processors/index.md
Filling in the missing entries (scaler, temp-layer) in the list for correctness.
> docs: Document missing user-defined input processors

- app/src/split/central.c
147c340 introduces a bug where the peripheral battery level is always reported with index 0. This should not be the case if there are more than one peripherals.
> fix(split): add source to battery event

- docs/docs/development/module-creation.md
The folder for boards and shields is `boards`, not `board`.
> docs: fix path typo in module-creation.md

- app/run-ble-test.sh
- docs/src/templates/setup.sh.mustache
See for example [this thread](https://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash) on why its better to use `#!/usr/bin/env bash` instead of `#!/bin/bash`. Without this change these scripts will not run on some platforms. This is not a breaking change for the platforms it already currently works on.
> fix: changed shebang to make scripts more platform independent

- .vscode/extensions.json
- .vscode/settings.json
Removed the deprecated `python.formatting.provider` setting and switched to using correct extension for formatting Python files now that different formatters have been broken out into separate extensions.
Limited Python analysis to only the directories containing Python scripts, so VS Code doesn't slow down while scanning all of Zephyr.
> Improve VS Code Python settings

- app/src/split/bluetooth/central.c
The previous code prints one line per byte, making debugging difficult.
> refactor(split): use LOG_HEXDUMP_DBG() to print position state data

- docs/src/pages/index.js
Img alt text on the home page was shown as alt="[object Object]"
since title was a react node and not text
This PR fixes that
> fix(docs): docs home img alt text

- app/Kconfig
- app/dts/bindings/zmk,combos.yaml
- app/src/combo.c
- docs/docs/config/combos.md
Keeping this draft for now, but this is a collection of improvements to remove a few combo Kconfig flags that are instead auto-calculated at build time, and reduce the RAM usage on more constrained devices.
A Le Chiffre STM32 Build on `main`:
```
[198/198] Linking C executable zephyr/zmk.elf
Memory region         Used Size  Region Size  %age Used
FLASH:       42636 B       128 KB     32.53%
RAM:        8120 B        15 KB     52.86%
RetainedMem:          0 GB          1 B      0.00%
IDT_LIST:          0 GB         2 KB      0.00%
```
Same keymap with this PR:
```
❯ west build -d build/lc_stm32_tap_dance
[7/7] Linking C executable zephyr/zmk.elf
Memory region         Used Size  Region Size  %age Used
FLASH:       42732 B       128 KB     32.60%
RAM:        7736 B        15 KB     50.36% …
```
> Combo RAM and Kconfig reduction 

- app/Kconfig
Restore prompts for deprecated combo Kconfig symbols, to avoid errors for existing builds that set them explicitly.
> fix(combos): Restore prompts for two deprecated Kconfigs

- docs/src/data/hid.js
This PR is simply to add the information for the alternate or secondary function of the keypad number keys used in the List of Keycodes docs page.  
With the current state of the docs, I was not aware that those keycodes will only serve as numbers when the Numlock is enabled.
> docs: Add secondary functions for the keypad number keys

- app/boards/shields/reviung5/boards/nice_nano_v2.overlay
- app/boards/shields/reviung5/reviung5.conf
- app/boards/shields/reviung5/reviung5.keymap
- app/boards/shields/reviung5/reviung5.zmk.yml
Adds underglow for the reviung5. Was just copying and adapting stuff from other reviungs. And created battery optimized keymap by toggling ext power off instead of just switching RGB on and off.
Looks nice :-D
> feat(underglow): add underglow for reviung5

- docs/docs/keymaps/behaviors/hold-tap.mdx
I assumed that `&lt` had the same default flavor as `&mt` and didn't see anything mentioned differently in the docs, but I recently learned it defaults to `tap-preferred`:
https://github.com/zmkfirmware/zmk/blob/ad6a181d7ec34fb6e31134f6bb991a9b2d0b8f78/app/dts/behaviors/layer_tap.dtsi#L17
This PR updates the documentation for `&lt` to describe that!
> docs: Document the default flavor of layer-tap

- app/src/pointing/input_processor_temp_layer.c
Temp layer freezes by mutex leak if layer state change event happens for default layer.
> fix(pointing): Avoids mutex leak for default layer toggle event

- .pre-commit-config.yaml
- docs/docs/development/hardware-integration/dongle.mdx
- docs/src/components/hardware-list.tsx
- docs/src/components/interconnect-tabs.tsx
- docs/src/css/power-estimate.css
- docs/src/css/power-profiler.css
- docs/src/keymap-upgrade/textedit.ts
Clean up lingering prettier warnings. These are causing failures in our zmk-docker worflows, which check that prettier runs properly. See https://github.com/zmkfirmware/zmk-docker/actions/runs/15376917506/job/43263738558?pr=168
> chore(docs): Fix prettier warnings

- app/include/zmk/ble.h
- app/src/ble.c
This PR adds a `bt_addr_le_t *zmk_ble_profile_address(uint8_t index)` function to get a profile address by index. 
This is the smallest (and hopefully most likely to be merged?) core change I could find to allow #2265 to be implemented in an module.
> feat(ble): Add function to get profile address by index

- app/include/zmk/ble.h
- app/src/ble.c
This PR implements `zmk_ble_active_profile_is_open()` and `zmk_ble_active_profile_is_connected()` in terms of newly introduced `zmk_ble_profile_is_open(addr)` and `zmk_ble_profile_is_connected(addr)`
> refactor(ble): add functions to check if profile is open/connected by address

- docs/.prettierignore
- docs/docs/development/local-toolchain/setup/native.mdx
- docs/docs/features/studio.md
- Fixes #2951. I assume this is required for other OS as well and not just Windows, but if anyone confirms it isn't then we can remove. It currently seems fine to me to recommend installing nevertheless.
- Fixes #2645.
- ~~Reformats the native toolchain setup file so that paragraphs and othes elements within a list item are properly indented.~~ Reverted, can't figure out how to get the pre-commit workflow to ignore the file as well.
Before:
After:
~~This required disabling prettier on the file, since it wanted to clobber all the indents and I don't think there is a way to add a range ignore in mdx files. I can drop the commit, but I don't think it's worth for me to spend more time trying to make prettier happy.~~
> docs: Document requirements-extra.txt and endpoint selection for Studio

- app/boards/arm/mikoto/Kconfig
- app/boards/arm/nice_nano/Kconfig
Given a typical setup of a battery at ~4 V and a nice!nano v2 running at 3.3 V, I measured a small increase in power usage (using a Nordic PPK2) when SOC_DCDC_NRF52X_HV was enabled. This changes the nice_nano_v2 and mikoto boards so this option is disabled by default.
Fixes #2990
> Disable high voltage DC-DC by default

- .github/workflows/stale.yml
Add a GitHub Action to automatically close stale PRs. This can be adapted to close stale issues too, but I think we should focus on PRs first and then make a followup to close issues once PRs have gotten more under control.
The action was adapted from [netlify/build](https://github.com/netlify/build/blob/main/.github/workflows/stalebot.yml) (MIT licensed) where it is functioning as expected, but for [issues](https://github.com/netlify/build/issues/5299). Documentation on the action can be found [here](https://github.com/actions/stale).
> feat(ci): Add stale GitHub Action to automatically close stale PRs

- app/boards/shields/nice_view/README.md
- app/boards/shields/nice_view/widgets/status.c
- app/boards/shields/nice_view/widgets/util.h
Allow the nice!view widget to display the status of each profile by:
- not adding a circle around the number if the profile is not bound
- drawing a dashed circle around the number if a profile is bound but not connected (device not live, explicitly disconnected with `BT_DISC`, ...)
Example:
- solid circle: connected
- dashed circle: not connected
- no circle: not bound
- filled circle: selected
---
This requires minor refactoring in BLE code to expose state methods by profile address rather than only by the current profile.
One issue I can see so far is that event's are indeed raised when the current profile changes but not when other profiles change from what I can tell (eg. a device other that the selected one disconnects).
I have tried addressing the `BT_DISC` case by adding a …
> nice!view: individual profile status

- app/src/behaviors/behavior_macro.c
- app/tests/macros/param-then-no-param/events.patterns
- app/tests/macros/param-then-no-param/keycode_events.snapshot
- app/tests/macros/param-then-no-param/native_posix_64.keymap
This PR adds a test for a macro bug where parameter passing isn't working correctly after `&macro_pause_for_release`, and proposes a fix.
The root cause seems to be that when pre-computing release state in `behavior_macro_init`, the parameter passing logic of the on-press portion is only partially taken into account. That is, control bindings like `&macro_param_1to1` are properly consumed (through the `handle_control_binding` calls) but whether the parameters are then used by a non-control behavior isn't considered: the release state precomputation does not replicate the resetting of `param*_source` variables that happens within `replace_params` during the on-press portion of the bindings. So the fix is to do this reset whenever a non-control behavior is encountered, emulating the …
> fix(behaviors): Correct macro release state for parametrized macros

- app/src/split/Kconfig
- docs/docs/config/split.md
Remove the previous condition on ZMK_SPLIT_WIRED that only enabled it if !ZMK_BLE. We'll defer to the `depends on` to ensure the DTS exists to use wired split to make that decision on enabling the feature.
> fix(split): Enable wired split by default if DTS is set

- .github/workflows/ble-test.yml
- .github/workflows/build-user-config.yml
- .github/workflows/build.yml
- .github/workflows/test.yml
This PR contains two performance tweaks for the GHA build workflow:
1. Use [treeless clones](https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/) when pulling in dependencies. This reduces the download size from 1.7 GB to 610 MB. 
2. Replace `yaml2json | jq` with `yq`. This saves the installation step shaving off a few more seconds.
The following table summarizes the performance impact for building a `reviung41` with the stock config on ZMK `v0.1`.
|     | cold cache | warm cache | cache size |
| --- | --- | --- | --- |
|upstream    | 5m 28s | 2m 02s | 1.7 GB |
|treeless PR | 3m 51s | 1m 45s | 610 MB |
(See https://github.com/urob/zmk-build-benchmarks/actions for the benchmarks.)
The dependency change is most impactful on cold caches. As Github caches …
> Optimize build workflow

- docs/docs/config/index.md
- docs/docs/development/devicetree.md
- docs/sidebars.js
Adds a devicetree primer to the development section. I feel this would be useful to have for more advanced users.
> docs: Add devicetree primer

- docs/blog/2023-10-05-zmk-sotf-6.md
- docs/docs/config/settings.md
- docs/docs/config/system.md
- docs/docs/customization.md
- docs/docs/development/hardware-integration/soft-off-setup.mdx
- docs/docs/features/split-keyboards.md
- docs/docs/keymaps/behaviors/backlight.md
- docs/docs/keymaps/behaviors/bluetooth.md
- docs/docs/keymaps/behaviors/outputs.md
- docs/docs/keymaps/behaviors/power.md
- docs/docs/keymaps/behaviors/underglow.md
- docs/docs/troubleshooting/connection-issues.mdx
- docs/docs/user-setup.mdx
- Add a few more tweaks related to settings clearing, like adding a warning for splits, adding more links to the new page, changing admonition type for keyboard name
- Slightly clean up split troubleshooting procedure, generalize language for >2 parts
- As a bonus, fix a broken anchor due to the new devicetree page changes
> docs: Add warning box for clearing settings for splits, generalize troubleshooting procedure

- app/include/zmk/keymap.h
- app/src/keymap.c
Properly account for studio and non-studio builds for the generation of the layer names stored within the keymap system.
Fixes #3045
> fix(core): Generate correct keymap layer names for all builds
