- CODE_OF_CONDUCT.md
- README.md
- docs/docs/intro.md
> Initial code of conduct documentation.

- docs/sidebars.js
> Replaced 'Basics' with 'Getting Started'

- docs/docs/faq.md
- docs/sidebars.js
> docs: FAQs (initial version)

- app/west.yml
> Upgrade to Zephyr 2.3.0 (plus small build fix.)

- .github/workflows/build.yml
- app/boards/shields/lily58/Kconfig.defconfig
- app/boards/shields/lily58/Kconfig.shield
- app/boards/shields/lily58/keymap/keymap.overlay
- app/boards/shields/lily58/lily58.dtsi
- app/boards/shields/lily58/lily58_left.overlay
- app/boards/shields/lily58/lily58_right.overlay
Initial stab at a Lily58 shield definition.
> Initial Lily58 shield definition.

- docs/docs/dev-boards-shields-keymaps.md
- docs/docs/dev-guide-new-shield.md
- docs/docs/dev-posix-board.md
- docs/docs/dev-setup.md
- docs/docs/user-setup.md
Tiny PR with some doc updates.
Mainly, just to add a note to make sure the user sets up the current shell correctly. I followed the full instructions and everything worked fine on Ubuntu 20.04, the only missing step to me was the missing note of "You need to setup the current shell if you want to continue".
Did a quick pass with the spell checker as well whilst I was there.
Going to try and get a board added after this, now that I know it builds correctly for me, though will probably leave a PR until I can test on a board.
> Quick doc update.

- docs/docusaurus.config.js
Should make it easier for others to make changes to the docs now.
> Fix edit url links for the website.

- .github/workflows/build.yml
- app/west.yml
Brings the cache size from 790MB down to 615MB. Should help speed up builds some.
> fix(build): Remove more unused west modules.

- app/boards/shields/corne/corne.keymap
This still needs some work but it is much improved from the original.
> Working on corne default keymap

- app/Kconfig
- app/cmake/zmk_config.cmake
> fix(shields): Load Kconfig for out-of-tree shields

- .github/workflows/build.yml
- app/boards/shields/romac/Kconfig.defconfig
- app/boards/shields/romac/Kconfig.shield
- app/boards/shields/romac/romac.keymap
- app/boards/shields/romac/romac.overlay
Fix license typo (sorry Pete)
Remove transform matrix as it's the default behaviour anyway
> Romac cleanup

- .github/workflows/test.yml
@BrainWart - Care to give a look?
> feat(test): Add GH Action for tests.

- app/src/keymap.c
This fixes #125 for me. The only shortfall I can see is that it doesn't drop through the layers any more for key release. If a key is transparent, it can only expect to receive a keypress event. I can't think of any uses for transparent keys at the moment.
To test the broken behavior:
key down A -> momentary/toggle a layer -> key up A
A will now be stuck pressed until pressed and released again.
Fixed:
key down A -> momentary/toggle a layer -> key up A
A is correctly released despite the layer change
> Fix keys not releasing when layers change

- docs/docs/behavior/hold-tap.md
- docs/docs/behavior/layers.md
- docs/docs/intro.md
Update the intro page with links into the docs, added layer-tap docs and improved the hold-tap docs slightly.
> update intro page, add layer-tap docs and update hold-tap docs.

- CONTRIBUTING.md
> Initial CONTRIBUTING.md file

- docs/blog/2020-09-21-zmk-sotf-2.md
- Closes #182
Deploy preview: https://deploy-preview-196--zmk.netlify.app/blog/2020/09/21/zmk-sotf-2
> Blog - State of the firmware #2

- app/include/zmk/usb_hid.h
- app/src/usb_hid.c
* To be leveraged by upcoming power
management work.
> Add API to access current USB status

- app/include/dt-bindings/zmk/keys.h
- app/include/dt-bindings/zmk/kscan-mock.h
- app/include/dt-bindings/zmk/matrix-transform.h
- app/include/dt-bindings/zmk/rgb.h
- app/include/zmk/split/bluetooth/service.h
- app/include/zmk/split/bluetooth/uuid.h
> Add missing licensing header

- app/drivers/zephyr/kscan_gpio_matrix.c
Fixes #266 
Seems like some refactoring from a7496ab06425cab7de5fc7164b4ce5a34dd7107b and 9be566603e2eb248fbaa7af65cba42d5c06dbd33 caused the issue.
> Fix matrix polling conditional macro

- docs/docs/user-setup.md
Added documentation in `Installing ZMK` in a new column named `PowerShell` with the script for installing ZMK in PowerShell.
> Issue #210 Document Setup.ps 

- docs/docs/customization.md
Ignore all references to Issue #138 from PR #257. This is the proper pull request addressing everything to do with ZMK config folders, built upon the work of @chenkevinh.
> Addressing #138 - ZMK Config Folders

- docs/docs/intro.md
From issue #179 Still need to decide what goes in the top-left most box because feature is already used as the header. Also need to come up with a sentence to go above the table that relates to the table featuring zmk and qmk. More features could also be added but this is a good start.
> Added Feature Matrix for Intro.md

- docs/blog/2020-05-24-wip.md
- docs/docs/dev-guide-new-shield.md
- docs/docs/intro.md
- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
Prerequisite of #218.  Closes #286.
> chore(docs): Docusaurus 2.0.0 alpha.65

- docs/docs/troubleshooting.md
Adds documentation for changing the config values of TX power in the `shield.conf` file. Being able to change this value helps some users with poor connection.
> DocumentedTX Power Config in Troubleshooting

- docs/package.json
Add:
- docusaurus serve
- docusaurus clear
> docs: Add missing docusaurus scripts

- .github/workflows/build.yml
- app/boards/shields/reviung41/Kconfig.defconfig
- app/boards/shields/reviung41/Kconfig.shield
- app/boards/shields/reviung41/boards/nice_nano.overlay
- app/boards/shields/reviung41/reviung41.conf
- app/boards/shields/reviung41/reviung41.keymap
- app/boards/shields/reviung41/reviung41.overlay
- docs/docs/hardware.md
- docs/static/setup.ps1
- docs/static/setup.sh
Add definitions for Reviung41 shield from Japan, and it's available in the US from a few vendors including Little Keyboards and Boardsource.xyz.
The board is open source and can be found here: https://github.com/gtips/reviung/tree/master/reviung41
> Add Reviung41 Shield Definitions

- docs/docs/behavior/outputs.md
> docs(outputs): run prettier on outputs.md

- app/boards/arm/bluemicro840/bluemicro840_v1.dts
- app/boards/arm/nice_nano/nice_nano.dts
- app/boards/arm/nrf52840_m2/nrf52840_m2.dts
- app/boards/arm/nrfmicro/nrfmicro_11.dts
- app/boards/arm/nrfmicro/nrfmicro_11_flipped.dts
- app/boards/arm/nrfmicro/nrfmicro_13.dts
Closes #315 🎉 
We lose around 50KB of code space with this change, but I think that's a fine tradeoff!
> fix(boards): Remap flash to account for bootloader

- .github/workflows/doc-checks.yml
- docs/package.json
Adds Prettier and ESLint checks to our docs.
> feat(docs): Add eslint and prettier GH Actions.

- docs/blog/2020-10-03-bootloader-fix.md
Explains the issue, diagnosis, and fix from #322.
> Add blog post about #322

- app/src/rgb_underglow.c
This adds debounce functionality of one minute to the settings save function. This will greatly reduce how often settings are saved when adjusting hue, saturation, brightness, and effects, which will ultimately reduce flash wear.
> feat(underglow): Debounce state settings save to reduce flash wear

- app/include/zmk/hid.h
This should've changed alongside: 711658206f86fc6af35be7d104243dfcf857f194
> refactor(hid): Replace `0x01` with `HID_USAGE_CONSUMER_CONSUMER_CONTROL`

- docs/docs/codes/_keyboard-keypad.mdx
- docs/docs/codes/modifiers.mdx
- docs/docs/dev-guide-new-shield.md
- docs/docs/feature/keymaps.md
- docs/sidebars.js
- docs/src/data/hid.js
Refactor and expand codes documentation to include modifier functions.
Closes #330.
> docs(codes): add modifier functions

- docs/docs/codes/modifiers.mdx
Some improvements on the modifier docs.
> docs: update modifier docs

- app/boards/shields/qaz/qaz.keymap
Looking to use the QAZ shield for an upcoming meetup dem, and think some whitespace formatting tweaks helps it helps it be more readable for the demo.
> QAZ shield keymap formatting tweaks.

- app/dts/behaviors/bluetooth.dtsi
- app/dts/behaviors/ext_power.dtsi
- app/dts/behaviors/key_press.dtsi
- app/dts/behaviors/layer_tap.dtsi
- app/dts/behaviors/mod_tap.dtsi
- app/dts/behaviors/momentary_layer.dtsi
- app/dts/behaviors/none.dtsi
- app/dts/behaviors/outputs.dtsi
- app/dts/behaviors/reset.dtsi
- app/dts/behaviors/rgb_underglow.dtsi
- app/dts/behaviors/sensor_rotate_key_press.dtsi
- app/dts/behaviors/transparent.dtsi
as discussed in https://github.com/zmkfirmware/zmk/pull/284
> add license headers to behavior dtsi files

- docs/sidebars.js
> docs: Rename `someSidebar` to `docs`

- docs/docs/behaviors/hold-tap.md
> docs(hold-tap): Capitalize hold-tap behavior document title

- app/include/zmk/hid.h
Improves readability of the HID reports.
> refactor(hid): Replace modifier usage values with their preprocessor definitions

- app/run-test.sh
example: `west test tests/hold-tap` will run all hold-tap tests.
> feat(tests): run subdirectory of tests

- README.md
- docs/docs/behaviors/mod-tap.md
Updates the mod-tap docs to be correct and explain about the relation between mod-tap and hold-tap.
Updates the README.md with more links to the docs and more confident language.
> docs: Update modtap docs and README.md

- app/src/rgb_underglow.c
> fix(ug): Start tick without settings state available

- app/src/ext_power_generic.c
- app/src/main.c
This PR adds settings support to external power.
> feat: Add external power settings

- .github/workflows/build.yml
- .github/workflows/clang-format-lint.yml
- .github/workflows/doc-checks.yml
- .github/workflows/test.yml
For each workflow, add its path to its own trigger conditions so that it automatically re-triggers for testing purposes whenever it is changed.
> build(workflows): add each workflow to its own trigger conditions

- app/Kconfig
- app/src/ext_power_generic.c
- app/src/rgb_underglow.c
> refactor(settings): Add Kconfig option for settings debounce

- .github/workflows/build.yml
Lays the groundwork for further improvements.
> ci(build): sort boards and shields alphabetically

- app/include/zmk/display.h
- app/src/ble.c
- app/src/display/main.c
- app/src/display/widgets/output_status.c
- app/src/main.c
* Make sure all LVGL access is from main work thread.
> A few core display stability fixes.

- .devcontainer/devcontainer.json
Reorder the file so that related properties are roughly grouped together and the order is more logical.
> refactor(devcontainer): reorder properties

- .github/workflows/build.yml
- app/boards/shields/crbn/Kconfig.defconfig
- app/boards/shields/crbn/Kconfig.shield
- app/boards/shields/crbn/crbn.keymap
- app/boards/shields/crbn/crbn.overlay
- app/boards/shields/crbn/readme.md
- docs/docs/hardware.md
- docs/static/setup.ps1
- docs/static/setup.sh
CRBN keymap is identical to planck qmk keymap but for the addition of some Bluetooth stuff
Following advice from innovaker planck keymap will be in a separate pr
> add CRBN shield

- app/boards/arm/dz60rgb/dz60rgb_rev1.keymap
- app/boards/arm/planck/planck_rev6.keymap
- app/boards/shields/boardsource3x4/boardsource3x4.keymap
- app/boards/shields/clueboard_california/clueboard_california.keymap
- app/boards/shields/corne/corne.keymap
- app/boards/shields/cradio/cradio.keymap
- app/boards/shields/iris/iris.keymap
- app/boards/shields/jian/jian.keymap
- app/boards/shields/jorne/jorne.keymap
- app/boards/shields/kyria/kyria.keymap
- app/boards/shields/lily58/lily58.keymap
- app/boards/shields/m60/m60.keymap
- app/boards/shields/microdox/microdox.keymap
- app/boards/shields/nibble/nibble.keymap
- app/boards/shields/qaz/qaz.keymap
- app/boards/shields/quefrency/quefrency.keymap
- app/boards/shields/reviung41/reviung41.keymap
- app/boards/shields/romac/romac.keymap
- app/boards/shields/romac_plus/romac_plus.keymap
- app/boards/shields/sofle/sofle.keymap
- app/boards/shields/splitreus62/splitreus62.keymap
- app/boards/shields/tg4x/tg4x.keymap
Ran all the default keymaps through the keymap upgrader and manually adjusted alignment.
> improvement: upgrade default keymaps

- .devcontainer/devcontainer.json
Caches VS Code extensions and other profile settings between zmk containers.
Based on advice from KemoNine.
> feat(devcontainer): add volume mount for root user

- .github/workflows/build.yml
- .github/workflows/test.yml
Improves readability and informativeness.
> ci: improve step names

- app/include/zmk/display/status_screen.h
- app/src/display/status_screen.c
I wasn't sure if this was intentional or not?
> chore(display): align status_screen copyright

- app/boards/arm/nrf52840_m2/nrf52840_m2.dts
- app/boards/shields/jorne/jorne.dtsi
- app/boards/shields/jorne/jorne_left.overlay
- app/boards/shields/jorne/jorne_right.overlay
Changes made with regex plus some manual tweaks.  See commit description for more detail.
> chore: standardize C style headers

- docs/docs/intro.md
Updating 4 in progress features to complete! Low power sleep states, VCC shutoff, battery reporting, and one-shot keys. Also removed OLED from display support, as it's not specific to OLEDs.
> docs(intro): Update feature table

- app/boards/shields/tg4x/Kconfig.defconfig
- app/boards/shields/tg4x/Kconfig.shield
- app/boards/shields/tg4x/README.md
- app/boards/shields/tg4x/boards/nice_nano.conf
- app/boards/shields/tg4x/boards/nice_nano.overlay
- app/boards/shields/tg4x/tg4x.conf
- app/boards/shields/tg4x/tg4x.keymap
- app/boards/shields/tg4x/tg4x.overlay
Various fixes / cleanup
* compile warnings
* keymaps updated to match upstream
* add readme
* add underglow
> (fix) tg4x Misc (See desc)

- docs/static/setup.sh
Corrects BF0 (zero) with BFO.
Refs: dcd665999a5ee04372559d56fc22b9a2d0784bf2
> fix(setup.sh): rename BF0-9000 to BFO-9000

- app/boards/arm/bluemicro840/bluemicro840_v1.dts
- app/boards/arm/nice_nano/nice_nano.dts
- app/boards/arm/nrf52840_m2/nrf52840_m2.dts
- app/boards/arm/nrfmicro/nrfmicro_11.dts
- app/boards/arm/nrfmicro/nrfmicro_11_flipped.dts
- app/boards/arm/nrfmicro/nrfmicro_13.dts
* Set pro-micro TX/RX pins, but don't enable the UART
by default.
> Clean up uart0 devicetree, don't enable by default

- app/dts/bindings/behaviors/one_param.yaml
- app/dts/bindings/behaviors/two_param.yaml
- app/dts/bindings/behaviors/zero_param.yaml
- app/dts/bindings/behaviors/zmk,behavior-bluetooth.yaml
- app/dts/bindings/behaviors/zmk,behavior-key-press.yaml
- app/dts/bindings/behaviors/zmk,behavior-momentary-layer.yaml
- app/dts/bindings/behaviors/zmk,behavior-none.yaml
- app/dts/bindings/behaviors/zmk,behavior-reset.yaml
- app/dts/bindings/behaviors/zmk,behavior-transparent.yaml
- app/dts/common/arduino_uno_pro_micro_map.dtsi
Does not include boards and shields.
Should these also be done?
> chore(core): replace `Pete Johanson` with `The ZMK Contributors`

- docs/docs/behaviors/hold-tap.md
Improves readability and consistency.
> docs(hold-tap): mark tapping_term_ms as code

- docs/docs/behaviors/sticky-key.md
- docs/docs/behaviors/sticky-layer.md
- docs/sidebars.js
fixes #439, missing sticky keys and sticky layers documentation
> docs(sticky keys): document sticky keys and sticky layers

- docs/blog/2021-01-27-zmk-sotf-4.md
Initial draft, to start getting eyes on this. Several sections fully missing details, a few needing updated links to the relevant PRs, etc.
@innovaker @Nicell @okke-formsma @joelspadin Any thing I've missed?
> State Of The Firmware #4

- docs/docs/behaviors/bluetooth.md
This behavior was not obvious to me, and I actually considered reporting it as a bug until @Nicell explained to me on Discord that it's WAI. :)
> docs: Explain ZMK stays connected to inactive host 

- docs/docs/intro.md
Added a few more green checks that map out to some of the new features added to BlueMicro_BLE.
> Update to BlueMicro_BLE Features

- app/src/display/main.c
> Fix fault on idle if displays not available.

- app/src/event_manager.c
Gets rid of two levels of nesting by some trivial reordering.
> refactor(core): make the event manager a bit easier to read

- docs/docs/behaviors/mod-morph.md
- docs/sidebars.js
This is my first pull request and my first time writing documentation so let me know if there's any problems or anything I wrote is unclear.
Created in reference to issue #651
> Docs: added mod morph page

- docs/docs/intro.md
- docs/package-lock.json
- docs/package.json
- docs/src/components/codes/Description.jsx
- docs/src/pages/power-profiler.js
* Bump to prettier 2.3.1.
* Re-run prettier:format to apply updated format.
> chore(docs): Bump prettier, and reformat w/ it.

- docs/docs/features/encoders.md
- docs/src/pages/power-profiler.js
Fixed code formatting in a few docs files.
> fix(docs): Appease Prettier

- CONTRIBUTING.md
> fix: basic setup link

- docs/src/templates/setup.ps1.mustache
* `Get-Acl` not found in Linux Powershell version, so only call it
if it exists.
> fix(setup): Fix setup.ps1 to check Get-Acl  exists

- docs/docs/features/encoders.md
> fix(docs): Typo EC11_CONFIG

- app/Kconfig
- app/include/zmk/hid.h
- app/src/hid.c
* Add Kconfig settings for NKRO or HKRO (boot compatible), HID
report types for keyboard page.
* Updated report storage and set/unset for each config.
> feat(hid): Configurable NKRO HID report support.

- app/boards/shields/reviung41/reviung41.keymap
Notice some keycodes are not matched with the expected keys.
> Fix some keycodes in reviung41 keymap

- app/boards/shields/chalice/Kconfig.defconfig
- app/boards/shields/chalice/Kconfig.shield
- app/boards/shields/chalice/boards/nice_nano.overlay
- app/boards/shields/chalice/boards/nice_nano_v2.overlay
- app/boards/shields/chalice/chalice.conf
- app/boards/shields/chalice/chalice.keymap
- app/boards/shields/chalice/chalice.overlay
- app/boards/shields/chalice/chalice.zmk.yml
Adding support for [Chalice](https://customkbd.com/products/chalice-pre-order).
This is my first ZMK PR so apologies for any issues and thanks in advance :)
> feat(shield) Add Chalice support

- .github/pull_request_template.md
* Kconfig.defconfig conditional correctness.
* Keyboard availability.
> chore: Add a few more items to PR template.

- docs/docs/behaviors/hold-tap.md
> Update documentation syntax for quick tap

- docs/docs/development/build-flash.md
Updating docs, per discussion on https://discordapp.com/channels/719497620560543766/719909884769992755/913258608983166996
> Fix docs for west command for custom config repo

- app/boards/shields/knob_goblin/Kconfig.defconfig
- app/boards/shields/knob_goblin/Kconfig.shield
- app/boards/shields/knob_goblin/knob_goblin.conf
- app/boards/shields/knob_goblin/knob_goblin.keymap
- app/boards/shields/knob_goblin/knob_goblin.overlay
- app/boards/shields/knob_goblin/knob_goblin.zmk.yml
> Add support for Knob Goblin shield

- docs/docs/customization.md
Added a small documentation section on building additional board and shields with action workflow.
> Add guide to build additional keyboards with GH Action

- docs/blog/2022-03-08-zephyr-3-0-upgrade-prep.md
Prep work blog post for the Zephyr 3.0 work in #1143
> feat: Add blog post with Zephyr 3.0 prep.

- app/boards/interconnects/pro_micro/pro_micro.zmk.yml
Modify description of pro micro interconnect yml file. See changes.
> Emphasize AMR processor incompatibility with ZMK

- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
- docs/src/hardware-metadata-static-plugin/index.js
Added /hardware-metadata.json to the ZMK website. This gives external tools a way to grab all hardware metadata at once.
> feat(docs): Add aggregated metadata to website

- docs/blog/2022-04-10-zmk-sotf-5.md
Still a draft, getting together the broad outline for feedback.
> feat(blog): Add SOTF #5.

- docs/docs/features/backlight.md
- docs/docs/features/underglow.md
This should help reduce confusion for newcomers.
> fix(docs): Clarify backlight & underglow use cases

- docs/blog/2022-04-02-zephyr-3-0.md
This helps anyone that has their own led_strip definition
> docs: LED include needed for Zephyr 3.0.0 upgrade

- docs/docs/features/backlight.md
> doc(backlight): small typo

- docs/src/setup-script-generation-plugin/index.js
- docs/src/templates/setup.ps1.mustache
- docs/src/templates/setup.sh.mustache
For now, disallow wired split combination during setup.
> feat(setup): Disallow split w/ wired controller.

- docs/package-lock.json
* Use npm version matching Netlify to fix up our lock file.
> fix(docs): Fix acorn dep in package lock file.

- app/src/split/bluetooth/central.c
* When a peripheral disconnects from a centraly, raise position events
to release any active positions from that
peripheral.
Closes #1339
> fix(split): Raise release events on disconnect.

- docs/docs/behaviors/key-press.md
Co-Authored-By: Robert U <978080+urob@users.noreply.github.com>
> fix(docs): Update keycode usage ID for numeric 4 in key-press.md

- app/dts/bindings/behaviors/zmk,behavior-mod-morph.yaml
Fixes the mod morph behavior's description in its definition
> fix(behaviors): Fix mod morph description

- docs/docs/config/behaviors.md
- docs/docs/config/kscan.md
- docs/docs/config/system.md
- docs/docs/config/underglow.md
- docs/docs/development/new-behavior.md
- docs/docs/development/new-shield.md
Building on top of #722, this PR incorporates suggestions from me and @dxmh. I also updated to add new Kconfigs for underglow from #1010 and some refactoring to account for #1314. It might be better to merge this without squashing.
> fix(docs): Improve configuration documentation

- docs/docs/user-setup.md
Found and fixed some typos on the user-setup page.
> fix(docs): typo fixes

- app/src/backlight.c
Removed deprecated macros, replaced them with new Zephyr 3 implementation, tested and working on real hardware
> chore(lighting): fix deprecation

- .github/workflows/build-user-config.yml
Minor refactor of west build step for consistency.
> fix(ci): Refactor west build step

- app/boards/shields/cradio/cradio.keymap
Improved cradio default keymap with better indentation and more features.
> Cradio keymap improvements

- app/boards/nrf5340dk_nrf5340_cpuapp.conf
- app/boards/nrf5340dk_nrf5340_cpuapp.overlay
- Fixed a stack overflow when enabling Bluetooth.
- Increased the I2C buffer size to support displays.
> fix(boards): Fix nRF5340 DK issues

- docs/docs/behaviors/sensor-rotate.md
This PR brings the new _Sensor Rotation_ behavior documentation in line with the parameter ordering used in the behavior implementation and the existing encoder documentation.
> fix(docs): switch sensor rotate parameter order

- app/Kconfig
> chore: Fix formatting of Kconfig setting.

- .github/workflows/build-user-config.yml
* Refactor preparation step using shell parameter expansion to insert shield variable if `matrix.shield` is not null.
* Use quotes as simple guards against input injection.
> fix(ci): Refactor prepare variable step

- docs/docs/development/build-flash.md
- docs/docs/user-setup.md
Add a note about the UF2 drive that automatically unmounts itself to restart, which may surprise some new users.
> feat(docs): A note about unmounting UF2 drive

- README.md
- docs(readme): add missing punctuations
- docs(readme): add link to MIT license
> docs(readme): improve writing

- docs/docs/behaviors/macros.md
- docs/docs/config/behaviors.md
This PR improves Parameterized Macros documentation.
> docs(macros): Improve parameterized macros docs

- docs/docs/behaviors/caps-word.md
> fix typo in caps-word.md

- docs/docs/development/usb-logging.md
Improve recommendations on where to set the logging Kconfig and note a couple extra config that are commonly changed related to logging. I would appreciate a confirmation on my understanding and explanation of these two.
> feat(docs): Detail logging and note extra useful options

- app/boards/shields/waterfowl/waterfowl.dtsi
- app/boards/shields/waterfowl/waterfowl.keymap
- app/boards/shields/waterfowl/waterfowl_left.overlay
- app/boards/shields/waterfowl/waterfowl_right.overlay
Updated Waterfowl configs to comply with encoder sensors changes from #1841 
@JW2586 FYI :)
> feat(shields): add right encoders support to Waterfowl

- app/boards/shields/reviung53/Kconfig.defconfig
- app/boards/shields/reviung53/Kconfig.shield
- app/boards/shields/reviung53/boards/nice_nano.overlay
- app/boards/shields/reviung53/boards/nice_nano_v2.overlay
- app/boards/shields/reviung53/reviung53.conf
- app/boards/shields/reviung53/reviung53.keymap
- app/boards/shields/reviung53/reviung53.overlay
- app/boards/shields/reviung53/reviung53.zmk.yml
- [n/a] If split, no name added for the right/peripheral half
> Reviung53 shield definition

- docs/docs/features/debouncing.md
Small fix on an outdated note.
> fix(docs): Fix debouncing driver support note

- .github/workflows/build-user-config.yml
This reverts commit c1bf35ce1de4b7d99c034300c9a813a0a3d11669.
> Revert "feat(build): Add support for artifact-name in build.yaml"

- docs/docs/hardware.mdx
It looks like the text in this page hasn't been touched in some time. I updated it the way I thought best to remove the outdated info, but I am open to feedback!
> fix(docs): Update outdated information in the hardware page

- .github/workflows/build.yml
Latest test run had odd github-script related errors, so trying upgrading to the latest version.
> fix(ci): Upgrade to github-script@v7

- docs/docs/behaviors/bluetooth.md
> fix(docs): Fix remark on &bt parameter 2

- app/src/hid_indicators.c
- app/src/split/bluetooth/central.c
- app/src/split/bluetooth/service.c
Missed a few event manager uses that were behind feature flags.
> fix: Fix missed event manager usages from refactor.

- .github/workflows/build.yml
Reported by fish on discord, I got the syntax wrong here it looks like.
> fix(ci): Use proper variable expression.

- .github/workflows/build-user-config.yml
> fix(ci): Update one lingering upload-artifacts action.

- docs/docs/config/system.md
Fixing in correct path in the doc.
> docs: correcting file path in config.md

- docs/docs/behaviors/mod-morph.md
Fixed the formatting in files that weren't passing pre-commit checks.
> chore: Fix formatting

- .github/workflows/build-user-config.yml
* Improve GHA caching by using a fixed temporary directory when using one.
> fix(build): Used a fixed temp dir for caching.

- app/keymap-module/modules/modules.cmake
* Handle board keymap location for boards with Zephyr board revisions included.
* Includes bare non-revision file and a revision specific keymap in case newer revision changes the layout/key positions.
> fix(build): Properly board revision keymaps.

- docs/docs/features/bluetooth.md
Added a remark noting issues with pairing in dual boot systems, any suggestions to improve technical correctness would be appreciated!
I wasn't around for #549 but I prefer this more concise approach, where we wouldn't have to maintain or take responsibility for an extended guide. This still remarks that the issue exists and hints at (unofficial) workarounds.
> feat(docs): Add a note on using BT with dual boot systems

- .gitignore
Add `app/.cache` (clangd cache directory) to `.gitignore`
> feat(gitignore): add clangd cache folder

- app/src/rgb_underglow.c
When going idle or disconnecting USB, the "is RGB on?" state was not properly stored/reverted when waking up, this should fix it.
Cant test it myself as i dont have a RGB board, but according to @awkannan on discord, it works 🤓
> fix(rgb): auto-off logic

- app/src/behaviors/behavior_soft_off.c
This should fix the issue I reported in #2300
> soft_off: Adding delay in central for split keyboards  

- docs/docs/config/index.md
- docs/docs/troubleshooting/connection-issues.mdx
Added a note on USB logging, pointing people towards output selection.
Added a note on the oscillator issue and how to resolve it for the nRF52 using the "internal oscillator".
Made the config/index page a bit more explicit about which files are searched for in the boards and shields folders.
> feat(docs) Minor improvements to the docs

- docs/package-lock.json
This should hopefully resolve the `ws` security alert that can't be resolved by its own.
Only impact I see so far is the sidebar of blog posts are categorized by year.
> chore(deps): npm update on docs

- docs/docs/development/hardware-integration/studio-setup.md
> docs(fix): broken anchor in studio setup

- app/src/ble.c
Unable to run anything since this prevents any kind of build for me
> Fixing compile bug in ble.c

- app/src/ext_power_generic.c
Currently ext_power only supports a single GPIO, which causes issues for board with separate power management channels for RGB and displays. This is a small patch to allow all the pins in the gpios phandle array provided to ext_power to be switched. 
Tested working on a board with two ext_power gpios and also tested to confirm no regressions on single ext_power gpio boards
> feat(ext power): Support multiple ext_power GPIOS

- app/src/studio/behavior_subsystem.c
- app/src/studio/core_subsystem.c
- app/src/studio/keymap_subsystem.c
- app/src/studio/rpc.c
Adding some tooling to make it easier to dig into the stack usage for our RPC encode/decode bits.
> Studio: RPC stack analysis

- docs/docs/troubleshooting/connection-issues.mdx
A minor improvement, as suggested by @caksoylar on Discord.
> docs: Added a note on bluetooth profiles under "unable to connect to device"

- app/boards/arm/bdn9/bdn9_rev2.dts
- app/boards/shields/reviung41/reviung41.overlay
- app/dts/layouts/gtips/reviung41.dtsi
- app/src/physical_layouts.c
* When building with ZMK Studio, assert that we have physical layouts, and those layouts have key information set.
> feat: Build asserts for requires studio layout bits.

- app/boards/arm/corneish_zen/corneish_zen.dtsi
> fix(boards): Corneish-zen physical layout

- app/src/studio/Kconfig
* Imply nanopb setting for reduced stack usage.
> fix(studio): Reduce stack usage.

- docs/docs/config/studio.md
- docs/docs/development/hardware-integration/physical-layouts.md
- docs/docs/development/studio-rpc-protocol.md
- docs/docs/features/studio.md
- docs/docs/keymaps/behaviors/studio-unlock.md
- docs/docusaurus.config.js
* Add a toplevel ZMK Studio link in our header.
> feat(docs): Add ZMK Studio link.

- docs/docs/keymaps/behaviors/hold-tap.mdx
- docs/docs/troubleshooting/connection-issues.mdx
> docs: Add retro-tap sentence and fix anchor

- docs/netlify-ignore-command.sh
- docs/netlify.toml
Add a separate ignore script that checks git changes but also only deploys main and version branches to allow us to deploy versioned docs.
> docs(ci): Netlify ignore command to check branch

- .github/pull_request_template.md
Added a bullet point reminding people to update the docs about whatever changes were made, when applicable.
> chore: Docs bullet point in PR checklist

- docs/docs/development/hardware-integration/dongle.mdx
> docs: Fix incorrect dongle `kscan` value

- docs/docs/features/studio.md
> docs(studio): Link to ZMK Studio download page

- docs/docs/faq.md
Update FAQ entry for 2.4GHz/dongle question and add a link to the dongle documentation.
> docs: Update dongle FAQ entry

- docs/docs/development/hardware-integration/new-shield.mdx
- docs/docs/development/local-toolchain/build-flash.mdx
- docs/docs/features/modules.mdx
> docs: Improved some links to modules

- docs/docs/features/studio.md
> docs: Add "planned: import/export keymap" to the studio features page

- app/src/combo.c
Properly mark combo configs as `const` so they are place in flash, not RAM.
Example build on my Le Chiffre STM32 PCB, which is f072, which is more RAM constrained:
On `main`:
```
[7/7] Linking C executable zephyr/zmk.elf
Memory region         Used Size  Region Size  %age Used
FLASH:       41628 B       128 KB     31.76%
RAM:        9600 B        15 KB     62.50%
RetainedMem:          0 GB          1 B      0.00%
IDT_LIST:          0 GB         2 KB      0.00%
```
This PR:
```
[194/194] Linking C executable zephyr/zmk.elf
Memory region         Used Size  Region Size  %age Used
FLASH:       41628 B       128 KB     31.76%
RAM:        9120 B        15 KB     59.38%
RetainedMem:          0 GB          1 B      0.00%
IDT_LIST:          0 GB         2 KB      0.00%
```
> refactor(combos): Reduce combo RAM usage

- docs/docs/development/local-toolchain/setup/container.mdx
> Update container.mdx for clarity about ZMK repo folder location

- docs/docs/user-setup.mdx
Fix what I broke in #2840 by renaming the tab value in one place and not another. Thanks to users who reported in Discord.
> docs: Fix powershell tab in user setup

- docs/blog/2025-03-20-contributor-sync-1.md
- docs/blog/authors.yml
> blog: Add meeting notes from February

- app/src/combo.c
> fix(combos): Properly clean up all old candidates.

- app/src/battery.c
Fix BAS battery level showing 100% if controller boots up with 0% battery charge.
Closes zmkfirmware/zmk#2972
> fix(core): Correctly sync BAS battery level

- docs/docs/config/index.md
> docs: correct a misleading _defconfig description

- docs/docs/config/kscan.md
I think there's a missing semicolon here?
> Update kscan.md to add missing semicolon in composite example 

- app/boards/shields/redox/redox-layouts.dtsi
- app/boards/shields/redox/redox.dtsi
I already tested this layout inside ZMK Studio
Please let me know if there is something else to do.
> Add physical layout for Redox shield
